rust-osdev/uefi-rs

src/lib.rs, src/table/boot.rs, tests/src/boot.rs
Hi @GabrielMajeri 
This is a slightly awkward implementation of `get_memory_map` that I wrote for a project I'm doing and this PR is mostly to see if you have any interest in such an implementation or if I should keep this as a helper in my own library. Also if you have any better suggestions on how to implement this I would love to know.
=> Implement `get_memory_map`

uefi-services/src/lib.rs
this change was merged in rust-lang/rust#50338. I don't know how regularly you expect users to update to the lastest nightly, but I just updated last night and got this change, and this fixes it for me. I built it with this change and ran the test harness and it all seemed to work.
=> use panic_implementation instead of panic_fmt

uefi-alloc/src/lib.rs
This fixes compilation under current nightly related to removal of Opaque.  It also removes a couple of comments that were obsoleted by the changes in the recent nightly, and does the closest thing to what those comments suggested.
=> Removed Opaque and cleanup.

src/error/status.rs, src/table/boot.rs
Since forgetting to check status codes is a common mistake in APIs that use them, I think that marking the UEFI status codes as must_use is a good idea.
I added assertions in the two places where they were not checked (reasonably, as there is only one valid reply in the current spec), which should act as a protection against buggy firmwares or future revisions of the spec adding new status codes.
=> Mark EFI status codes as must_use and check them

uefi-test-runner/src/boot/memory.rs, uefi-test-runner/src/proto/console/gop.rs, uefi-test-runner/src/proto/console/stdout.rs
So, while I was around the test suite trying to fix the issue discussed in #1, I thought I could as well do some extra cleanup.
=> Some test suite tweaks

src/table/boot.rs, uefi-test-runner/src/boot/misc.rs, uefi-test-runner/src/boot/mod.rs
This implements the `set_watchdog_timer` function and correspondent test.
=> Add set_watchdog_timer implementation and test

src/table/boot.rs, uefi-test-runner/src/boot/memory.rs
These functions can be used to violate type-safety, memory-safety and thread-safety, and are in that sense textbook examples of unsafe functions ;)
=> Mark CopyMem and SetMem as unsafe

src/proto/console/serial.rs, uefi-logger/src/lib.rs, uefi-test-runner/build.py, uefi-test-runner/src/proto/console/serial.rs
These improvements were mostly discussed in #1, with a couple of extra ideas I got since then:
- uefi-logger's output is annotated with the log level on a line-by-line basis.
- Headless vs non-headless QEmu configurations are now much closer to each other. Basically, the only difference is whether QEMU spawns an X11 window with the display or not.
- The Python code intercepts QEMU's output and strips ANSI escape sequences from it before forwarding it to stdout, so the UEFI code cannot mess up your terminal anymore.
=> Annotated logs, stdout cleanup, and headless display

BUILDING.md, README.md, src/proto/console/gop.rs, src/proto/console/pointer/mod.rs, src/proto/console/serial.rs, src/proto/console/text/input.rs, src/proto/console/text/output.rs, src/proto/macros.rs, src/proto/media/file.rs, src/proto/media/file_system.rs, src/table/boot.rs, src/table/runtime.rs, uefi-test-runner/src/main.rs
This PR replaces the `extern "C"` ABI with `extern "win64"`. This ensures that an ELF kernel can safely call the functions in this crate, but we drop support for 32-bit.
Temporary solution for #38
=> Fix function ABI

src/proto/console/gop.rs, uefi-test-runner/src/proto/console/gop.rs
The GOP example wrote to the framebuffer without using `write_volatile`, meaning the compiler was allowed to reorder or discard these writes. This PR fixes that.
=> Use `write_volatile` in the GOP example

src/proto/console/pointer/mod.rs, uefi-test-runner/src/proto/console/pointer.rs
The associated test used to print an error on every run because the Status::NotReady output was incorrectly interpreted as an error. In the context of this function, it means that the pointer state has not changed since the last query, which is normal.
Since this output is not really an error, I think it is better modeled by returning an optional pointer status, so I changed that in simple pointer protocol interface.
=> Improve simple pointer protocol state query

src/proto/console/gop.rs
This MR tries to improve the usability and safety of the Graphics Output Protocol by...
- Bringing documentation in sync with the UEFI spec's level of detail.
- Adding memory safety checks to the Blt function (if it is safe, it is not allowed to do buffer overflows)
* We can later extract an unsafe back-end if that turns out to be a perf bottleneck for someone.
- Clarifying in which circumstances a BltBuffer stride must and mustn't be specified using an enum.
- Panicking if the framebuffer is accessed in a Blt-only mode
* While this function is unsafe, I think the check is cheap enough (framebuffer is normally acquired once and used many times) and the error easy enough to make.
- Hiding the reserved byte of BltPixels (allowing the user to modify it is a type-safety risk).
- Homogeneizing …
=> Graphics output protocol cleanup

Cargo.toml, src/error/completion.rs, src/error/mod.rs, src/error/status.rs, src/lib.rs, src/prelude.rs, src/proto/console/gop.rs, src/proto/console/pointer/mod.rs, src/proto/console/serial.rs, src/proto/console/text/input.rs, src/proto/console/text/output.rs, src/proto/media/file.rs, src/table/boot.rs, uefi-alloc/src/lib.rs, uefi-exts/src/boot.rs, uefi-logger/src/lib.rs, uefi-test-runner/src/boot/memory.rs, uefi-test-runner/src/boot/misc.rs, uefi-test-runner/src/main.rs, uefi-test-runner/src/proto/console/gop.rs, uefi-test-runner/src/proto/console/pointer.rs, uefi-test-runner/src/proto/console/serial.rs, uefi-test-runner/src/proto/console/stdout.rs, uefi-test-runner/src/proto/mod.rs
UEFI has warnings, which represent non-fatal errors. Currently, we treat them as fatal errors, which is somewhat pessimistic. This PR explores a different strategy which allows the user to do various things with warnings including pattern-matching them, logging them silently, or handling them as errors.
Some errors which were previously discarded, such as `EFI_TIMEOUT` in serial communication, are now reported as warnings.
Fixes #52.
=> Handle UEFI warnings more cleanly

src/proto/console/gop.rs, uefi-test-runner/src/proto/console/gop.rs
Here is a different take on the direct framebuffer interface:
- A low-level (pointer, length) pair is returned instead of a high-level slice, since providing a slice gives the user the wrong impression that non-volatile writes are okay.
- The unsafety barrier is shifted from the GOP to its client. After all, `GraphicsOutput::framebuffer()` is perfectly safe per se in the sense that there is no incorrect input or wrong call circumstance that will cause it to do unsafe things. It is the caller who is going unsafe by writing into the framebuffer after that.
Longer-term, the interface could be improved further by providing a more ergonomic way to do volatile writes (which would feel closer to the original slice abstraction).
=> Slight redesign of the raw framebuffer interface

BUILDING.md, src/error/completion.rs, src/error/mod.rs, src/prelude.rs, src/proto/console/gop.rs, src/proto/console/pointer/mod.rs, src/proto/console/serial.rs, src/proto/console/text/output.rs, src/proto/macros.rs, src/proto/media/file.rs, src/proto/media/fs.rs, src/table/boot.rs, src/table/cfg.rs, src/table/mod.rs, src/table/runtime.rs, src/table/system.rs, uefi-alloc/src/lib.rs, uefi-exts/src/boot.rs, uefi-logger/src/lib.rs, uefi-services/src/lib.rs, uefi-test-runner/src/main.rs, uefi-test-runner/src/proto/console/gop.rs, uefi-test-runner/src/proto/console/mod.rs, uefi-test-runner/src/proto/console/pointer.rs, uefi-test-runner/src/proto/console/serial.rs, uefi-test-runner/src/proto/debug.rs, uefi-test-runner/src/proto/mod.rs
This PR gives uefi-rs a solid type-safety cleanup (e.g. no more "usize" as a substitute for pointers, and using 'static when that's a lie is avoided). Most importantly, however, it also fixes #3 by providing a safe method to exit UEFI boot services, ensuring that the borrow checker will warn you if you try to use boot services after the fact.
Achieving this result required a significant redesign of how protocols work. Previously, protocols were assumed to live forever, whereas now they are treated as a reference to UEFI boot services. Some lifetime inconvenience results, and impl Trait may not be used quite as frequently as before, but overall the patch remains remarkably simple considering what it does.
The type-safety cleanup fixes #23 .
=> Type-safety cleanup and safe exit from boot services

.travis.yml
The CI is broken. I think that's because the clippy and rustfmt components changed name during stabilization.
=> Making the CI work again

src/lib.rs, src/prelude.rs, src/result/mod.rs
In https://github.com/rust-osdev/uefi-rs/pull/78 `ResultExt2` was added to handle the special case of an Error not have an additional payload. However, this isn't necessary, as a `where` clause for `Default` can also handle this case.
As a bonus, it works fine on `Result<Output, Option<usize>>` values, it will just set the payload to `None` if a warning triggers and error.
=> Replace ResultExt2 with a where clause

src/result/mod.rs
Most functions in the uefi package return a `Result<Output>`,  but some return `Result<Output, ErrData>`. This makes it challenging to write your own methods returning `Resut<T>`, especially because [the `Error` type is not exported](https://github.com/rust-osdev/uefi-rs/blob/b57af64d905decb43fe458641eb5976d378874dc/src/lib.rs#L40).
An easy way to fix this is to just add a method converting a `Result<Output, ErrData>` to a `Result<Output>`, keeping the status but discarding the data.
=> Add discard_errdata() method to Result

src/proto/console/gop.rs, src/table/boot.rs
Both `BltPixel` and `MemoryDescriptor` are already fully packed _and_ fully aligned structures. Thus, adding `#[repr(packed}]` does nothing except:
- makes certain field accesses unsafe
- allow the struct to be safely misaligned in memory
This doesn't seem like the intent of the code, so removing `packed` should make using these structs easier. Really, I would want something like #[repr(perfect_alignment)] and have the compiler error if any padding would need to be inserted for #[repr(C)].
=> Remove unnecessary repr(packed)

src/proto/media/file/dir.rs, src/proto/media/file/mod.rs
Currently all of the structs that implement `FileProtocolInfo` are unsized DSTs. As generic trait bounds implicitly include constraint of `Sized`, we have to explicitly use `FileProtocolInfo + ?Sized` whenever we want to use FileProtocols in a generic manner.
=> Use ?Sized with get_info and set_info

src/proto/media/file/dir.rs, src/proto/media/file/info.rs, src/proto/media/file/mod.rs, src/proto/media/file/regular.rs, src/proto/media/fs.rs
In `proto::media::file`, `File` and `Directory` share most of their functionality in common. In general, such common functionality is easier to deal with in rust though traits.
This change refactors the existing code into 3 structs and 1 trait
- `File` a trait containing all the functionality common to all file handles.
- `FileHandle` a basic file handle struct, allowing for conversion to the more specific structs. This is what `open()` returns.
- `RegularFile` a normal data file, allowing for direct read/write.
- `Directory` a directory file, allowing for enumerating its contents. This is returned by `open_volume()`.
There are three main questions I have about this change.
1. There isn't really any reason to have a lifetime bound on `File`, `Directory`, etc... Should I change the …
=> Refactor File types to have common functionality use traits

uefi-exts/Cargo.toml, uefi-exts/src/file.rs, uefi-exts/src/lib.rs
The change in #89 did not properly handle allocation failures. On
failure, `alloc()` returns a null pointer, and this is not checked.
This change moves buffer allocation to the new Alloc API, and correctly
handles allocation failure and potential unsafety with zero-sized alloc
requests.
I also removed the dependency on `uefi-services` from `uefi-alloc`. The
dependency isn't needed, and now users can use `uefi-exts` with their
own allocators.
=> Properly handle allocation failure

src/table/boot.rs, uefi-exts/src/boot.rs, uefi-test-runner/src/main.rs, uefi-test-runner/src/proto/console/gop.rs, uefi-test-runner/src/proto/console/pointer.rs, uefi-test-runner/src/proto/console/serial.rs, uefi-test-runner/src/proto/debug.rs
Fixes #79 
This change lets users avoid allocating when they just want to find a single implementer of a protocol.
=> Use UEFI's locate_protocol to replace find_protocol

src/lib.rs, uefi-exts/src/lib.rs, uefi-test-runner/src/main.rs
`alloc` and `try_from` are now stable
=> Remove #![feature()] for stable features

src/proto/console/pointer/mod.rs, src/proto/console/text/input.rs, src/table/boot.rs, src/table/runtime.rs
As said in the title, this PR simply replaces any uses of mem::uninitialized in the repo with mem::MaybeUninit. I've run the test-runner to make sure that everything checked there is still working, and encountered no errors.
=> Replace all usages of mem::uninitialized with mem::MaybeUninit

src/proto/mod.rs, src/proto/pi/mod.rs, src/proto/pi/mp.rs, uefi-test-runner/build.py, uefi-test-runner/src/proto/mod.rs, uefi-test-runner/src/proto/pi/mod.rs, uefi-test-runner/src/proto/pi/mp.rs
This protocol allows one to bootstrap their OS/hypervisor/whatever into MP mode using UEFI facilities instead of doing it manually.
Specification link (PDF p. 453, document p. 171): https://uefi.org/sites/default/files/resources/PI_Spec_1_6_A_final_Feb4.pdf#page=453
StartupAllAPs and StartupThisAP FFI functions currently wrapped in a blocking manner only.
=> UEFI MP Services Protocol support

BUILDING.md, src/lib.rs, src/proto/console/gop.rs, src/proto/console/pointer/mod.rs, src/proto/console/serial.rs, src/proto/console/text/input.rs, src/proto/console/text/output.rs, src/proto/media/file/mod.rs, src/proto/media/fs.rs, src/proto/pi/mp.rs, src/table/boot.rs, src/table/runtime.rs, uefi-macros/src/lib.rs, uefi-test-runner/src/main.rs, uefi-test-runner/src/proto/pi/mp.rs
Fixes #38 
Needs the very latest nightly (might not be released yet ^^).
=> Use EFIAPI ABI introduced in latest nightly

src/result/completion.rs, src/result/mod.rs
Unfortunately, I just don't manage to bring back a working uefi-rs dev environment on my machine, so I'll let someone who can actually test this judge. But "by eye" this looks like it couldn't possibly cause any regression in code that uses Completion correctly.
=> Fix Completion documentation and add assertion that status isn't an error

src/data_types/strs.rs
This is my attempt to implement `Debug` and `Display` traits for the `CStr16` type using the traits that have already been implemented for `Char16`.
Strangely if I try to format `\u{0}`, `Display` panics while `Debug` does not, but I don't see any essential differences between the implementations of `Char16` for `Debug` and `Display`. It seems that the following code is not working for `impl Display for Char16`:
https://github.com/rust-osdev/uefi-rs/blob/ba8cb63c395f77acd0fa64a29395af2b8b334d20/src/data_types/chars.rs#L121-L123
This is the panic output:
```
ERROR: Panic in /Users/tsuki/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/result.rs at (1189, 5):
ERROR: called `Result::unwrap()` on an `Err` value: Error
```
So for now, the formatting process just …
=> Implement Debug&Display traits for CStr16

src/table/boot.rs, src/table/runtime.rs
According to the UEFI spec, `SetVirtualAddressMap` is used by the OS loader to map the runtime service memory region to virtual addresses after `ExitBootServices` is called. A bootloader will normally map the kernel address space to the higher-half and then jump to the kernel, and we can't leave the `RUNTIME_SERVICES_CODE` and `RUNTIME_SERVICES_DATA` alone. However, this process includes some absolute address relocation done by the runtime services themselves, which is an event triggered by the `SetVirtualAddressMap` call. Thus, `SetVirtualAddressMap` may not be "useless" and this is a patch to add an interface for it.
Closes #107 
Signed-off-by: imtsuki <me@qjx.app>
=> Add `set_virtual_address_map` interface in runtime services

Cargo.toml, src/proto/loaded_image/mod.rs, src/proto/mod.rs
Mainly, this allows applications to access command line arguments passed from the EFI shell or a boot option.
Note: this relies on the changes in GabrielMajeri/ucs2-rs#7. When that is merged and a new version published, I can update this to use the new version of `ucs2`.
=> Add support for the LoadedImage protocol

uefi-test-runner/build.py
The target directory is not necessary `target`. People may override it with `build.target-dir` in Cargo config file, for example.
This PR changes it to read this information from `cargo metadata` so that the correct target directory can be located.
=> Use cargo metadata for target dir

src/logger.rs, src/proto/console/text/output.rs
This PR fixes #121.
Signed-off-by: imtsuki <me@qjx.app>
=> Fixes #121: ignore EFI_DEVICE_ERROR in output_string

.github/workflows/rust.yml
=> Set up CI through GitHub Actions

.github/workflows/rust.yml
Update CI workflow to use the `clippy-check` action, which displays the lints in the GitHub interface.
=> Use specialized Clippy action

src/proto/media/file/mod.rs
If `NamedFileProtocolInfo` isn't accessible, rustdoc fails to document
impl blocks of the concrete instantiations such as `FileInfo`. (Related upstream bug: https://github.com/rust-lang/rust/issues/32077)
__Before__:
__After__:
=> Re-export `NamedFileProtocolInfo`

src/lib.rs
Add the negative_impls feature.
(In case this gets merged do you mind releasing a new version for uefi and uefi-services?)
=> Fix compilation on latest nightly.

src/table/boot.rs
(sorry, messed up the other pr)
From the spec:
> A pointer to the size, in bytes, of the MemoryMap buffer. On input, this is the size of the buffer allocated by the caller. On output, it is the size of the buffer returned by the firmware if the buffer was large enough, or the size of the buffer needed to contain the map if the buffer was too small. 
Also, the `pub fn memory_map<'buf>()` fn already takes this into account when creating the iterator, and sets the length as `map_size / entry_size`.
=> map_size is already the required size in bytes for the buffer.

Cargo.toml, src/logger.rs
As discussed in the context of #123 , this PR enables configuring whether logger errors should be ignored or not at compile time.
Fixes #123 .
=> Add cargo feature for ignoring logger errors

uefi-services/Cargo.toml
rust-lang/rust#69171 was merged a couple of days ago, which finally dropped support of the old deprecated `asm!` syntax. `uefi-services` depends on an old version of `x86_64`, so that it won't be built successfully on latest nightlies.
Signed-off-by: imtsuki <me@qjx.app>
=> Bump x86_64 dependency version to fix build on latest nightlies

src/proto/console/gop.rs
Small fix in the conversion from a `u32` to a `BltPixel`.
Because the precedence of the shift operator is stronger than the bitwise AND, the masks are shifted before applying, resulting in all channels being set to the blue channel.
Without the additional parenthesis, `green: (color & 0x00_FF_00 >> 8)` expands to `green: (color & 0x00_00_FF)` first.
=> Fix `BltPixel::from` conversion

Cargo.toml, src/table/system.rs, uefi-hello-world-aarch64/.cargo/aarch64-unknown-uefi.json, uefi-hello-world-aarch64/.gitignore, uefi-hello-world-aarch64/Cargo.toml, uefi-hello-world-aarch64/README.md, uefi-hello-world-aarch64/build.py, uefi-hello-world-aarch64/src/main.rs, uefi-services/Cargo.toml, uefi-services/src/lib.rs
Although coincidence and clearly overlaps (silly me I thought would be no PR on this anyway), I still decided to PR this as this can be seen as a simpler version of #120. 
It also include patches to workaround the branch evaluation on the x86_64 check but...with a much better format I think. 
A "managed" main method is also experimented on, as it panics if an error status returns, and shutdown like test runner if it succeeded. N.B. I copied the folder and removed most stuff from test runner. 
You can also see a very crude way to shadowing std crate into bare-metal environment by the use of `no-std-compat`. Most if not all things from std works, like std::collection::BTreeMap in this example (so should the rest like HashMap), yet floating point support clearly doesn't present. (I tried to …
=> Add basic AArch 64 support

.github/workflows/rust.yml, uefi-test-runner/Cargo.toml, uefi-test-runner/build.py, uefi-test-runner/src/proto/pi/mp.rs
Fixes our current CI.
- fixes QEMU install.
- adds a new `--ci` flag and Cargo feature which will disable the failing test.
- schedules our CI to run daily, to check for issues with new nightlies.
- disables KVM acceleration in CI.
Closes #139.
=> Update Rust CI workflow

src/proto/console/gop.rs
Incorporates the information from the wiki page on the Graphics Output Protocol into the module documentation.
Fixes #140.
=> Update GOP docs with text from wiki

.cargo/config, .github/workflows/rust.yml, BUILDING.md, uefi-test-runner/Cargo.toml, uefi-test-runner/build.py, uefi-test-runner/src/main.rs
Updates the crate to use [the recently added Cargo support](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#build-std) for automatically building `core` in cross-compiling scenarios.
Based on the instructions in the [`cargo-xbuild` README](https://github.com/rust-osdev/cargo-xbuild#alternative-the-build-std-feature-of-cargo)
=> Replace `cargo-xbuild` with `build-std` feature

.github/workflows/rust.yml
The `clippy-check` action currently has a [pretty big caveat](https://github.com/actions-rs/clippy-check#limitations), in the sense that it cannot print the status on PRs from forked repositories. This is not exactly desired, so this PR opts for the simpler option of just running clippy directly.
=> Manually run clippy instead of relying on custom action

src/proto/loaded_image/mod.rs
Add a method to get `image_base` and `image_size` from LoadedImage. Since these fields are private, a getter is needed to retrive them.
I'm open to suggestions on a better method name.
closes #147
=> Add method to return (image_base, image_size) to LoadedImage

src/proto/loaded_image/mod.rs
It seems this change was lost during the rebase.
=> Rename `image_info` to `info`

src/table/boot.rs, src/table/system.rs, uefi-test-runner/src/boot/memory.rs
=> Hide the `MemoryMapIter` type from the API

src/lib.rs, src/proto/loaded_image/mod.rs, src/table/boot.rs
This upstreams two local changes from Pebble's fork of `uefi-rs`, which would allow us to use the official release:
- Fixes a bug in `LoadedImage::load_options` where a slice is created from a null pointer if no load options are passed, causing a panic. Fixed by returning an empty string if there aren't any load options. Also documents this behaviour.
- Provides a method for constructing custom `MemoryType`s, checking that it's valid.
=> Upstream two changes from Pebble's fork

src/table/boot.rs, src/table/system.rs
This allows iterating the list multiple times, which is for example useful for retrieving some information about the list (e.g. amount of usable memory) without destroying the iterator.
=> Make memory map iterator clonable

src/table/system.rs
Forgot to change this in #164.
=> Use `ExactSizeIterator` in `exit_boot_services`

uefi-services/src/lib.rs
Though `llvm_asm!` is still supported, it won't be stable. `asm!` is better.
=> Use new `asm!` syntax

uefi-services/Cargo.toml, uefi-services/src/lib.rs
With this PR, the `uefi-services` crate's `panic_handler` can now be toggled off with the `no_panic_handler` feature.
Hope I'm doing this right as this is my first PR.
=> Made panic_handler optional

src/exts.rs, src/lib.rs, src/result/status.rs, src/table/runtime.rs
Renames an unstable feature, updates to the latest `alloc` API changes, and then fixes clippy and format issues.
=> Fix CI with latest nightly

CONTRIBUTING.md
Adds a mention to `CONTRIBUTING.md` that new protocols can only be defined in the `uefi` crate.
Should help with issues like #184
=> Clarify how new protocols can be defined

src/proto/loaded_image/device_path.rs, src/proto/loaded_image/mod.rs, src/table/boot.rs
My [previously merged pull request](https://github.com/rust-osdev/uefi-rs/pull/187#issue-533203544)'s code comments had various spelling errors, phrasing inconsistencies, and generally bothered me with their quality—I've gone back and edited them so they match the quality I'd expect from a public crate.
All I've edited are code comments that were made for code in my [previous pull request](https://github.com/rust-osdev/uefi-rs/pull/187#issue-533203544).
=> Fixing various phrasing inconsistencies and spelling errors in prev PR's comments

src/proto/console/gop.rs, src/proto/loaded_image/device_path.rs, src/proto/pi/mp.rs, uefi-services/Cargo.toml, uefi-test-runner/src/proto/console/gop.rs, uefi-test-runner/src/proto/pi/mp.rs
This is needed because nightly removed the const_in_array_repeat_expressions feature.
=> Update x86_64 requirement from 0.13.1 to 0.13.2

src/table/boot.rs, uefi-test-runner/src/main.rs
Prevents issues like #175, since getting the boot device is a common task.
=> Add helper function for retrieving the boot FS

src/proto/media/file/regular.rs
- `into_kind` doesn't exist. should be typo for `into_type`
=> Fix typo in regular.rs

src/proto/media/file/mod.rs
- To get file info, we have to pass buffer which has sufficient capacity
* https://github.com/rust-osdev/uefi-rs/blob/master/src/proto/media/file/mod.rs#L115
- When the file-name is known, we can allocate the buffer of exactly required size
* that is, `size_of::<Header>() + name_length`
- It'd be helpful to expose Header types so that we can calculate the buffer size based on that
=> Expose NamedFileProtocolInfo's Header types

src/lib.rs, uefi-services/Cargo.toml, uefi-test-runner/Cargo.toml
The `qemu-exit` crate also must be fixed to build this crate with the latest nightly. I sent a patch (https://github.com/andre-richter/qemu-exit/pull/18).
=> Fix the build error on the latest nightly

src/lib.rs, src/result/status.rs, uefi-test-runner/src/proto/pi/mp.rs
=> Switch to the newer `Try` trait API

src/proto/media/mod.rs, src/proto/media/partition.rs, uefi-test-runner/src/proto/media/mod.rs
This is described in section 13.18 of the UEFI specification. It
provides information about MBR or GPT partitions.
=> Add PartitionInfo protocol

src/proto/mod.rs, src/proto/shim/mod.rs, uefi-test-runner/src/proto/mod.rs, uefi-test-runner/src/proto/shim.rs
This protocol is not part of the UEFI specification, but is installed
by the [Shim bootloader](https://github.com/rhboot/shim) which is
commonly used by Linux distributions to support UEFI Secure Boot. Shim
is built with an embedded certificate that is used to validate another
EFI application before running it. That application may itself be a
bootloader that needs to validate another EFI application before
running it, and the shim lock protocol exists to support that.
=> Add shim lock protocol

uefi-services/Cargo.toml, uefi-services/src/lib.rs
Makes the `qemu-exit` dependency of the `uefi-services` crate depend on the `qemu` optional feature.
Fixes #228
=> Make the `qemu-exit` dependency optional

src/proto/media/block.rs
The media field should be a pointer to `BlockIOMedia`.
=> Fix type of the media field in the BlockIO protocol

src/proto/device_path.rs
From the "Generic Device Path Structures" section of the UEFI spec,
"[...] all nodes are byte-packed data structures that may appear on
any byte boundary. All code references to device path notes must
assume all fields are unaligned".
Add `#[repr(packed(1)]` to both structures. `packed(1)` is the same as
`packed`, but I think it's a little clearer to specify the required
alignment explicitly here.
=> Make DevicePath and AcpiDevicePath unaligned

src/data_types/chars.rs
This is needed to call `.unwrap()` on a `Result<_, CharConversionError>`.
For example: `Char16::try_from(c).unwrap()`.
=> Derive Debug for CharConversionError

src/table/boot.rs, uefi-test-runner/src/boot/memory.rs
In boot.rs we see there is an unsafe function named memset. This function has a signature different than memset(3), but has a name different than that in the edk2 sources. This is confusing and will lead to bugs in a very unsafe function when people mix up the order of the value and the size.
We should name the function set_mem and give it the signature from EFI_SET_MEM.
uefi-rs/src/table/boot.rs
Line 529 in 948464c
```
pub unsafe fn memset(&self, buffer: *mut u8, size: usize, value: u8) { 
```
See #232
=> Rename boot services' `memset` to `set_mem`

src/proto/loaded_image.rs, src/table/boot.rs
This adds code to load, unload, and start images, as well as set the
command-line of the image.
I didn't add anything to uefi-test-runner for this since to really
test it you need a valid EFI binary to load, but I tested it in a
separate project and verified it can load a Linux kernel that has the
EFI stub built in.
A couple things are left unimplemented here:
- LoadImage supports loading from either a DevicePath or from a
buffer. Only the latter method is implemented here.
- StartImage can provide exit data if the called image exits. I
haven't implemented passing that back to the caller for now since I
don't have a use case to test it against.
=> Implement image loading/starting

src/proto/shim/mod.rs, src/result/status.rs
See the systemd-boot declaration:
https://github.com/systemd/systemd/blob/5efbd0bf897a990ebe43d7dc69141d87c404ac9a/src/boot/efi/shim.c#L23-L31
This is because the shim is built with sysv ABI funcs by defualt.
This PR also adds bindings to the hashing functionality of the shim. For more information see:
- [The shim's protocol declaration](https://github.com/rhboot/shim/blob/20e4d9486fcae54ee44d2323ae342ffe68c920e6/shim.h#L194-L223)
- [The shim's context declaration](https://github.com/rhboot/shim/blob/20e4d9486fcae54ee44d2323ae342ffe68c920e6/include/peimage.h#L781)
Signed-off-by: Joe Richey <joerichey@google.com>
=> shim: ShimLock protocol uses "sysv64" function ABI

BUILDING.md, src/table/system.rs, uefi-services/src/lib.rs, uefi-test-runner/src/main.rs, uefi-test-runner/src/proto/console/mod.rs, uefi-test-runner/src/proto/mod.rs
Updates the system table's `stdin`/`stdout`/`stderr` methods require a `&mut` reference.
Fixes #239
=> Make using the `stdio` handles require a mutable ref

.github/workflows/rust.yml, src/proto/shim/mod.rs, uefi-test-runner/aarch64-unknown-uefi.json, uefi-test-runner/src/proto/mod.rs
Fixes #242 by choosing the right calling convention for Shim functions based on the target architecture.
Also updates the CI script to build the code for AArch64 as well, to prevent future regressions.
=> Fix AArch64 build

src/table/runtime.rs, uefi-test-runner/src/main.rs, uefi-test-runner/src/runtime/mod.rs, uefi-test-runner/src/runtime/vars.rs
Added three methods to `RuntimeServices`: `get_variable_size`, `get_variable`,
and `set_variable`.
Also added a test for these methods. There's a TODO comment about testing
runtime services after existing boot services, but I'm not sure how best to
structure that change, so for now I've added the new test prior to exiting
boot services.
=> Add support for getting/setting variables

src/proto/device_path.rs
Although the spec defines the length field as `UINT8 Length[2]`, it is always
treated as a `u16` and is more convenient to access that way.
=> device path: change the length type to u16

src/proto/device_path.rs
The constants are grouped and prefixed by their associated `DeviceType`.
Also changed `DeviceSubType` to not use `newtype_enum` because many of the
values have multiple names, so the `newtype_enum` implementation of `Debug`
doesn't work properly and generates warnings.
=> device path: add constants for all subtypes

src/logger.rs
I enhanced the logger to include filename and line. What do you think?
=> Better logger that includes filename and line

src/table/boot.rs, uefi-test-runner/src/main.rs, uefi-test-runner/src/proto/mod.rs
This function gets a list of all the protocol GUIDs that are installed on a
handle.
=> Implement `BootServices::protocols_per_handle`

src/proto/console/gop.rs
Given a 4x4 16-pixel image, this would previously check if 4+4*4 (20) <= 16.
=> Fix `BltRegion::Full` bounds check

src/table/runtime.rs
Hi! The current `fmt::Debug` impl for the `Time` struct didn't included leading zeroes, which is a bit odd. I optimized the implementation. `fmt::Display` was completely missing,
Current debug-format looks like: `Time: 2021-07-13 21:14:46.000000000, Timezone=unspecified, Daylight=(empty)`
and current display-format looks like this: `Time: 2021-07-14 07:00:37.000 (local)` (or `Time: 2021-07-14 07:00:37.000 UTC+2`) 
I tested it inside my QEMU setup.
Furthermore I changed the debug formatting for the time zone and the daylight fields of a Time struct a bit. The current approach was strange, because for example, users got a weird number for the Timezone without explanation, that this number is the time zone.
What do you think?
=> Better `fmt::Debug` for `Time` struct + `fmt::Display`

BUILDING.md, src/lib.rs, uefi-macros/src/lib.rs
Currently procedural macros do not work outside of `uefi` crate, because they are referencing crate-local items (Guid, Protocol etc.) and when invoked from a crate other than 'uefi' those items cannot be found (well because the other crate does not have them).
This is a known (as I learned) procedural macro issue and the latest best [workaround](https://github.com/rust-lang/rust/issues/54647) is what I implemented here - allow 'uefi' to reference itself by `::uefi` and then use `::uefi` in those macros.
As an additional bonus (I can revert that if you have objections but it's neat and does not break anything) I made the 'entry' macro always make the exported entry function have the name 'efi_main', which is required by the rust efi target I think.
Anyway, with that change, users can name …
=> Fix procedural macros

src/proto/device_path.rs
All device paths start with the same header containing type, subtype, and
length. Move these fields into a struct and use the struct in the two existing
device path types, `DevicePath` and `AcpiDevicePath`.
This also fixes the missing `length` field in `AcpiDevicePath` since it uses
the header type now.
The `header` fields in `DevicePath` and `AcpiDevicePath` are not public
because it's generally unsafe to modify the values since they determine how
the rest of the data in the node is interpreted.
=> device path: add header struct

src/data_types/guid.rs, src/data_types/mod.rs, src/data_types/strs.rs, src/table/runtime.rs, uefi-test-runner/src/runtime/vars.rs
This method uses the `get_next_variable_name` function of `RuntimeServices` to get each variable name and vendor GUID.
=> Add method to get variable names

src/proto/device_path.rs, uefi-test-runner/src/proto/device_path.rs, uefi-test-runner/src/proto/mod.rs
Device paths are variable length structures packed into an array, so usually
you have a pointer to the head of the array and advance through the elements by
adding the length from the header to the pointer. The new `DevicePath::iter`
method provides a more convenient way of doing this.
=> device path: add iter method and test

src/proto/console/pointer/mod.rs, src/table/boot.rs
This pull request is a follow-up of Pull Requests #255 and #258.
=> Add `BootServices::exit` method; Make `PointerMode`'s fields public for checking against support of a pointer device

src/proto/device_path.rs
This is implemented as a byte-by-byte comparison of the device path
nodes covering the entire payload of the device path (using the
`length` field in the header), so it's not the same as just comparing
the fields of the `DevicePath` struct.
=> device path: implement PartialEq+Eq for DevicePath

src/data_types/mod.rs, src/proto/console/text/output.rs, src/table/boot.rs, src/table/header.rs, src/table/runtime.rs, src/table/system.rs
Hey! This PR makes it possible to debug-format the UEFI system table. I'd love to see this functionality upstream. What do you think?
Example output (I can proof that it works in my QEMU setup)
```
UefiSystemTable {
header: Header {
signature: 6076298535811760713,
revision: 2.7.0,
size: 120,
crc: 3701267086,
_reserved: 0,
},
fw_vendor: "EDK II",
fw_revision: 1.0.0,
stdin_handle: Handle(
0x000000000701a818,
),
stdin: 0x0000000006de5b90,
stdout_handle: Handle(
0x0000000007019f18,
),
stdout: 0x0000000006de5fd0,
stderr_handle: Handle(
0x0000000007018018,
),
stderr: 0x0000000006de5a30,
runtime: RuntimeServices {
header: Header {
signature: 6220110259551098194,
revision: 2.7.0,
size: 136,
crc: 2242073619,
_reserved: 0,
},
get_time: 0x0000000007abd56b,
set_time: 0x0000000007abda01, …
```
=> system table can get debug-formatted (including boot and runtime services)

src/proto/loaded_image.rs
This allows overriding the data in `LoadedImage`. It's useful in the
following scenario:
1. Secure boot is enabled, so images loaded with `LoadImage` must be
signed with an appropriate key known to the firmware.
2. The bootloader has its own key embedded, and uses that key to
verify the next stage. This key is not known to the firmware, so
the next stage's image can't be loaded with `LoadImage`.
3. Since image handles are created by `LoadImage`, which we can't
call, we have to make use of an existing image handle -- the one
passed into the bootloader's entry function. By modifying that
image handle (after appropriately verifying the signature of the
new data of course), we can repurpose the image handle for the next
stage.
See [shim] for an example of this scenario in action.
[shim]: …
=> loaded image: add set_image function

src/data_types/strs.rs, uefi-test-runner/Cargo.toml, uefi-test-runner/src/main.rs
In my experience, the current CStr16 abstraction is really a pain when you want to use the strings in regular Rust code. As I'm developing my own OS/kernel, I'd love to have a nice way to transform these to regular Rust strings.
=> better CStr16 to String and str

.github/workflows/rust.yml, src/data_types/enums.rs, src/data_types/guid.rs, src/proto/mod.rs
The first commit fixes up various compilation issues in existing doctests. The second commit adds a `cargo test` step to the github actions that runs on the x86_64-unknown-linux-gnu target instead of a UEFI target so that the doctests don't bitrot. (Regular `#[test]` unit tests could potentially be added later too for things that don't need to run on a UEFI target, e.g. for code under `src/data_types`.)
Running the tests on the host can be done like this:
CARGO_PROFILE_DEV_PANIC=unwind \
cargo test -Zbuild-std=std --target x86_64-unknown-linux-gnu
Changing panic to unwind avoids https://github.com/rust-lang/wg-cargo-std-aware/issues/56. (The comments there suggest that `-Zbuild-std=panic_abort` would work instead of changing the panic type, but I kept getting the duplicate lang item …
=> Fix docstring tests and test them in the CI

.github/workflows/rust.yml, BUILDING.md, Cargo.toml, template/.cargo/config, template/Cargo.toml, template/src/main.rs
This adds a new crate under `template/` that contains a very minimal UEFI
application. The instructions in `BUILDING.md` have been updated to reference
the template instead of using inline code snippets.
I think this makes it a bit easier to get started with a new app -- you can
just copy the whole directory and make a couple changes in `Cargo.toml` to get
started. `uefi-test-runner` is similar, but has a lot more stuff in it so it's
harder to see exactly what is needed. Moving the code out of markdown also
makes it easier to test in github actions to ensure the code stays valid.
=> Add a minimal UEFI application template

src/proto/console/gop.rs
This Pull Request makes the method `query_mode` of `GraphicsOutput` public, likely due to a typo as the documentation is there.
=> make `GraphicsOutput.query_mode(...)` public

.github/workflows/rust.yml, src/data_types/strs.rs
- Fix a doc link that rustdoc doesn't understand
- Add a `cargo doc` step to the CI to catch things like that automatically
- Also changed the clippy lint to treat warnings as errors
- Enable more of the crate's features in tests
=> Fix doc link and make CI lints stricter

src/data_types/mod.rs, src/data_types/owned_strs.rs, src/lib.rs, uefi-test-runner/src/runtime/vars.rs
For now the API is quite minimal; mostly it just makes interop between
regular Rust strings and EFI strings easier. You can convert from a
`&str` to a `CString16`, and since it derefs to `&CStr16` you can call
the methods exposed by that type as well.
This type is gated by the `exts` feature since it requires allocation.
=> Add CString16

src/data_types/guid.rs, src/proto/media/partition.rs, src/table/cfg.rs, src/table/runtime.rs, uefi-macros/src/lib.rs, uefi-test-runner/src/runtime/vars.rs
=> Enhance `Guid::from_values` and `Guid::fmt`

.github/workflows/rust.yml, Cargo.toml, src/table/boot.rs, uefi-test-runner/src/boot/misc.rs
The default panic mechanism was changed to `abort` in 58a623a70b50e2a3a1da61926b531a864b787ce8, to avoid issues with event callbacks. However, as far as I can tell, since https://github.com/rust-lang/rust/pull/76570, unwinding is automatically disabled for `extern "efiapi"` functions, so there shouldn't be any issue with using `panic = unwind` by default.
I've implemented the `check_event` method and added a new test for creating a custom event, and after playing around a bit, there seemed to be no issues with panics inside the notify function.
=> Handle panics by unwinding the stack and implement `check_event` method

uefi-macros/src/lib.rs
I was actually working on another thing (that I may or may not PR as it's more of a proof of concept) and in the process I've added a few macro checks with nice spans so it actually shows where stuff is wrong (guid one is especially cool) - and so here is a separate small PR with those things.
`const _` bit was stabilized in [1.37](https://blog.rust-lang.org/2019/08/15/Rust-1.37.0.html#using-unnamed-const-items-for-macros) and is an idiomatic way of doing what was done before with ugly unhygienic static, and it's also done in a way that reuses existing ident token instead of creating a new one (as I did in my previous PR, basically fixing my own oversight) so the error highlight is also slightly better. And also I use `export_name` instead of `no_mangle` so that the function name still …
=> Improve macro errors

.github/workflows/rust.yml, uefi-test-runner/README.md, uefi-test-runner/build.py
Fixes https://github.com/rust-osdev/uefi-rs/issues/281
=> Add a test command to build.py and also use it in the CI

CONTRIBUTING.md
The proc macros now work correctly outside of the uefi crate thanks to
the improvements made in https://github.com/rust-osdev/uefi-rs/pull/260.
=> contributing: remove text about protocol macro limitations

uefi-macros/Cargo.toml, uefi-macros/tests/cargo_wrapper, uefi-macros/tests/compilation.rs, uefi-macros/tests/ui/entry.rs, uefi-macros/tests/ui/entry.stderr, uefi-macros/tests/ui/guid.rs, uefi-macros/tests/ui/guid.stderr
Use the [trybuild](https://github.com/dtolnay/trybuild) crate to test
the `unsafe_guid` and `entry` macros. The compilation output is compared
against expected output to check the various error cases in the macros,
which allows detailed tests covering things like the specific error
messages and the associated spans.
=> macros: add compilation tests

src/alloc.rs
This reverts commit cba22ccac0503b5d15f8f1544ea1899232d98caa.
Fixes #303
=> Revert "Temporarily disable a false-positive clippy lint"

src/table/boot.rs
The device path pointer does not need to be exclusive here, and also lift the mutable pointer to said device path pointer out of the function - this argument in `LocateDevicePath` is `IN OUT`, and is used to return remaining part of the device path:
> On input, a pointer to a pointer to the device path. On output, the 
device path pointer is modified to point to the remaining part of the 
device path—that is, when the function finds the closest handle, it 
splits the device path into two parts, stripping off the front part, and 
returning the remaining portion. EFI_DEVICE_PATH_PROTOCOL is 
defined in Section 10.2.
=> Fix locate_device_path impl argument pointer

src/data_types/mod.rs, src/lib.rs, src/table/boot.rs
While I rewrote the OUT pointers in UEFI methods to use `MaybeUninit` (which actually looks very clean and logical) to avoid ever having null handles, the reason for the repr change is so that whenever an UEFI method accepts a handle - by the docs it can be optional or not, and this can be expressed by just having either `Handle` or `Option<Handle>` in the fn-pointer args, which is very clean and removes the need for null handles (`Handle::unitialized()`) to ever exist on Rust side.
I spent a night debugging my impls of (dis)connect_controller (that I will make a PR for too at some point) only to realize that I automatically assumed that whatever I did in the PR was already there ¯\_(ツ)_/¯
=> Change Handle representation to be non-nullable so that Option<Handle> is FFI-safe

src/lib.rs, src/table/boot.rs
Only now, after #309 was merged, I learned that there is a cleaner ~~unstable~~ way of using a vector as an unitialized buffer and then marking it as initialized without any pointer reinterpretations.
Here is a change that implements that - check it out.
=> Improve Handle buffer handling code

src/data_types/mod.rs, src/data_types/strs.rs, uefi-test-runner/src/runtime/vars.rs
This provides an easy way to convert from a UTF-8 str to a CStr16
without requiring allocation. You just have to provide a backing buffer
large enough to store the converted characters.
Also converted the runtime vars test to use this method instead of
`CString16`, since if the runtime tests are ever moved to run after
exiting boot services, they won't be able to use allocation.
=> Add `CStr16::from_str_with_buf`

BUILDING.md, CONTRIBUTING.md, README.md, template/README.md, uefi-test-runner/README.md
Coming back to the project after not working on it for a while made me realize that the docs have increased in size as the project grew, yet it's not extremely clear where you need to look to find what. This PR is an attempt to clean up and reorganize them, in order to make them easier to read.
Overview and motivation of the main changes:
- The `README` has been streamlined to contain only an overview of what `uefi-rs` does and links to the relevant documentation files.
I've also removed the link to gil0mendes' blog post, since at this point it's a bit outdated and no longer matches the current workflow.
- The `BUILDING.md` file has been fleshed out a bit, and I've moved what wasn't common to building and running general UEFI apps to the other files.
- The `template` directory now has a …
=> Update and reorganize documentation

uefi-test-runner/README.md, uefi-test-runner/build.py
I've recently had the need to build and run the project on Windows using the Windows Subsystem for Linux, and I didn't encounter many blockers. The only problem is that QEMU would try to use KVM, which is currently broken in WSL. This PR adds a new flag to the test runner to allow selectively disabling hardware acceleration.
With this change,  `./build.py run --disable-kvm --ci --headless` runs all the tests successfully under WSL2 on Windows 10. Unfortunately, trying to run the tests excluded from CI results in failures, suggesting that QEMU on WSL has some similar bugs.
=> Add flag to `build.py` for disabling KVM

Cargo.toml
This change should cause docs.rs to show documentation for things hidden
behind feature flags, notably the `exts` feature.
See https://docs.rs/about/metadata for details.
=> Enable all `uefi-rs` features on `docs.rs`

src/table/system.rs, uefi-services/src/lib.rs
The logger and allocator provided by the uefi crate can't be used after
calling exit_boot_services. Add a paragraph to `exit_boot_services` to
document that. Add a similar paragraph to the `uefi-services` crate
documentation.
=> Add documentation about logging/allocating after exiting boot services

.github/workflows/rust.yml, uefi-test-runner/build.py, uefi-test-runner/src/runtime/vars.rs
The CI only lints the uefi package but with all features enabled, while build.py lints all packages but with no features enabled. Change build.py to lint all packages with a subset of features enabled (all the uefi features that enable more code), and change the CI to just run the build.py clippy command so that the two stay in sync.
Also fixed a few clippy lints in the test runner.
=> Improve clippy linting in `build.py` and CI

src/table/boot.rs, uefi-test-runner/src/main.rs, uefi-test-runner/src/proto/console/gop.rs, uefi-test-runner/src/proto/console/mod.rs, uefi-test-runner/src/proto/debug.rs, uefi-test-runner/src/proto/device_path.rs, uefi-test-runner/src/proto/media/mod.rs, uefi-test-runner/src/proto/mod.rs
First commit implements open_protocol, test_protocol, and close_protocol. Second commit uses it in the test code for screenshots, which fixes occasional unexpected timeout errors.
=> Implement `open_protocol`, use it to fix flaky screenshot test

uefi-test-runner/build.py
This was failing because the manifest path is passed in as a path object
rather than a string.
=> `build.py`: fix `clippy --verbose`

uefi-test-runner/build.py
This will make the CI fail if any regular compiler warnings occur.
=> `build.py`: deny warnings when running clippy

CONTRIBUTING.md, PUBLISHING.md
I've realized that the process for publishing new versions of the crates in this repository has grown to be (a bit) complicated, and couldn't find an appropriate reference online for how to best manage the publishing of new versions of multi-crate projects.
This PR adds a new `PUBLISHING.md` document, describing some practices I've discovered over the years for handling new releases of the uefi-rs crates.
These are by no means final, but documenting the steps should make it possible to review and improve them over time.
=> Document how to publish new versions of the crates

Cargo.toml, uefi-services/src/lib.rs, uefi-test-runner/src/main.rs
`qemu-exit` crate also must be updated. I sent a PR: https://github.com/andre-richter/qemu-exit/pull/20
=> fix: build error on the latest nightly

Cargo.toml, uefi-services/Cargo.toml, uefi-test-runner/Cargo.toml
Fixes: https://github.com/rust-osdev/uefi-rs/issues/329
=> chore(deps): update the version of `qemu-exit`

src/data_types/mod.rs, src/result/completion.rs, src/table/system.rs
Fixes CI getting broken by a new clippy lint.
Currently failing due to https://github.com/rust-lang/rust-clippy/issues/8140
=> Add missing `#[must_use]` marker attributes

.github/workflows/rust.yml, CONTRIBUTING.md, README.md, build.py, uefi-test-runner/README.md
build.py isn't really specific to uefi-test-runner; it has commands for
generating docs, running clippy, and running tests. Move it to the root
of the repo to reflect its broader role.
Updated various docs that reference build.py.
=> Move build.py to the root of the repo

build.py, uefi-test-runner/src/main.rs
OVMF sets up the stdout handle such that writes go to all serial devices
(as well as the visual console when not running headless). This is
convenient since the logger writes to stdout, so connecting a serial
device to QEMU's stdout writes logs from the test runner to the host.
However, once a serial device is opened in exclusive mode it is
disconnected from stdout. Since the test runner needs to open a serial
device in exclusive mode, a single serial device isn't sufficient --
once the device is opened in exclusive mode it will stop receiving logs.
So, open two serial devices for the QEMU test. The first one is
connected to the host's stdout, and serves just to transport logs. The
second one is connected to a pipe, and used to receive the SCREENSHOT
command and send the response. That …
=> Fix logs cut off after screenshot test

uefi-services/Cargo.toml
https://github.com/rust-osdev/uefi-rs/issues/340
=> (cargo-release) uefi-services version 0.11.0

src/lib.rs
Fixes clippy failures on latest `rustc` versions.
=> Remove `vec_spare_capacity` nightly feature

.github/workflows/rust.yml, xtask/src/main.rs, xtask/src/opt.rs
Add an xtask action and corresponding CI job to test that the template
app builds against the released versions of the uefi-rs libraries. Since
nightly compiler changes can break the released versions at any time,
it's nice to have an automatic alert.
Fixes https://github.com/rust-osdev/uefi-rs/issues/343
=> ci/xtask: add test-latest-release

Cargo.toml, README.md
The badges section of Cargo.toml is mostly deprecated, and crates.io
doesn't display badges anymore. According to the [manifest
reference](https://doc.rust-lang.org/cargo/reference/manifest.html#the-badges-section),
badges should be placed in the readme instead.
Added maintenance badges from
https://isitmaintained.com/project/rust-osdev/uefi-rs, and dropped the
Travis CI badge entirely.
=> Move badges from `Cargo.toml` to `README.md`

src/data_types/mod.rs, src/table/system.rs
Enables to create Handle and System Table from raw pointers.
```rust
let uefi_system_table_addr = mb2_boot_info.efi_sdt_64_tag().unwrap().sdt_address();
let uefi_image_handle_addr = mb2_boot_info.efi_64_ih().unwrap().image_handle();
// nice "from"-creation
let mut uefi_system_table = SystemTable::<Boot>::from(uefi_system_table_addr);
let uefi_image_handle = Handle::from(uefi_image_handle_addr);
// ...
let rt_table = uefi_system_table.exit_boot_services(uefi_image_handle, mmap);
```
=> System Table and Handle: From-implementation to create objects from raw pointers

src/result/completion.rs
This reverts commit bc21bb9cd63cf25f8d3c216fa3d935e980dde989.
Fixes https://github.com/rust-osdev/uefi-rs/issues/333
=> Revert "Temporarily allow clippy::return_self_not_must_use"

.github/workflows/rust.yml
This extends the aarch64 job to have the same level of coverage as the
x86_64 job.
https://github.com/rust-osdev/uefi-rs/issues/259
=> ci: run VM tests on aarch64

template/README.md
Clicking from the file alone is correct, but there is a problem if it is read automatically by github at the folder level.
Maybe it would be better to provide the full path?
=> DOC: Fixed link

.github/workflows/rust.yml, xtask/src/qemu.rs
This was accidentally dropped when porting build.py to Rust. On AArch64,
check that qemu exits 0, and on x86_64, expect an exit code of 3.
=> xtask: fix status check at end of VM test

src/data_types/owned_strs.rs, src/data_types/strs.rs
Since `CStr16` implements `Display`, the [`ToString`](https://doc.rust-lang.org/alloc/string/trait.ToString.html) trait is automatically implemented. That provides `to_string` as long as `alloc` is enabled, so `as_string` isn't needed.
https://github.com/rust-osdev/uefi-rs/issues/73
=> strs: remove CStr16::as_string

template/README.md
Since the file structure links got moved out of the top-level readme
into the template's readme, showing the `template/` prefix isn't
needed. (The targets of the path links were already fixed up in
https://github.com/rust-osdev/uefi-rs/pull/356, this cleans up the text
to match.)
=> template: clean up paths in readme

src/data_types/owned_strs.rs, src/proto/media/file/mod.rs, uefi-test-runner/src/proto/media/mod.rs, xtask/src/qemu.rs
As suggested in https://github.com/rust-osdev/uefi-rs/issues/73, avoid an implicit `&str` -> `&CStr16` conversion in `File::open`, and just take a `&CStr16` directly.
Also added a test for opening and reading a file so we can see this code works as expected. And to make logging easier in the test, add a `Display` impl for `CString16`.
=> Remove implicit string conversion from File::open

xtask/src/main.rs
This avoids needing to manually override the default toolchain with
`rustup override`.
Also fix an out-of-date comment.
=> xtask: run tests with +nightly

src/proto/media/file/info.rs, src/table/runtime.rs
The bulk of this change is adding tests for `FileInfo`, `FileSystemInfo`, and `FileSystemVolumeLabel`.
In doing so I noticed that the `size` field in the header of the first two was calculated incorrectly in their `new` methods, so fixed that.
And some minor changes to implement Derive and PartialEq on additional types to make the tests easier to write.
(I have some more fixes to make in this area including removing the implicit string conversion, but that will be easier with the tests in place.)
=> Fix file info sizes and add tests

src/data_types/owned_strs.rs, src/data_types/strs.rs
Add support for `CStr16 == CStr16`, `&CStr16 == CString`, and `CString == &CStr16`.
=> data_types: add string equality impls

src/data_types/mod.rs
The docstring now mentions both standard methods of getting alignment
(align_of and align_of_val), and describes a specific case where these
are not sufficient.
=> data_types: expand Align trait docstring

src/data_types/strs.rs, src/proto/media/file/info.rs
The file info types are now constructed directly from a `&CStr16`
instead of internally converting from a `&str`. This also removes
`FileInfoCreationError::InvalidChar`, since that error is no longer
possible.
Also added `CStr16::as_slice_with_nul`.
https://github.com/rust-osdev/uefi-rs/issues/73
=> Remove more implicit string conversions

src/table/boot.rs
The old implementation contains a `protocols` slice with a lifetime `a`.
```rust
pub struct ProtocolsPerHandle<'a> {
boot_services: &'a BootServices,
protocols: &'a mut [&'a Guid],
}
```
But `protocols` slice does not live long enough for `'a`. It will be freed when the `ProtocolsPerHandle` struct is dropped.
From std doc, ( https://doc.rust-lang.org/nightly/core/slice/fn.from_raw_parts.html )
```rust
pub unsafe fn from_raw_parts<'a, T>(data: *const T, len: usize) -> &'a [T]
```
> The memory referenced by the returned slice must not be mutated for the duration of lifetime `'a`.
The current codebase does not use this internal property except the `protocols` getter method. So having an invalid lifetime does not immediately cause undefined behavior but it is safer to fix.
Since I'm not a …
=> Fix ProtocolsPerHandle internal slice property.

CHANGELOG.md, src/proto/loaded_image.rs, uefi-test-runner/src/proto/loaded_image.rs
The spec describes `LoadOptions` as "A pointer to the image’s binary
load options. See the OptionalData parameter in [section 3.1.3 Load
Options] of the Boot Manager chapter for information on the source of
the LoadOptions data." The `OptionalData` field is described as "The
remaining bytes in the load option descriptor are a binary data buffer
that is passed to the loaded image."
So there's no guarantee made about the contents of `LoadOptions`; it's
arbitrary binary data as far as the UEFI spec is concerned. So it's not
necessarily safe to treat the load_options as a `Char16` pointer, since
it might not be aligned and might not be null-terminated. That said, the
data is *usually* a null-terminated UCS-2 string. The UEFI Shell spec
specifies that command-line parameters are passed that …
=> loaded_image: make load options API safer

src/data_types/mod.rs, src/table/system.rs
The `Handle::from_ptr` and `SystemTable<View>::from_ptr` doctests use a
`0xdeadbeef` pointer, which of course is not valid. Change the tests to
compile but not actually run so that they don't trigger UB.
Noticed this when running the unit tests with Miri, which caught the
undefined behavior the in the SystemTable case.
=> Don't run doctests with invalid pointers

CHANGELOG.md, src/data_types/mod.rs, src/lib.rs, src/proto/media/file/info.rs, src/proto/media/file/mod.rs, uefi-test-runner/src/proto/media/mod.rs
This fixes a couple alignment bugs with the info types:
The `FileSystemInfo` was accidentally different from the intended C representation of the type due to extra alignment padding as described in https://github.com/rust-osdev/uefi-rs/issues/80. Fixing that required fairly invasive changes to the file info types, but I think everything is now aligned correctly and has no UB.
Additionally the storage size check didn't take trailing alignment padding into account, now it does.
One more alignment improvement: if the storage buffer is not aligned, an aligned sub-slice is used (if possible). With that fix in place it's possible run the tests under Miri for some added confidence in the correctness of all the unsafe code.
More details in the commit messages.
=> Fix alignment issues in file info types

.github/workflows/rust.yml, xtask/src/cargo.rs, xtask/src/main.rs, xtask/src/opt.rs
xtask: add option to override toolchain
xtask: add command for running unit tests under Miri
ci: add miri job
Fixes https://github.com/rust-osdev/uefi-rs/issues/379
=> Add miri action to xtask and CI

CHANGELOG.md, src/table/boot.rs
~I'll have to fix this if/when #309 gets merged :)~ done
If've tested this directly locally in my own project (getting the pointers with like `((bs as *const _ + 1) as *const usize - 14) as *const fn ptr`), have not figured out how to actually run/write the tests from this crate so I'll later add some tests here.
=> Implement the ConnectController/DisconnectController methods

CHANGELOG.md, src/table/boot.rs
This replaces `BootServices::load_image_from_buffer` with a single
method that can load from either a `[u8]` buffer or a file path via
`SimpleFileSystem`.
The source is modeled with the `LoadImageSource` enum. That helps make
it clear that the buffer input isn't needed when specifying a file path,
but the reverse isn't necessarily true since the file path can be added
as metadata when loading from a buffer. Additionally, the `boot_policy`
flag (called `from_boot_manager` in `LoadImageSource`) is only used when
loading from a file path.
=> Add BootServices::load_image

CHANGELOG.md
In the initial changelog layout I didn't think about the fact that the
three published packages are versioned independently (and we don't
necessarily release updates to all three at the same time), so it makes
sense to split them out into separate sections.
=> Add package sections to changelog

src/table/boot.rs, uefi-test-runner/src/boot/mod.rs
This is an implementation of https://github.com/rust-osdev/uefi-rs/issues/372.
I would like to ask something.
1. How should I use `*const` and `*mut` each? I couldn't get which should I use.
2. Should I remove `unsafe` keyword from `locate_handle_buffer` property? I believe I should not but it confuses me that some FFI function pointers ( such as `locate_protocol` ) do not mark self as `unsafe`.
3. How do I test this function?
Thanks! :)
=> implement BootServices::locate_handle_buffer function

CHANGELOG.md, src/proto/media/partition.rs
Change `GptPartitionEntry.attributes` from a plain `u64` to
a struct created with `bitflags!`.
=> Add GptPartitionAttributes bitflags

src/result/status.rs
Following the changes in https://github.com/rust-osdev/uefi-rs/issues/360, warning status were supposed to be treated as errors when converted to `Result`s. But instead they were incorrectly being converted to `Result::Ok`. Fix that, and add a new unit test for that case.
=> Fix status to Result conversions

CHANGELOG.md, src/proto/media/file/mod.rs, uefi-test-runner/src/proto/media/known_disk.rs, uefi-test-runner/src/proto/media/mod.rs, xtask/Cargo.toml, xtask/src/disk.rs, xtask/src/main.rs, xtask/src/qemu.rs
* Add `FileHandle::into_directory` and `FileHandle::into_regular_file`. These can be more convenient than `FileHandle::into_type` when you know what type of file you expect.
* Add code in xtask to build a disk image with a FAT partition, then run file system tests against that disk (when the test runner is built with the qemu feature). A disk image is used instead of QEMU's VVFAT option so that everything is fully controlled (can test exact FS info values) and isolated from the host.
This partially addresses https://github.com/rust-osdev/uefi-rs/issues/57. There are some more partition and file system tests that can be added later.
=> Add FileHandle convenience methods and new file system tests

README.md
It seems like these badges aren't getting dynamically updated the way they're supposed to.
=> Drop maintenance badges from README

src/alloc.rs, src/proto/console/gop.rs, src/proto/media/file/info.rs, src/result/status.rs, src/table/boot.rs, src/table/cfg.rs, uefi-macros/src/lib.rs
Various clippy lints have either been made smarter such that they no
longer trigger, or have been moved to the pedantic group which is
allowed by default.
=> Remove no-longer-needed allows for clippy lints

CHANGELOG.md, src/proto/media/file/info.rs, src/table/runtime.rs, uefi-test-runner/src/proto/media/known_disk.rs
* Add a `TimeParams` struct with public fields corresponding to all the
non-padding fields of `Time`, and change `Time::new` to take that as
input. That improves callsites of `Time::new` so that you can see what
the numeric values correspond to. See `known_disk.rs` for an example.
* Add `Time::invalid` for use with `File::set_info`. When setting file
info, a fully-zero-time indicates the attribute should not be
updated. I think ideally we'd have `Time` always represent a valid
value, and use `Option<Time>::None` to represent an invalid time
similar to what we do with `Handle`s, but I don't think Rust currently
allows us to indicate that all-zero-Time can be used for the
Option::None niche.
* Add `Time::is_invalid` to check that all fields are in the valid range.
* Update Time's docstring …
=> Improve Time struct

CHANGELOG.md, src/table/runtime.rs, uefi-test-runner/src/runtime/vars.rs
This provides information about variable storage space.
=> Add RuntimeServices::query_variable_info

.github/workflows/rust.yml, xtask/src/main.rs
The nightly rust compiler is currently unable to compile the version of
fatfs we are using in xtask. Rust bug:
https://github.com/rust-lang/rust/issues/95538. But we don't need to use
nightly to compile xtask. In the CI, install both stable and nightly
toolchains. The stable toolchain will be used by default, and xtask
already knows to insert `+nightly` when building uefi-rs, so there's no
need to set `override: true` for the nightly toolchain anymore.
Fixes https://github.com/rust-osdev/uefi-rs/issues/397
=> ci: use stable toolchain for compiling xtask

src/proto/device_path/mod.rs, src/proto/device_path/text.rs, uefi-test-runner/src/proto/device_path.rs
=> `DevicePathToText` and `DevicePathFromText` Protocol

CHANGELOG.md, src/data_types/mod.rs, src/data_types/owned_strs.rs, src/data_types/strs.rs, src/lib.rs, src/proto/device_path/mod.rs
This is a start for https://github.com/rust-osdev/uefi-rs/issues/401
It turned out to be a bit complicated to add useful support for file path media device path nodes, because the data is in a packed struct so the path string may be unaligned. (The spec says "All code references to device path nodes must assume all fields are unaligned".) That means we can't use `&CStr16` to provide access to the path, since reference in Rust must always be aligned.
To solve this I added a new type, `UnalignedCStr16`, with methods to convert to a `&CStr16` using a separate aligned buffer, or `CString16` if `exts` is enabled. There are other places in the UEFI spec with unaligned strings, so this type will be useful elsewhere in the future.
There's a fair amount of unsafe code here, but there are unit …
=> Add FilePathMediaDevicePath (and a bunch of supporting code)

CHANGELOG.md, src/proto/media/file/info.rs, src/proto/media/file/mod.rs, uefi-test-runner/src/proto/media/known_disk.rs
This is a partial fix for https://github.com/rust-osdev/uefi-rs/issues/406 in that it removes the only internal use of `exts::allocate_buffer`.
Also added a call to `get_boxed_info` in uefi-test-runner to check that it works there, and a new unit test so that Miri can validate all the unsafe code in `get_boxed_info`.
=> Fix undefined behavior in `File::get_boxed_info`

src/proto/media/file/info.rs
When running the file info tests under Miri with
`-Zmiri-tag-raw-pointers` enabled, `new_impl` triggered a Stacked
Borrows error. This occurred because after a mutable info pointer to the
raw `u8` buffer was created, we went back and created another mutable
pointer within the `u8` buffer to copy the name string into.
Fix by creating the name destination pointer from the info pointer
rather than the `u8` buffer pointer.
=> Fix potential UB in file info

src/alloc.rs, src/data_types/owned_strs.rs, src/data_types/strs.rs, src/lib.rs, src/proto/console/gop.rs, src/proto/device_path/mod.rs, src/proto/loaded_image.rs, src/proto/media/file/dir.rs, src/proto/media/file/info.rs, src/proto/media/file/mod.rs, src/table/boot.rs
`as` conversions are a bit of a blunt hammer, so where possible it's
nice to use a more restricted operation.
Lint is described here: https://rust-lang.github.io/rust-clippy/master/#ptr_as_ptr
It would be great to eventually get rid of most `as` conversions, but baby steps :)
=> Enable the clippy::ptr_as_ptr lint

src/proto/media/file/mod.rs
Very simple fix, we're making a `&mut Info` so need to pass in a mutable
pointer.
Partial fix for https://github.com/rust-osdev/uefi-rs/issues/414
=> Fix test_get_boxed_info with -Zmiri-tag-raw-pointers

src/proto/mod.rs, src/table/boot.rs
I periodically get confused about why we use `UnsafeCell` to return protocol references. I _think_ this new documentation accurately describes why, but definitely open to corrections if I have it wrong :)
I think it's possible that in the future we could improve the API to avoid needing `UnsafeCell`. For example, if we make `open_protocol` always use `Exclusive` access then we can provide stronger guarantees (and then maybe have some `unsafe` escape-hatch methods for opening protocols in other modes, with appropriate documentation around how to use them without triggering UB). For now though, I figure it would be helpful to document the current state of things.
=> Add documentation on why UnsafeCell is used for protocols

src/table/boot.rs, src/table/runtime.rs
The added links show which methods in `SystemTable` can be called to get
a reference of each struct.
rust-osdev#416
=> Add documentation links for `BootServices` and `RuntimeServices`.

uefi-test-runner/src/proto/mod.rs
The check for "at least one implementation of Simple Text Output" was
accidentally checking for at least two implementations.
=> Fix off-by-one test error

src/table/boot.rs
This buffer was accidentally being converted from &mut -> *const -> *mut.
=> Fix an accidental const conversion

CHANGELOG.md, src/proto/device_path/mod.rs, src/proto/device_path/text.rs, src/proto/loaded_image.rs, src/proto/mod.rs, src/table/boot.rs, uefi-test-runner/src/proto/device_path.rs, xtask/src/cargo.rs
This is an update to the device path API with two goals:
* Clearly define the separation between device paths, device path
instances, and device path nodes by using different types.
* Make tests pass under Miri with `-Zmiri-tag-raw-pointers` enabled
In the UEFI spec, the `EFI_DEVICE_PATH_PROTOCOL` struct is used to
represent both full paths and individual nodes. Prior to this commit,
`DevicePath` was used the same way. This didn't make for the clearest
API though, since the distinction between paths and nodes mainly existed
in the documentation rather than the type system. To solve this, there
are now three main types: `DevicePath`, `DevicePathInstance`, and
`DevicePathNode`.
In addition, since `DevicePath` was only four bytes in size (i.e. the
size of the node header), Miri was unhappy …
=> Improve device path API

template/README.md
This PR adds a link to the `bootloader` crate in our template's README file, to proactively answer questions such as #424.
=> Add link to `bootloader` crate in template README

src/proto/console/text/output.rs, src/proto/media/fs.rs, src/table/boot.rs, src/table/runtime.rs
Documentation links have been added to the following structs:
* `SimpleFileSystem`
* `Output`
Documentation links have been updated in the following structs:
* `BootServices`
* `RuntimeServices`
Adds documentation for https://github.com/rust-osdev/uefi-rs/issues/416
=> Add documentation links

src/logger.rs
=> Remove unused lifetime from `Logger` impl block

src/proto/mod.rs, src/proto/network/mod.rs, src/proto/network/pxe.rs, uefi-test-runner/src/proto/mod.rs, uefi-test-runner/src/proto/network.rs, uefi-test-runner/tftp/example-file.txt, xtask/src/main.rs, xtask/src/net.rs, xtask/src/qemu.rs
This pr adds the PXE Base Code protocol.
I only need `BaseCode::tftp_get_file_size` and `BaseCode::tftp_read_file`, but felt weird about only adding a small part of the protocol, so added the other functions as well.
I was able to test `BaseCode::tftp_get_file_size` and `BaseCode::tftp_read_file` on real hardware.
This pr slightly overlaps with #306: Both prs add structures for `EFI_MAC_ADDRESS` and `EFI_IP_ADDRESS`.
=> Add PXE Base Code protocol

CHANGELOG.md, src/data_types/owned_strs.rs, src/data_types/strs.rs, src/prelude.rs, uefi-macros/src/lib.rs, uefi-test-runner/src/proto/media/known_disk.rs, uefi-test-runner/src/runtime/vars.rs
Fairly simple, just got annoyed while tinkering with a personal project and thought it might be nice to contribute something to help. Both macros take a string literal and convert it to the respective CStr literal.
=> Create macros for making `CStr16` and `CStr8` literals

uefi-services/src/lib.rs
Resolves #428 
By changing `log::set_max_level(log::LevelFilter::Info);` to `log::set_max_level(log::STATIC_MAX_LEVEL);`, the max log level can be set by specifying features.
For example, to use info for release and trace for debugging, set `features = ["release_max_level_info", "max_level_trace"]`.
Tested this to work, thought I could just remove that line, but it seems you need to explicitly set it to STATIC_MAX_LEVEL, which is set depending on the features and whether it is a release build.
=> Change logger max level to be set by feature

src/proto/console/serial.rs
This should make it easier to log to the serial output, since otherwise user code would have to construct a newtype to be able to log to it.
=> Implement `core::fmt::Write` for `Serial`

src/table/header.rs
The `Header` `Debug` implementation was accidentally printing the `size`
field for the `signature`. Rather than just fix that field, switch the
whole thing back to using `derive(Debug)`. This adds in the `_reserved`
field, which probably doesn't matter much either way but might as well
show the whole struct when debug printing.
=> Switch back to automatic Debug derive for Header struct

.github/workflows/rust.yml, xtask/Cargo.toml, xtask/src/disk.rs, xtask/src/main.rs, xtask/src/net.rs, xtask/src/qemu.rs
As reported in https://github.com/rust-osdev/uefi-rs/pull/433, the qemu code makes use of some APIs from the `nix` crate, which causes compilation to fail on Windows (native, not WSL). The qemu code can't be easily made to work on Windows, but the rest of xtask should still work fine building, running clippy, etc. Fix by adding `#![cfg(unix)]` to the `qemu` module, as well as the `disk` and `net` modules that are only used by the qemu code. Also changed the `run_vm_tests` action to panic on non-Unix targets.
Also add Windows compilation to CI. The new job builds the UEFI packages on a Windows runner instead of Ubuntu. This is a somewhat minimal test (just builds for a single target, doesn't run tests or clippy), but should be enough to ensure that development on Windows outside of WSL is …
=> Fix compilation of the xtask package under Windows and add to CI

CHANGELOG.md, src/table/boot.rs, src/table/revision.rs, src/table/runtime.rs
The create_event_ex function (in boot services) and query_variable_info (in runtime services) were added to their respective tables in UEFI 2.0. In earlier versions these functions can't be called, so check the table revision before using these function pointers.
=> Check table version before calling UEFI 2.0+ functions

src/table/boot.rs, uefi-test-runner/src/main.rs, uefi-test-runner/src/proto/debug.rs, uefi-test-runner/src/proto/device_path.rs, uefi-test-runner/src/proto/loaded_image.rs, uefi-test-runner/src/proto/media/known_disk.rs, uefi-test-runner/src/proto/media/mod.rs, uefi-test-runner/src/proto/network.rs, uefi-test-runner/src/proto/rng.rs
Since `ScopedProtocol`'s only use is to be dereferenced, it makes sense to add a `Deref` impl so users don't have to do it manually. This also improves safety, since with this change it's harder to accidentally keep a reference to a protocol alive after exiting boot services.
=> Implement `Deref` and `DerefMut` for `ScopedProtocol`

CHANGELOG.md
Realized we didn't include one in #434.
=> Add changelog entry for `ScopedProtocol` changes

xtask/Cargo.toml
This is a minimal fix to get the CI passing again.
See https://github.com/clap-rs/clap/issues/3822 for more details.
=> xtask: Pin to clap 3.1 to avoid deprecation errors

xtask/Cargo.toml, xtask/src/opt.rs
Similar in scope to 57e61fb5d074294b1856c0f59852b491b2f5faa1, but attempts to cleanly update to clap 3.2 and fix the deprecations. The changes are based on the example set in https://github.com/EmbarkStudios/cargo-deny/pull/431.
=> Fix errors due to deprecations in the `clap` API

src/proto/rng.rs
When passing in a specific algorithm type to the get_rng function, a
pointer to the `Option`-wrapped value was incorrectly being passed
in. The pointer should be to the `RngAlgorithmType` inside the `Option`
instead.
Fixes https://github.com/rust-osdev/uefi-rs/issues/446
=> Fix incorrect pointer cast in get_rng

CHANGELOG.md, src/result/error.rs, src/result/status.rs
The ucs2 crate is still used for `Output`'s `fmt::Write` impl, but that returns a `fmt::Result` so it doesn't need `uefi::Status` or `uefi::Error` conversions.
=> Remove unused From<ucs2::Error> impls

uefi-services/src/lib.rs
This doesn't seem to be needed anymore. Tested by inserting an intentional panic into the test runner and verified it successfully panics.
=> Remove eh_personality lang item

uefi-services/src/lib.rs
The `PanicInfo` type implements `Display`, so it can be printed out in a
standard format without manually accessing the location and message data.
This changes the format of the panic output a bit, and now matches the
"normal" panic output of an std Rust target.
Old output:
```
[ERROR]: uefi-services/src/lib.rs@144: Panic in uefi-test-runner/src/main.rs at (44, 5):
[ERROR]: uefi-services/src/lib.rs@151: test panic
```
New output:
```
[ERROR]: uefi-services/src/lib.rs@141: panicked at 'test panic', uefi-test-runner/src/main.rs:44:5
```
This also allows the `panic_info_message` unstable feature to be removed.
=> Simplify uefi-services panic handler

CHANGELOG.md, src/proto/mod.rs, src/proto/security/memory_protection.rs, src/proto/security/mod.rs
This corresponds to the `EFI_MEMORY_ATTRIBUTE_PROTOCOL` proposal:
https://bugzilla.tianocore.org/show_bug.cgi?id=3519
The protocol is part of a push to add better memory protection to UEFI:
https://github.com/MicrosoftDocs/windows-driver-docs/blob/abb7dfa01467a300eefe589a4a8f9353199c0ade/windows-driver-docs-pr/bringup/uefi-ca-memory-mitigation-requirements.md
This is not yet part of a released UEFI Specification, but support for
using the protocol has already been added to shim and Fedora's fork of grub
* https://github.com/rhboot/shim/pull/459/commits/825d99361b4aaa16144392dc6cea43e24c8472ae
* https://github.com/rhboot/grub2/commit/aa3c4f62715c81de280de8403d0de1ff52a7440c
By our usual naming conventions, `EFI_MEMORY_ATTRIBUTE_PROTOCOL` would
translate to a struct named `MemoryAttribute`. …
=> Add MemoryProtection protocol

xtask/src/cargo.rs, xtask/src/main.rs, xtask/src/util.rs
Starting in rustup 1.25.0, the environment is modified during `cargo`
invocations in a way that breaks setting the channel arg
(e.g. "+nightly") in a subprocess.
Fix by unsetting those variables in the child cargo's env.
See https://github.com/rust-lang/rustup/issues/3031
=> xtask: Fix channel of cargo operations

CHANGELOG.md, src/table/boot.rs, uefi-test-runner/src/boot/misc.rs, uefi-test-runner/src/proto/console/gop.rs, uefi-test-runner/src/proto/console/mod.rs, uefi-test-runner/src/proto/console/pointer.rs, uefi-test-runner/src/proto/console/serial.rs, uefi-test-runner/src/proto/device_path.rs, uefi-test-runner/src/proto/media/mod.rs, uefi-test-runner/src/proto/mod.rs, uefi-test-runner/src/proto/pi/mod.rs, uefi-test-runner/src/proto/pi/mp.rs, uefi-test-runner/src/proto/rng.rs, uefi-test-runner/src/proto/shim.rs
Overview:
* Add `BootServices::get_handle_for_protocol`. This is a convenience method for finding one arbitrary handle that supports a protocol.
* Mark `locate_protocol` as `unsafe` and deprecated, as it has the same safety problems as `handle_protocol`.
* Mark `handle_protocol` as `unsafe` (it's already deprecated).
* Update all the test code to use `open_protocol` instead of `locate_protocol`.
Using `open_protocol` is now the only undeprecated way of opening a protocol. There's still some more safety work to do here -- if the protocol isn't opened in exclusive mode, or if the `agent` parameter isn't set correctly, UB could result. But pushing all users towards `open_protocol` is a good first step.
This is a partial fix for https://github.com/rust-osdev/uefi-rs/issues/359
=> Protocol safety improvements

src/data_types/mod.rs, src/data_types/owned_strs.rs, src/data_types/strs.rs
~I cleaned up and improved the code of `.eq()`-implementations for `CStr16` and `CString16`. Now it is easy to compare `&str` and `String` from the standard library with UEFI strings.~
~Let me know what you think.~
According to the discussion, I changed the PR. Now there is a common trait which allows to compare Rust strings (str, String) against CStr16 and CString16.
PS: If it's okay for you, I'd be happy to support you as a maintainer/developer in `uefi-rs` as I'm submitting stuff to uefi-rs anyway from time to time. Just let me know if you need support
=> EqStrUntilNul trait to compare Rust strings (str, String) against CStr16 and CString16

CHANGELOG.md
This adds a changelog entry which I forgot in #462 
PS: I guess that we create an PR for everything and review it? Or would it be fine to directly push such small changes to main? (I do not know If I have rights for it, I did not test it) @nicholasbishop @GabrielMajeri
=> changelog: added `EqStrUntilNul` trait implementation

src/proto/media/disk.rs, src/proto/media/mod.rs, uefi-test-runner/src/proto/media/known_disk.rs
Adds the `EFI_DISK_IO_PROTOCOL` and `EFI_DISK_IO2_PROTOCOL` protocols from the UEFI specification that build on top of the block I/O protocol to provide byte-oriented disk I/O.
=> Add `DiskIo` and `DiskIo2` protocols

src/table/boot.rs
The replacement for accessing this field (Deref/DerefMut on
ScopedProtocol) isn't part of 0.16.0, so it isn't correct to mark the
field deprecated in that version. Bump to 0.17.0, which should be the
next version of uefi.
Fixes https://github.com/rust-osdev/uefi-rs/issues/484
=> Update deprecation version in ScopedProtocol::interface

Cargo.toml, uefi-macros/Cargo.toml, uefi-services/Cargo.toml
Allow older versions of some dependencies to be used if that's all
that's available. This change will have no effect for typical builds
with Cargo, as Cargo will just pick the latest version and download
it. But in more restrictive/sandboxed build environments where the
latest versions of packages might not be available, it's helpful to
allow a wider range of versions.
Only non-dev dependencies have been changed, and only in the three
published packages.
Tested locally by temporarily prefixing these depdency versions with `=`
to force Cargo to use exactly that version, and verifying that
build/test/run commands still worked.
=> Relax version requirements for various deps

Cargo.toml, src/lib.rs
Add a `docsrs` config in the `docs.rs` metadata in Cargo.toml. This will
set `--cfg docsrs` when building on docs.rs. Enable the `doc_auto_cfg`
feature when the `docsrs` config is enabled. This feature is currently
unstable, but docs.rs uses a nightly compiler so this works fine.
The effect of this is that docs.rs will show a badge for items that are
only available if some feature is enabled. For example,
`BootServices::find_handles` will have a badge saying "Available on
crate feature exts only."
To view this locally, run this:
```
RUSTDOCFLAGS="--cfg=docsrs" cargo +nightly doc --all-features --open
```
This change has only been applied to the `uefi` package, since the
`uefi-macros` package does not have any features and the `uefi-services`
package's features don't control the visiblity …
=> Use doc_auto_cfg to show feature requirements on docs.rs

CHANGELOG.md
https://github.com/rust-osdev/uefi-rs/issues/488
=> Update changelog for 0.16.1

src/data_types/guid.rs
Allows Guids to be used in more collections such as https://doc.rust-lang.org/std/collections/struct.BTreeSet.html
=> add Ord and PartialOrd for Guid struct

CHANGELOG.md, Cargo.toml, src/logger.rs
Similar to #456, this PR refactors the `ignore-logger-errors` feature to the new additive `panic-on-logger-errors` feature.
=> Transform feature "ignore-logger-errors" to additive feature.

src/proto/media/block.rs
This is a breaking typo fix. But as `main` already contains some breaking changes since 0.16, I feel that it's the right time to fix it.
=> is_media_preset -> is_media_present in BlockIOMedia

src/data_types/enums.rs, src/proto/device_path/mod.rs
This PR implements the `HardDriveMediaDevicePath` specialization of `DevicePathNode`.
I basically looked at the existing `FilePathMediaDevicePath` and added the new structure with a similar API.
This has been tested on the TianoCore UEFI of QEMU.
I've also added unit tests against the raw bytes of `HardDriveMediaDevicePath` for an MBR and a GPT partition.
=> Implement `HardDriveMediaDevicePath` (along with MBR and GPT tests). 

CHANGELOG.md, src/table/boot.rs, uefi-macros/src/lib.rs, uefi-macros/tests/ui/entry_unnamed_image_arg.rs, uefi-macros/tests/ui/entry_unnamed_image_arg.stderr, uefi-macros/tests/ui/entry_unnamed_table_arg.rs, uefi-macros/tests/ui/entry_unnamed_table_arg.stderr, uefi-test-runner/src/main.rs, uefi-test-runner/src/proto/console/gop.rs, uefi-test-runner/src/proto/console/mod.rs, uefi-test-runner/src/proto/console/pointer.rs, uefi-test-runner/src/proto/console/serial.rs, uefi-test-runner/src/proto/debug.rs, uefi-test-runner/src/proto/device_path.rs, uefi-test-runner/src/proto/loaded_image.rs, uefi-test-runner/src/proto/media/known_disk.rs, uefi-test-runner/src/proto/media/mod.rs, uefi-test-runner/src/proto/mod.rs, uefi-test-runner/src/proto/network.rs, uefi-test-runner/src/proto/pi/mod.rs, uefi-test-runner/src/proto/pi/mp.rs, uefi-test-runner/src/proto/rng.rs, uefi-test-runner/src/proto/shim.rs
This is a change I've been noodling on for a bit related to https://github.com/rust-osdev/uefi-rs/issues/359. The basic issue is that in order to use protocols fully safely, with no chance of either the handle or protocol being modified or removed while in use, we need to ensure that protocols are opened in exclusive mode with the correct agent handle set. We've made some good steps towards that by deprecating and marking unsafe things like `handle_protocol`, but there are still unsafe ways to use `open_protocol`.
To resolve this (to the extent possible given the design of UEFI), I've added a new `open_protocol_exclusive` function. This function is fully safe; it ensures that the correct agent is set through the use of a new global image handle set by the `#[entry]` macro, and always …
=> More protocol safety improvements

CHANGELOG.md, src/lib.rs, src/proto/shim/mod.rs, src/result/status.rs
It seems like there's still a fair amount of discussion around what the
Try API should look like in the tracking issue for try_trait_v2. This
could lead to the API being changed in the nightly compiler, and
breaking uefi-rs compilation (which is particularly annoying when using
a released version rather than the latest git version).
To avoid that possibility, just drop the feature as it is not much used
in uefi-rs and can easily be replaced. As described in the changelog,
most uses can be fixed by adding a call to `into()`. If the compiler
needs a bit more help, `Result::from(status)` can be used.
https://github.com/rust-osdev/uefi-rs/issues/452
=> Drop use of unstable try_trait_v2 feature

.github/workflows/rust.yml, BUILDING.md, README.md, rust-toolchain.toml, template/README.md, template/rust-toolchain.toml, xtask/src/cargo.rs, xtask/src/main.rs, xtask/src/opt.rs
(See the two commits for more details)
=> Add rust-toolchain.toml and pin to a working nightly

CHANGELOG.md
The change to `#[entry]` is mentioned in the `uefi` section already since it's also relevant there, but worth mentioning in the
`uefi-macros` section as well so that it's clear why there's a new version and to note that the arguments to main must now be named.
help.
=> Update changelog for uefi-macros

CHANGELOG.md, src/proto/media/file/dir.rs, src/proto/media/file/mod.rs, src/proto/media/file/regular.rs, src/result/error.rs, uefi-test-runner/src/proto/media/known_disk.rs
This MR adds the "is_regular_file" and "is_regular_directory"-methods for the File-trait which is especially useful if you work with the generic `FileHandle` abstraction. 
~~Furthermore, it splits up the existing integration test a little for a clearer separation of concerns. The simple file system protocol test now tests creating a file in the root volume. On this file, I test my newly created additions.~~
~~Additionally, `FileHandle::into_type` now returns a direct value instead of a Result. If we have a failure there, it is a hard-bug in the uefi-rs lib and not something the user should take care of.~~
=> "is_regular_file" for file trait + integration test

CHANGELOG.md, src/data_types/strs.rs
- CStr8 can now be constructed from core::ffi::CStr
- CStr8 now also implements EqStrUntilNul
- some streamlining with the existing and more mature CStr16 type
help.
=> CStr8 cleanup and enhancements

CHANGELOG.md, src/data_types/strs.rs
The move of `CStr` from `std` to `core` is not due to become stable until 1.64. The first nightly where it could be used without the unstable `core_c_str` feature was 2022-07-16, which is still pretty recent. Let's back this change out for now to give users pinned to older versions more time.
help.
=> Temporarily revert use of core::ffi::CStr

CHANGELOG.md, Cargo.toml, template/Cargo.toml, uefi-macros/Cargo.toml, uefi-services/Cargo.toml
=> Release uefi-macros-0.8.0, uefi-0.17.0, uefi-services-0.14.0

CHANGELOG.md, src/data_types/mod.rs, src/proto/security/memory_protection.rs, src/table/boot.rs
These correspond to `EFI_PHYSICAL_ADDRESS` and `EFI_VIRTUAL_ADDRESS`. These usually end up being converted to a pointer type, but notably they are always 64-bit regardless of the target platform. This change revealed a bug in the `AllocateType` enum; it was using `usize` for a couple members, but that is not correct for all targets, e.g. `i686-unknown-uefi`.
help.
=> Add PhysicalAddress and VirtualAddress type aliases

.github/workflows/msrv_toolchain.toml, .github/workflows/rust.yml, README.md
Add a CI job that runs `cargo xtask build` with an old nightly. Currently the oldest nightly that works is 2022-04-18. There's nothing particularly magic about that version; we can require a newer version when we deem it appropriate. Having this CI job just makes it easy for us to identify in advance when a PR is going to require a newer nightly, while still allowing other CI jobs to use latest nightly.
This change is related to (but not a fix for): https://github.com/rust-osdev/uefi-rs/issues/510
help.
=> ci: Test the build on an old nightly

rust-toolchain.toml, template/rust-toolchain.toml, xtask/src/cargo.rs, xtask/src/main.rs, xtask/src/pipe.rs, xtask/src/qemu.rs
The bug in nightly Rust that was causing problems for us has been fixed, so switch back to latest nightly. (The other changes are due to the current nightly clippy warning about some unnecessary borrows.)
Fixes https://github.com/rust-osdev/uefi-rs/issues/500
help.
=> Switch the toolchain back to latest nightly

CHANGELOG.md, src/proto/device_path/text.rs
The specification of the conversion functions is a little unusual in that they return a pointer rather than `EFI_STATUS`, and that's reflected in us previously returning an `Option` here, but `Result` is more appropriate for a Rust API.
help.
=> Change DevicePath[From|To]Text methods to return a Result

uefi-macros/LICENSE, uefi-services/LICENSE
It's good practice to include the license file in each published crate so that the crates.io archive includes the full license text. This comes up for example when using `cargo vendor`; you generally want to make sure that all your third-party deps have a license file.
help.
=> Copy license file to uefi-macros and uefi-services

README.md
Add a link to the book, links to docs.rs reference for uefi-macros and uefi-services, and reword things a bit.
[Rendered](https://github.com/rust-osdev/uefi-rs/blob/29efb4ab0ff84abb8fad78b6b801ecaac9e7b308/README.md#documentation)
help.
=> Update documentation section of readme

CHANGELOG.md, uefi-services/src/lib.rs
The panic handler now displays its log message using `println!` instead of `error!`. The message prefix is altered from [ERROR] to [PANIC]. The extraneous filename and line number printed by `error!` are also removed from the log message.
Previously, the panic handler in `uefi-services` would use `error!` to print a log message. By using `error!`, the log message would also include the file name and line number of the panic handler function. As the file name and line number where the panic originated from are logged using the `PanicInfo` struct, this information is not necessary. By printing the log message with `println!` instead of `error!` this unnecessary information can be removed.
I temporarily added a panic call to the uefi test runner to show the panic log messages:
```rust
// ... …
```
=> uefi-services: Change panic handler log message.

uefi-services/src/lib.rs
Fixup for https://github.com/rust-osdev/uefi-rs/pull/526
help.
=> Fix warning from unneeded `macro_use`

xtask/src/opt.rs, xtask/src/qemu.rs
`cargo xtask run` now takes a `--disable-network` arg that turns off the network protocol tests by not creating a network device.
The purpose of this flag is to make the QEMU tests faster when iterating on something locally. Disabling the network stuff drops the time down from ~12.5s to ~4.5s. The extra time doesn't matter when running in CI, but for quick local testing it can add up.
help.
=> Add option to disable network tests

CHANGELOG.md, src/data_types/guid.rs, src/lib.rs, src/proto/device_path/mod.rs, src/proto/media/partition.rs, src/proto/rng.rs, src/table/cfg.rs, src/table/runtime.rs, uefi-macros/src/lib.rs, uefi-test-runner/src/runtime/vars.rs
This is similar to `Guid::from_values`, but takes a more convenient string argument like the `unsafe_guid!` attribute macro.
In the second commit, various uses of `Guid::from_value` are converted to use `guid!` instead. Should be no functional change from that, just a little shorter and easier to read.
help.
=> Add `guid!` macro

CHANGELOG.md, src/data_types/guid.rs
=> Add Guid methods to convert to/from byte arrays

.github/PULL_REQUEST_TEMPLATE.md
Github renders the line breaks in the template, so for the "sensible git history" item it gets split across three lines in the PR description. Change it to a single line just to be a little prettier.
help.
=> Tweak pull request template wrapping

.github/workflows/rust.yml, xtask/src/qemu.rs
The aarch64 and ia32 jobs had some extra complexity to get a working OVMF on ubuntu-20.04. Now that there are ubuntu-22.04 runners available, switch the jobs to that version and use the provided OVMF packages.
This change exposed an issue with `--target ia32`; it didn't work with the `ovmf-ia32` package on Ubuntu. Fixed by running the ia32 target using the same settings as x86_64. The important difference is really `-machine q35`, but we might as well share all the settings.
Running the 32-bit firmware on a 64-bit machine is actually a slightly more realistic test than running it on a 32-bit machine, since (at least to my knowledge) ia32 UEFI on a 64-bit CPU is more commonly found on real hardware than on a 32-bit CPU.
[Rewriting …
=> ci: Simplify some jobs with ubuntu-22.04 runner

src/data_types/guid.rs, src/logger.rs, src/table/revision.rs, src/table/runtime.rs, xtask/src/pipe.rs, xtask/src/qemu.rs
Clippy now warns when arguments in a format string could be specified inline, e.g. `format!({var})` instead of `format!({}, var)`. Note that only standalone variables can be used in this way, e.g. `{var}` works, but not `{self.var}`.
I think it helps readability to be consistent within a format string and only use one style, so in cases where any of the arguments could be done in the new style I introduced new local variables as needed.
=> Fix clippy warnings

CHANGELOG.md, src/table/revision.rs, src/table/system.rs
* Changed firmware-revision to an opaque `u32` instead of a `Revision`. The `Revision` type is specific to a UEFI revision, but the firmware revision doesn't have any defined semantics (it's not necessarily a major.minor format).
* Fixed the repr for `Revision` to be transparent
* Added `EFI_2_100` for the latest spec revision
* Added a new `Display` impl for `Revision` that formats correctly for all spec versions.
* Replaced the custom `Debug` impl with a derived impl; the new `Display` impl can be used for pretty formatting.
help.
=> Fixes and improvements for `Revision`

CHANGELOG.md, src/data_types/mod.rs, src/data_types/owned_strs.rs, src/data_types/strs.rs, src/data_types/unaligned_slice.rs, src/proto/device_path/mod.rs
I added `UnalignedCStr16` a while ago for use with device path nodes, which sometimes end in a DST string. Since device path nodes are all packed structures, the DST slice may be unaligned, so you can't return a normal reference as that would be UB.
Some device path nodes end with DST slices that aren't strings. For example, `ACPI _ADR` ends with a `[u32]` slice. So we need something more general than `UnalignedCStr16`, which is what `UnalignedSlice` is. An `UnalignedSlice<u16>` provides the same `to_cstr16` and `to_cstring16` methods as `UnalignedCStr16`, so for existing caller's this should be a pretty transparent change.
=> Replace `UnalignedCStr16` with `UnalignedSlice`

CHANGELOG.md, src/proto/device_path/mod.rs
The first commit is a bit of code cleanup: the spec uses base-10 for the device path node subtypes, but our enum used base-16, which made it hard to see at a glance if the values matched. Changed them to match how they are written in the spec.
The second commit adds a couple more subtypes, making our list fully up-to-date with UEFI v2.10.
=> Add new `DeviceSubType` values

xtask/Cargo.toml, xtask/src/disk.rs
Updates the `xtask` package's `mbrman` dependency to 0.5.0. This new version has a small breaking change which we had to fix.
Supersedes #531.
=> Update `mbrman` to 0.5.0

src/data_types/strs.rs, src/data_types/unaligned_slice.rs, src/proto/console/gop.rs, src/proto/console/pointer/mod.rs, src/proto/console/serial.rs, src/proto/console/text/input.rs, src/proto/console/text/output.rs, src/proto/debug/mod.rs, src/proto/device_path/mod.rs, src/proto/loaded_image.rs, src/proto/media/block.rs, src/proto/media/file/info.rs, src/proto/media/partition.rs, src/proto/network/pxe.rs, src/proto/pi/mp.rs, src/result/error.rs, src/result/status.rs, src/table/runtime.rs, src/table/system.rs
This adds `const` to all trivial getters where possible. Although applications in the field will barely benefit from this, I like about `const` that it ensures that a function is pure, i.e., has no side-effects during runtime.
I did this with the help of `cargo clippy -- -D clippy::missing_const_for_fn`.
=> const fn for trivial getters where possible

CHANGELOG.md
The panic handler change accidentally went under the previous release's section. Move it up to the current unreleased version.
=> Fix location of a changelog item

CHANGELOG.md, src/table/boot.rs
This PR adds functionality that was added to UEFI 2.10, mantis #2229 - "Support ISA-specific memory attributes in descriptors". 
- [ X ] Sensible git history (for example, squash "typo" or "fix" commits). See the [Rewriting History](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History) guide for help.
- [ X ] Update the changelog (if necessary)
=> Support ISA-specific `MemoryAttribute`s in `MemoryDescriptor`s

CHANGELOG.md, src/data_types/mod.rs, src/table/boot.rs, uefi-test-runner/src/boot/misc.rs, uefi-test-runner/src/main.rs
This PR implements basic protocol handler services such as `(re/un)install_protocol_services` and allows a user to be notified when a protocol is installed through the implementation of `register_protocol_notify`. To support the implementation of `register_protocol_notify`, a variant was added to `SearchType` and any functions using it updated. A new type `SearchKey` was added to abstract over the void pointer given by `register_protocol_notify`. 
There was one `enum` added to support `install_protocol_services` that currently has only one variant, 'InterfaceType'. I have chosen to make this `enum` public to be forwards-compatible, but in the implementation of `install_protocol_services` I don't include an `interface_type` parameter yet as `InterfaceType` and simply pass the only variant. …
=> Implement additional `BootServices` functions

uefi-test-runner/src/proto/media/known_disk.rs, uefi-test-runner/src/proto/media/mod.rs
A few minor documentation improvements.
=> fs-tests: doc improvements

CHANGELOG.md
This adds the publishing date to all versions in the changelog. I think this is a very informative information as it better reflects the freshness of a project than just version numbers.
=> changelog: add publish date to all versions

.github/workflows/msrv_toolchain.toml, README.md, book/src/tutorial/building.md, template/.cargo/config, xtask/src/cargo.rs
They are implicit on uefi as of https://github.com/rust-lang/compiler-builtins/pull/473 from June, so we can simplify the examples and the build stuff a bit. This is sort of a follow-up to #298.
help.
I'm not sure whether updating the changelog is necessary as this doesn't really break anything.
Though, this only works with a nightly compiler newer than 2022-08-07, so I guess you might
=> Don't explicitly require compiler-builtins(-mem)

xtask/Cargo.toml
This is a hopefully very temporary workaround for https://github.com/rust-osdev/uefi-rs/issues/573.
=> Add temporary workaround for yanked dependency

src/data_types/mod.rs, src/data_types/strs.rs, src/data_types/unaligned_slice.rs, src/proto/console/gop.rs, src/proto/device_path/mod.rs, src/proto/media/block.rs, src/proto/media/file/mod.rs, src/proto/network/pxe.rs, src/result/error.rs, src/table/boot.rs, src/table/runtime.rs, src/table/system.rs
This is a follow-up to #545. It adds `const fn` everywhere possible.
We need to keep in mind that future refactorings might need to drop the `const`. This is considered fine as we do not require things to be `const`. In our case, it mainly helps to know if there will be side effects or not.
=> const fn wherever possible

xtask/src/arch.rs
Derive `clap::ValueEnum` on `UefiArch`. This improves the help output, it now lists the allowed values:
```
--target <TARGET>        UEFI target to build for [default: x86_64] [possible values: aarch64, ia32, x86_64]
```
=> Improve clap help for `--target`

uefi/README.md
This is mostly copied from the top-level readme, with some edits to focus more on the `uefi` package rather than the whole project.
I think it might make sense to do some cleanups in the top-level readme as well so there's less duplicated content, but I'll leave that for a different PR.
=> Add uefi/README.md

uefi-test-runner/Cargo.toml, uefi-test-runner/README.md, uefi-test-runner/src/main.rs, uefi-test-runner/src/proto/media/known_disk.rs, xtask/src/cargo.rs, xtask/src/main.rs
This takes care of some of the low-hanging fruit for https://github.com/rust-osdev/uefi-rs/issues/553:
* Update the readme to mention the test program just runs in the special QEMU env
* Assert that the firmware string is "EDK II"
* Drop the `qemu` feature from `uefi-test-runner`, since we always want that behavior now.
In a future PR I'll do some more cleanups like changing warn/error logs to asserts, but this will require some care because the supported protocols are a bit different between x86 and arm.
=> uefi-test-runner: Assume that we're running in the special QEMU env

CHANGELOG.md, uefi/src/data_types/owned_strs.rs, uefi/src/data_types/strs.rs
I noticed that there is some small room for improvement for the `EqStrUntilNul` trait.
=> Several small improvements to EqStrUntilNul

CHANGELOG.md, uefi/src/data_types/strs.rs
After this was reverted in 5f4e15870513954d4a3c8b5099f26b42eecaaf28, we now can add it again, as our MSRV is now recent enough.
This reverts https://github.com/rust-osdev/uefi-rs/pull/509 and closes https://github.com/rust-osdev/uefi-rs/issues/510
=> `TryFrom<core::ffi::CStr>` implementation for `CStr8`

CHANGELOG.md, uefi-test-runner/src/proto/media/known_disk.rs, uefi/src/lib.rs, uefi/src/mem.rs, uefi/src/proto/media/file/dir.rs, uefi/src/proto/media/file/mod.rs, xtask/src/cargo.rs
This adds a function to `Directory` to get directory entry information as boxed/owned values. This is done similar to `File::get_boxed_info` [commit1]. Unfortunately, the code is almost identical. I tried to create a new commonly shared abstraction [commit2]. However, it is not that easy to let it compile successfully. I'm seeking for advice.
=> `Directory::read_entry_boxed` plus common abstraction `make_boxed`

uefi-test-runner/src/main.rs, uefi-test-runner/src/proto/console/gop.rs, xtask/src/pipe.rs, xtask/src/qemu.rs
This contains a number of related improvements to the test runner. The main changes are:
* If the screenshot test fails for some reason, don't dump the raw pixel data to the console. The data is not human-readable anyway, and if your console is slow it can take a while to print it all.
* Drop the second serial device from the test runner. We added this a while ago to fix the conflict in the screenshot test between needing to open the serial device in exclusive mode (so that the timeout and input aren't messed with by other EDK2 code) and needing to continue writing logs after the screenshot. Turns out there's a simpler way to fix this: we can use a single serial device, which does break the console logger, but we can restore the console output with `connect_controller`.
* Add …
=> Simplify serial usage in test-runner and check that tests completed

BUILDING.md, book/src/tutorial/building.md, rust-toolchain.toml, template/.cargo/config.toml, template/README.md, template/rust-toolchain.toml, xtask/src/cargo.rs
As of `nightly-2022-11-10` the UEFI targets are tier 2 and available via rustup. That means we can switch to building without `build-std`.
In order to continue testing the older nightly, `cargo xtask build` checks if the targets are installed and switches back to `build-std` if not.
Fixes https://github.com/rust-osdev/uefi-rs/issues/504
=> Install UEFI targets via rustup

.github/workflows/msrv_toolchain.toml, CHANGELOG.md, README.md, uefi/src/lib.rs, uefi/src/result/error.rs, uefi/src/result/status.rs
In order to use error-handling crates, such as [anyhow](https://crates.io/crates/anyhow), the `uefi::Error` type needs to implement the [`Error`](https://doc.rust-lang.org/core/error/trait.Error.html) trait.
To do this, I had to bump the minimum nightly version a couple of days to enable the `error_in_core` feature.
=> Implement Error trait for uefi::Error

book/src/SUMMARY.md, book/src/how_to/drawing.md, uefi-test-runner/examples/sierpinski.rs
This example draws a fractal to the screen using the grahpics output protocol.
=> book: Add a graphics example

uefi/src/data_types/strs.rs, uefi/src/proto/console/text/output.rs, uefi/src/proto/media/file/dir.rs, uefi/src/proto/media/file/mod.rs, uefi/src/proto/media/file/regular.rs, uefi/src/result/mod.rs, uefi/src/result/status.rs, xtask/src/device_path/node.rs
~This MR improves the documentation of the low-level `read` method of the file system protocol on a regular file or a directory.~
Following our discussions, I changed the scope to:
documentation and code improvements for Status, Error, and read()
=> documentation and code improvements for Status, Error, and read()

.github/workflows/rust.yml, uefi/Cargo.toml, uefi/src/lib.rs, uefi/src/result/error.rs, xtask/Cargo.toml, xtask/src/cargo.rs, xtask/src/main.rs, xtask/src/opt.rs
Note: the first commit in this PR is from https://github.com/rust-osdev/uefi-rs/pull/589 so that we don't have to resolve merge conflicts later.
This PR adds an `unstable` feature to the uefi crate. It will be used to gate new unstable features as we work towards being able to compile on the stable channel. Re naming, both `nightly` and `unstable` are used frequently by other crates. [`nightly` is slightly more common](https://github.com/rust-osdev/uefi-rs/pull/584#discussion_r1032697720), but I think `unstable` is more accurate since unstable features can be enabled on non-nightly builds of the compiler, and the documentation for these features is the [Unstable Book](https://doc.rust-lang.org/unstable-book/), as opposed to the "Nightly Book".
Also in this PR is a new build mode: `cargo …
=> Add `unstable` feature and improve CI for feature flags

.github/workflows/rust.yml, xtask/src/cargo.rs, xtask/src/main.rs, xtask/src/opt.rs
We do not publicly do this on docs.rs but having `--document-private-items` helps us to prevent illegal intra-doc links and other rustdoc errors in the documentation of private items.
=> doc: add '--document-private-items' to `cargo xtask doc`

uefi-test-runner/src/proto/console/pointer.rs, uefi-test-runner/src/proto/console/serial.rs, uefi-test-runner/src/proto/debug.rs, uefi-test-runner/src/proto/string/unicode_collation.rs
We now assume that tests are running in the special QEMU env, so change some of the tests to `expect` that a protocol is present rather than just `log::warn` if missing.
This change looks big due to removing `if` blocks creating big whitespace changes; `git show -w` will make it easier to see what's really changed.
https://github.com/rust-osdev/uefi-rs/issues/553
=> test-runner: Make some tests stricter

.github/workflows/rust.yml, CHANGELOG.md, uefi-test-runner/Cargo.toml, uefi/Cargo.toml, uefi/src/lib.rs, uefi/src/mem.rs, uefi/src/proto/media/file/dir.rs, uefi/src/proto/media/file/mod.rs, xtask/src/cargo.rs, xtask/src/main.rs, xtask/src/opt.rs
This closes #483. It builds on the foundation created in #559.
It adds the methods `read_entry_boxed_in` and `get_boxed_info_in` that need the new `unstable_alloc` feature. `Dir::read_entry_boxed` and `File::get_boxed_info` will work with both, stable and nightly Rust (i.e., default allocation and allocator api).
**However, there is one problem**: We need to discuss how we integrate unstable features into cargo xtask build/test.
I tested it manually, but we need to test in CI if everything builds with `unstable_alloc` and without.
=> Added `read_entry_boxed_in` and `get_boxed_info_in` that use the `allocator_api`

uefi-test-runner/src/proto/console/mod.rs, uefi-test-runner/src/proto/console/serial.rs
The serial test is occasionally failing in CI. I'm hoping that changing the test to open in exclusive mode will fix it, using the same trick of reconnecting all controllers that we do in `send_request_to_host`. It's hard to be sure though since the test failure doesn't occur all that often.
=> test-runner: Open serial device in exclusive mode

uefi/src/table/boot.rs
I added a list of possible errors that `BootServices::open_protocol` can return into the function's documentation.
Since each error could have multiple possible causes, I listed which chapter of the UEFI Specification this function can be found in. I figured that this would be better than copying every possible cause for every error of each function from the specification.
Please let me know if you think there might be a better way to list the types of errors returned from functions. I hope to add the possible returned error types for other `BootServices` functions in the future. :)
=> Add list of possible errors to `BootServices::open_protocol` docs

xtask/Cargo.toml
Fixes https://github.com/rust-osdev/uefi-rs/issues/573
=> xtask: Update to mbrman 0.5.1

uefi/src/table/boot.rs
Hi,
I added some more lists of returned error types to the documentation of functions in `BootServices`.
Please let me know if there's anything I could change. :)
=> Add list of possible errors to some `BootServices` function docs

CHANGELOG.md, uefi/src/data_types/unaligned_slice.rs
Slices and containers like `Vec` print their elements when formatted with `Debug`, so make `UnalignedSlice` do the same.
Also implement `Clone`, which just makes a shallow copy.
=> UnalignedSlice: impl Clone and improve Debug

uefi/src/table/boot.rs
Hello,
I added some more documentation to functions in `BootServices`.
I also rewrote some documentation in `BootServices::signal_event` to detail the possibility that some UEFI implementations might return an error, even though the UEFI Specification does not list any returned errors. I figured the documentation probably should not say that the function won't return any errors, since it returns a `Result`.
Does anyone else have advice for writing documentation on UEFI functions with errors that are not listed in the UEFI spec? It seems like this problem comes up a lot in UEFI. :)
=> Add docs to `BootServices` functions describing error cases

uefi-test-runner/src/proto/network/mod.rs, uefi-test-runner/src/proto/network/pxe.rs, uefi-test-runner/src/proto/network/snp.rs, uefi/src/proto/network/mod.rs, uefi/src/proto/network/snp.rs, xtask/src/util.rs
Fixes #431.
The code is written on top of @d-sonuga's PR, with the main change being in the tests, where an UDP packet is sent to the UDP echo server and the answer is read back.
=> Implement SIMPLE_NETWORK_PROTOCOL

uefi/src/table/boot.rs
I'm feeling like I made parts of the documentation more verbose than necessary. :P
This commit cuts back on words that I felt were unnecessary for the documentation. I like this shortened version better, but please let me know if you think the previous version was better.
=> Shortened error documentation for all methods in `BootServices`

uefi/src/data_types/owned_strs.rs
For issue #594.
I implemented the `Error` trait in the same way that it's implemented for `uefi::Error`.
I'm not sure where the `Error` trait is useful, so I haven't tested it beyond running the unit/qemu tests. :P I'm curious, though, what can this be used for?
Please let me know if this looks like a good solution for #594 and I'll implement these traits for other error types, as well.
=> Implement `Error` and `Display` traits for `FromStrError`

uefi/src/table/boot.rs
This is because the chapter numbers can change often in the UEFI specification, while identifiers do not.
Also added error documentation and UEFI spec references to other `BootServices` functions.
=> Replaced UEFI chapter numbers with function identifiers in the docs

.github/workflows/rust.yml, CHANGELOG.md, uefi-test-runner/src/proto/mod.rs, uefi-test-runner/src/proto/tcg.rs, uefi/src/proto/mod.rs, uefi/src/proto/tcg/enums.rs, uefi/src/proto/tcg/mod.rs, uefi/src/proto/tcg/v1.rs, uefi/src/proto/tcg/v2.rs, xtask/src/main.rs, xtask/src/opt.rs, xtask/src/qemu.rs, xtask/src/tpm.rs
This adds basic support for TPM v1 and v2 devices. Currently you can just query some information from the protocols; I'll be adding support for more active operations like extending PCRs in a future PR, but I didn't want to put too much in one PR.
`uefi-test-runner/src/proto/tcg.rs` has a basic example of how to use the current functionality.
=> Initial support for TCG TPM protocols

.editorconfig
This commit changes the `max_line_width` to 80 in `.editorconfig`. This is not mandatory nor enforced. However, 80 is also the default for commit messages and some editors guide users to follow this rule. For example, my CLion IDE automatically shows a line at width 80:
I think that a line-width of 80 is more suited than 100 from personal experience. However, I also used 100 as default for a long time.
PS: @nicholasbishop @GabrielMajeri : Merry Christmas!
=> Editorconfig: switch to max line width of 80

uefi/src/proto/media/file/dir.rs, uefi/src/proto/media/file/mod.rs, uefi/src/proto/media/file/regular.rs, uefi/src/proto/media/fs.rs, uefi/src/table/boot.rs
Also revised some existing documentation to match the current style of how most errors are documented.
=> Add some documentation for media protocols

uefi/src/proto/media/file/mod.rs
Clippy found this bug. Apparently, we do not have an integration test for it. We obtained the size of a reference, not of the data structure itself.
=> uefi: bug fix found by clippy

CHANGELOG.md, uefi/src/proto/console/gop.rs, uefi/src/table/boot.rs, uefi/src/table/system.rs
This commit addresses #616 and replaces three occurrences of `impl Iterator` with a specific type. I do not see a benefit in the `impl Iterator` design pattern in our code base. Using a specific, public type is simpler for end-users, as discussed in #616.
`impl Something` only makes sense, I think, in use-cases where users specify code, such as in [`actix-web`](https://actix.rs/):
```
async fn greet(req: HttpRequest) -> impl Responder {
let name = req.match_info().get("name").unwrap_or("World");
format!("Hello {}!", &name)
}
``` 
Or in situations where the return type is complex and nested with many generics.
=> Simplification: No longer return "impl Iterator"

CHANGELOG.md, uefi/Cargo.toml, uefi/src/lib.rs, uefi/src/proto/device_path/build.rs, uefi/src/proto/device_path/device_path_gen.rs, uefi/src/proto/device_path/mod.rs, uefi/src/proto/media/file/info.rs, uefi/src/proto/tcg/v1.rs, xtask/src/device_path/field.rs, xtask/src/device_path/mod.rs, xtask/src/device_path/node.rs
The `ptr_meta` crate (https://docs.rs/ptr_meta) is a polyfill for the unstable [`ptr_metadata`](https://github.com/rust-lang/rust/issues/81513) feature on stable Rust. This allows us to drop use of an unstable feature with fairly minimal code changes; mostly just adding a derive for the `Pointee` type on some DST structs.
https://github.com/rust-osdev/uefi-rs/issues/452
=> uefi: Add `ptr_meta` dependency

uefi/src/data_types/owned_strs.rs, uefi/src/data_types/strs.rs, uefi/src/lib.rs, uefi/src/polyfill.rs, uefi/src/proto/device_path/build.rs, uefi/src/proto/device_path/device_path_gen.rs, xtask/src/device_path/mod.rs, xtask/src/device_path/node.rs, xtask/src/device_path/spec.rs
The functionality we need from those features can be provided with a few pretty simple one-liner functions. Add those functions to the uefi crate in a new polyfill module.
https://github.com/rust-osdev/uefi-rs/issues/452
=> Drop unstable `maybe_uninit_slice` and `vec_into_raw_parts` features

uefi-test-runner/src/boot/memory.rs, uefi/src/data_types/owned_strs.rs, uefi/src/data_types/strs.rs, uefi/src/data_types/unaligned_slice.rs, uefi/src/lib.rs, uefi/src/proto/media/file/info.rs
No functional changes, just some minor code cleanups.
=> Minor alloc-related cleanups

uefi-test-runner/src/proto/media/known_disk.rs
This MR adds an integration test for creating directories and files in a freshly created directory.
I've faced an error with directory creation while working on #472 - so I thought it is smart to test this in a dedicated place on a lower level.
=> media/test: add integration test for creating a directory

uefi/README.md
The MSRV is listed in both the top-level readme and uefi readme; update the uefi readme to reflect the current correct value.
=> uefi: Update MSRV in the readme

uefi-test-runner/src/proto/tcg.rs, uefi/src/proto/tcg/mod.rs, uefi/src/proto/tcg/v1.rs
This adds support for logging to the event log and extending PCRs, as well as sending raw commands to the TPM. The QEMU test has been updated to cover these features as well.
=> Implement the rest of the TPM v1 interface

CHANGELOG.md, uefi/src/proto/network/pxe.rs
NOTE: This commit changes the API for `BaseCode::discover`, but should continue to be source-compatible. Edit: `DiscoverInfo` will break in cases where the generic can't be inferred, or where it's explicitly declared (eg, `DiscoverInfo<[Server; 4]>` needs to be changed to `DiscoverInfo<4>`).
The `info` parameter in `BaseCode::discover` is an optional pointer argument (it may be NULL), but is incorrectly specified in the Rust extern definition as `Option<*const T>`. This type is (at least) one byte larger than a Pointer on all platforms, making it incompatible with the Optional Pointers in EFI. Two possible fixes:
1. Remove `Option` wrapper (this is what the PR contains)
2. Convert to `Option<&T>` (chose not to use this since converting references requires unsafe)
The `DiscoverInfo` struct …
=> PXE: Fix BaseCode::discover optional argument

.github/workflows/rust.yml
This fixes the `Node.js 12 actions are deprecated` warnings, as seen for example here: https://github.com/rust-osdev/uefi-rs/actions/runs/3877009992
=> ci: Update checkout action to latest version

CHANGELOG.md, uefi/src/table/boot.rs
=> uefi: Remove useless padding field

template/src/main.rs, uefi-macros/tests/ui/entry_bad_abi.rs, uefi-macros/tests/ui/entry_bad_abi.stderr, uefi-macros/tests/ui/entry_bad_arg.rs, uefi-macros/tests/ui/entry_bad_arg.stderr, uefi-macros/tests/ui/entry_bad_async.rs, uefi-macros/tests/ui/entry_bad_async.stderr, uefi-macros/tests/ui/entry_bad_attr_arg.rs, uefi-macros/tests/ui/entry_bad_attr_arg.stderr, uefi-macros/tests/ui/entry_bad_const.rs, uefi-macros/tests/ui/entry_bad_const.stderr, uefi-macros/tests/ui/entry_bad_generic.rs, uefi-macros/tests/ui/entry_bad_generic.stderr, uefi-macros/tests/ui/entry_bad_return_type.rs, uefi-macros/tests/ui/entry_bad_return_type.stderr, uefi-macros/tests/ui/entry_unnamed_image_arg.rs, uefi-macros/tests/ui/entry_unnamed_image_arg.stderr, uefi-macros/tests/ui/entry_unnamed_table_arg.rs, uefi-macros/tests/ui/entry_unnamed_table_arg.stderr, uefi-services/src/lib.rs, uefi-test-runner/examples/hello_world.rs, uefi-test-runner/examples/loaded_image.rs, uefi-test-runner/examples/sierpinski.rs, uefi-test-runner/src/main.rs, uefi/src/lib.rs
The `abi_efiapi` feature has been stabilized, so in the very latest nightlies we get this warning from enabling it:
the feature `abi_efiapi` has been stable since 1.68.0-nightly and no longer requires an attribute to enable
We don't want to stop using `#![feature(abi_efiapi)]` just yet though, because that would require raising our nightly MSRV to 2023-01-13. So for now, to get the CI passing again, turn off the `stable_features` warning.
In the `uefi-macros` tests, just remove `#![feature(abi_efiapi)]` since that code is only run when developing uefi-rs, not when using it.
=> Fix warnings from `abi_efiapi` stabilization

uefi-test-runner/src/proto/tcg.rs, uefi/src/proto/tcg/v1.rs, uefi/src/proto/tcg/v2.rs
Companion PR to https://github.com/rust-osdev/uefi-rs/pull/631. This adds support in the V2 interface for logging to the event log and extending PCRs, getting/setting active banks, and sending raw commands to the TPM. The QEMU test has been updated to cover these features as well.
=> Implement the rest of the TPM v2 interface

uefi/src/lib.rs, uefi/src/proto/console/gop.rs, uefi/src/proto/loaded_image.rs, uefi/src/proto/network/pxe.rs, uefi/src/proto/tcg/mod.rs, uefi/src/proto/tcg/v1.rs, uefi/src/proto/tcg/v2.rs, uefi/src/util.rs
Add `uefi::util`, an internal module (not part of the public API) with some useful functions, and change some existing code to use those functions.
Just code cleanup, should be no real functional changes.
=> Move some util code from TCG to a new top-level module

CHANGELOG.md, uefi/src/table/boot.rs
A while ago we changed `DevicePath` to be an unsized type, which necessitated some trait bound changes elsewhere. For example, `open_protocol_exclusive` changed from `P: Protocol` to `P: ProtocolPointer + ?Sized`. However, there are a number of other functions in boot services that take a generic protocol, and they weren't updated so they don't work with unsized protocols. This commit fixes all of those functions.
=> uefi: Fix protocol functions to work with unsized protocols

.github/workflows/book.yml
Forks regularly fail as the book/deploy step fails there.
=> ci: fix book/deploy in forks

uefi/src/proto/device_path/mod.rs
Deriving `Debug` and `PartialEq` on a packed struct containing `[u8]` fields is being phased out. See https://github.com/rust-lang/rust/issues/107457 for more info. (I'm not really clear on _why_ this is being phased out since it seems easy enough to work around, but probably the info is buried somewhere in the many comments on the PR linked in that issue.)
=> Fix new lints related to derives on a packed struct

uefi/src/proto/security/memory_protection.rs, uefi/src/table/boot.rs
=> Add PAGE_SIZE constant and update MemoryProtection protocol docs

uefi-macros/tests/ui/entry_bad_arg.stderr, uefi-macros/tests/ui/entry_bad_return_type.stderr
The new error text is actually not as good, we'll want to make some updates to the `entry` macro to improve that in the future. Filed that as https://github.com/rust-osdev/uefi-rs/issues/649
=> uefi-macros: Fix error tests

CHANGELOG.md, uefi/Cargo.toml
Fixes https://github.com/rust-osdev/uefi-rs/issues/650
=> Release uefi-0.19.1

.github/workflows/rust.yml, uefi-test-runner/Cargo.toml, uefi-test-runner/src/proto/pi/mp.rs, uefi-test-runner/src/proto/tcg.rs, xtask/src/cargo.rs, xtask/src/main.rs, xtask/src/qemu.rs
In addition to fixing the tests under Windows, this PR enables adds running the VM tests under Windows to prevent future accidental breakage.
=> Various fixes for tests under Windows

uefi/src/proto/console/gop.rs
As pointed out in https://github.com/rust-osdev/uefi-rs/issues/612, our GOP docs said the protocol can be used both during boot services and during runtime. As far as I can tell this is incorrect; as with all other protocols it can only be used during boot services. (Of course, a firmware implementation might leave the memory initialized, giving the appearance that GOP is usable after exiting boot services, but that would essentially be a UAF bug.)
For some supporting evidence, see this presentation: https://uefi.org/sites/default/files/resources/UPFS11_P4_UEFI_GOP_AMD.pdf
> Major differences between GOP driver vs. legacy VGA BIOS:
> ...
> 2. Boot only services vs. both boot and OS run-time services
=> uefi: Remove mentions of runtime usage from GOP docs

CHANGELOG.md, uefi-test-runner/src/main.rs, uefi/src/table/system.rs
Exiting boot services is a one-way operation, which is why `exit_boot_services`
takes `self` rather than a reference. If it succeeds then you get back a
`SystemTable<Runtime>`, but even if it fails you can't continue to use boot
services except for a very limited subset. Specifically, in UEFI 2.8 and
earlier, only `get_memory_map` and `exit_boot_services` are allowed. Starting in
UEFI 2.9 other memory allocation functions may also be called.
To properly support pre-2.9 firmware then, the right thing to do is to
make sure that the initial buffer allocated to hold the memory map has
sufficient extra room in case the first attempt to get the memory map
and exit boot services fails. We now add room for 8 extra entries if
that occurs, matching the behavior of the Linux kernel: …
=> uefi: Rework `exit_boot_services` API

CHANGELOG.md, uefi-test-runner/src/proto/driver.rs, uefi-test-runner/src/proto/mod.rs, uefi/src/proto/driver/component_name.rs, uefi/src/proto/driver/mod.rs, uefi/src/proto/mod.rs
Add support for `EFI_COMPONENT_NAME_PROTOCOL` and
`EFI_COMPONENT_NAME2_PROTOCOL`. The former protocol has been deprecated since UEFI 2.1, but there are still some old devices (like some Macbooks) that don't support `EFI_COMPONENT_NAME2_PROTOCOL`.
The `ComponentName` wrapper type makes it easy to automatically use the V2 protocol if available, but fall back to V1 otherwise.
=> Add component name protocols

CHANGELOG.md, uefi/src/lib.rs
Previously these macros were only exported from the `prelude` module, but that's intended for glob imports which not everyone likes to use.
=> uefi: Export cstr8, cstr16, and entry macros from the root

CHANGELOG.md, uefi-test-runner/examples/loaded_image.rs, uefi-test-runner/src/boot/misc.rs, uefi-test-runner/src/boot/mod.rs, uefi-test-runner/src/proto/driver.rs, uefi-test-runner/src/proto/mod.rs, uefi/src/table/boot.rs
These types are smart pointers, so `Deref` is a good fit.
=> Implement `Deref` for `HandleBuffer` and `ProtocolsPerHandle`

uefi/src/proto/console/text/input.rs
Add intra-doc links and an example showing how to wait for an event and match both printable and special keys.
https://github.com/rust-osdev/uefi-rs/issues/660
=> uefi: Improve Input::read_key docstring

uefi-test-runner/Cargo.toml, uefi-test-runner/src/proto/network/pxe.rs, uefi-test-runner/src/proto/pi/mp.rs, xtask/src/cargo.rs, xtask/src/main.rs
Make the MP and PXE tests fail if the protocol isn't present. If the tests aren't supposed to pass then they are disabled by feature flag. This makes it easier to catch accidental breakage, since the tests will actually fail with an error instead of just printing a warning.
=> Make more tests fail if protocol is missing

.github/workflows/msrv_toolchain.toml, README.md, uefi/README.md, xtask/src/cargo.rs
This requires an MSRV bump to 2022-11-22. (The build-std targets were actually added in 2022-11-10, but there were some bugs in the dist at that time that cause linker errors on i686.)
=> xtask: Fully drop support for build-std

.github/workflows/rust.yml
There's no need to run `cargo xtask build` first, since the build happens anyway when calling `cargo xtask run`.
=> ci: Simplify the VM jobs

uefi-macros/src/lib.rs, uefi-macros/tests/ui/entry_bad_arg.stderr, uefi-macros/tests/ui/entry_bad_return_type.stderr
In Rust 1.69, the error output of our function typecheck will become less clear. Fix by doing an intermediate cast from the fn item to a fn pointer, and then checking the signature of that pointer.
Also improved the error span to point at the whole function signature rather than just the ident.
Fixes https://github.com/rust-osdev/uefi-rs/issues/649
=> uefi-macros: Improve entry macro errors

.github/workflows/rust.yml, uefi-test-runner/Cargo.toml, xtask/src/cargo.rs, xtask/src/main.rs, xtask/src/opt.rs
Add an `unstable` option to `uefi-test-runner` that controls whether the `unstable` feature of the `uefi` crate is enabled. Also add a separate CI job so that we test both with and without the unstable feature.
This change is a necessary prereq for testing on stable, since we can't unconditionally enable unstable features there.
=> test-runner: Make `unstable` an optional feature

xtask/Cargo.toml, xtask/src/disk.rs
fatfs got a new release after a couple years, switch to that instead of pinning to a git commit.
=> xtask: Switch fatfs to latest crates.io release

.github/workflows/rust.yml
The Windows job is sometimes hitting the four minute timeout, so bump it up by a couple minutes to avoid unnecessary flakes.
=> ci: Increase Windows job timeout

xtask/src/cargo.rs
I noticed while testing https://github.com/rust-osdev/uefi-rs/pull/662 that Miri is printing some useful warnings about pointer/integer casts. Enabling the `-Zmiri-strict-provenance` flag turns these warnings into errors so that they'll fail CI, otherwise it's easy to miss them.
=> xtask: Enable strict provenance checks in Miri

.github/workflows/nightly_toolchain.toml, .github/workflows/rust.yml
This job is in preparation for switching most of the CI to operating on the stable channel. We still need some actions to run on the nightly channel so we can test the `unstable` feature and run tests under miri.
To that end, move various steps under a single `nightly_channel` job. The job switches to the nightly channel using a new `nightly_toolchain.toml` file, so once we switch the top-level `rust-toolchain.toml` to stable, the new job will remain on nightly.
Note: we'll need to update our branch protection settings to merge this since the list of jobs has changed.
=> ci: Add a nightly_channel job

uefi-macros/src/lib.rs
The `entry` macro's example code had `#![no_std]` in it to make it look like how you'd normally use it with the uefi targets. In the context that the example code is compiled in though, the target is the host's target. To get the example compiling there, we had to add some hidden hacks for `eh_personality` and a panic handler. Those hacks don't work on the stable channel though, so drop them along with `no_std`.
=> uefi-macros: Make `entry` example more compatible with stable

.github/workflows/rust.yml, xtask/src/main.rs, xtask/src/opt.rs
The uefi-macros tests check that the expected compiler output is produced for errors. The error output is slightly different between stable and nightly, so when we transition to testing on stable we have to handle that somehow. We could potentially have two sets of expected output, one for stable and one for nightly, but that's probably more trouble than it's worth. Instead, add an option to skip the uefi-macros tests, and enable that flag in the CI job for the nightly channel.
=> xtask: Add option to skip uefi-macros tests

uefi-macros/src/lib.rs, uefi-macros/tests/ui/entry_unnamed_image_arg.stderr, uefi-macros/tests/ui/entry_unnamed_table_arg.stderr
When the macro produces an error due to unnamed arguments, point precisely at the `_` part of the argument, rather than the whole argument including the type.
=> uefi-macros: Use a more precise error span

CHANGELOG.md, uefi-test-runner/src/runtime/vars.rs, uefi/src/table/runtime.rs
Fixes https://github.com/rust-osdev/uefi-rs/issues/681
Deleting a UEFI variable seems a useful low level primitive for this lib to provide. 
Side note: Be gentle, I'm new to Rust and probably doing dumb things -- all advice welcome. Thx.
=> uefi: Add delete_variable() helper

uefi/src/lib.rs
Reorganize the information in the top-level `uefi` docstring a bit. Also add links to the book and spec, and various other links.
=> uefi: Update package docstring

README.md, uefi/README.md
These sections were mostly duplicated between the top-level readme and the `uefi` package's readme. In the top-level readme, it had a broken link to the `BUILDING.md` document which has been deleted.
Since we now have "Documentation" sections in both those readmes, the "Building UEFI programs" section was mostly redundent, except for the part about MSRV. Add new MSRV sections, and in the top-level readme just link to the `uefi` package's readme so that we don't have to update both places when the MSRV changes.
=> Rework "Building UEFI programs" sections in the readmes

CHANGELOG.md, uefi-test-runner/src/proto/mod.rs, uefi/src/logger.rs, uefi/src/proto/console/text/output.rs, uefi/src/table/system.rs
The `Output` protocol has an internal pointer to an `OutputData` object. This was represented as a reference with the `'boot` lifetime, but this isn't quite right since the actual lifetime could be shorter than boot services. Furthermore, in several places the lifetime was set to `'static`, which is definitely not correct.
Fix by dropping the lifetime parameter, and instead just use a raw pointer. This is more in line with how we've implemented other protocols.
=> uefi: Drop `'boot` lifetime from Output protocol

CHANGELOG.md, uefi/src/result/error.rs
Implements a solution for the discussion in https://github.com/rust-osdev/uefi-rs/issues/691.
=> error: enable core::error::Error for all error payloads

CHANGELOG.md, uefi/src/proto/console/gop.rs, uefi/src/proto/console/pointer/mod.rs, uefi/src/proto/console/serial.rs
Similar to https://github.com/rust-osdev/uefi-rs/pull/689, drop some `'boot` lifetimes from a few more older protocol implementations. These protocols have internal data pointers, and they are best expressed as raw pointers because we don't actually control the lifetime. When returning the data via a method we can tie the borrow's lifetime to `&self`.
=> Remove some more protocol lifetime parameters

CHANGELOG.md, uefi/src/data_types/owned_strs.rs
`CString16` can be borrowed as `&CStr16`, and `CStr16` can be converted to `CString16` with `to_owned()`.
=> uefi: Implement Borrow/ToOwned for CString16/CStr16

xtask/Cargo.toml, xtask/src/device_path/field.rs, xtask/src/device_path/group.rs, xtask/src/device_path/node.rs, xtask/src/device_path/util.rs
Some changes needed to use the new API for parsing attributes.
=> xtask: Upgrade to syn 2.0

uefi-test-runner/src/boot/memory.rs, uefi/src/table/boot.rs, uefi/src/table/system.rs
Added a sorted iterator and a method to convert a normal iterator to it.
Should close [issue#661](https://github.com/rust-osdev/uefi-rs/issues/661)
=> Add Sorted Iterator for the UEFI Memory Map (Issue#661)

.github/workflows/msrv_toolchain.toml, .github/workflows/rust.yml, CHANGELOG.md, book/src/tutorial/app.md, book/src/tutorial/building.md, rust-toolchain.toml, template/README.md, template/rust-toolchain.toml, template/src/main.rs, uefi-macros/src/lib.rs, uefi-macros/tests/ui/entry_bad_abi.stderr, uefi-macros/tests/ui/entry_bad_return_type.stderr, uefi-macros/tests/ui/guid_bad_hex_group2.stderr, uefi-macros/tests/ui/guid_bad_hex_group5.stderr, uefi-services/src/lib.rs, uefi-test-runner/examples/hello_world.rs, uefi-test-runner/examples/loaded_image.rs, uefi-test-runner/examples/sierpinski.rs, uefi-test-runner/src/main.rs, uefi/README.md, uefi/src/lib.rs, xtask/src/main.rs
Rust 1.68 is out, so we can use the stable channel now. This PR includes https://github.com/rust-osdev/uefi-rs/pull/617 and https://github.com/rust-osdev/uefi-rs/pull/636, removes nightly from the rust-toolchain files, updates the CI, and updates various docs.
Closes https://github.com/rust-osdev/uefi-rs/issues/452
Closes https://github.com/rust-osdev/uefi-rs/issues/638
=> Switch to the stable channel :tada: 

xtask/src/qemu.rs
The search order for finding the OVMF files is now:
1. Command-line argument (`--ovmf-code`, `--ovmf-vars`)
2. Environment variable (`OVMF_CODE`, `OVMF_VARS`)
3. OS-dependent paths
=> xtask: Add OVMF_CODE/OVMF_VARS env vars

.editorconfig, nix/nixpkgs.nix, shell.nix, xtask/Cargo.toml, xtask/src/qemu.rs
This enables to run `cargo xtask run` under NixOS. The challenge is to find the OVMF files.
=> OVMF: enable "cargo xtask run" under NixOS

.github/workflows/rust.yml
Now that most jobs are on the stable channel, enabling caching should be more effective than it would have been on nightly.
=> ci: Enable caching

.github/workflows/rust.yml, xtask/src/main.rs, xtask/src/opt.rs
This job was useful when we were on the nightly channel and using various unstable features that could break at any time, but there's not much value to keeping it now that we're on the stable channel.
The other minor thing the job checked was that the specific build command provided in the tutorial (originally in `BUILDING.md`) works. That was helpful back when we had some unstable (and verbose) `-Zbuild-std` flags, but now the build command is just `cargo build --target x86_64-unknown-uefi` which doesn't really need testing.
=> ci: Drop test_latest_release job

Cargo.lock, xtask/Cargo.toml
This drops a few dependencies of dependencies as can be seen in Cargo.lock.
=> xtask: Turn off some unnecessary dep features

uefi/src/table/system.rs
Static references have stronger guarantees than raw pointers, and since these fields are internal anyway let's avoid the risk of UB and keep them as raw pointers.
=> uefi: Remove static references from SystemTable implementation

uefi-macros/Cargo.toml, uefi-services/Cargo.toml, uefi/Cargo.toml
This indicates the MSRV, see cargo docs for more details: https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field
=> Set rust-version = 1.68 in all public packages

Cargo.toml
I'm confused as to how this hasn't caused problems to be missing -- like why does `cargo fmt --all` work for the `uefi` crate even though it was missing from this list?
=> Add uefi to workspace members

uefi/src/data_types/mod.rs, uefi/src/data_types/opaque.rs, uefi/src/proto/device_path/mod.rs, uefi/src/proto/network/pxe.rs, uefi/src/proto/tcg/v1.rs
There are several places where we copy a rather abstruse pattern from the nomicon for representing opaque structs for FFI purposes [1]. This is necessary until such time as as a proper extern type [2] is stabilized.
To avoid having to copy-paste this pattern, add a simple macro for it.
[1]: https://doc.rust-lang.org/stable/nomicon/ffi.html#representing-opaque-structs
[2]: https://rust-lang.github.io/rfcs/1861-extern-types.html
=> uefi: Add opaque_type macro

uefi/src/proto/console/serial.rs, uefi/src/proto/network/pxe.rs, uefi/src/proto/network/snp.rs, uefi/src/proto/pi/mp.rs, uefi/src/table/boot.rs, uefi/src/table/cfg.rs, uefi/src/table/runtime.rs
We use bitflags with FFI interfaces, so we should ensure the struct layout is correct.
=> uefi: Consistently set repr(transparent) on bitflags

.github/dependabot.yml
We don't need to update our `Cargo.toml` files anytime a new patch update is released. A minor or major release is more interesting, so leave those enabled.
=> dependabot: Ignore patch updates

.github/workflows/rust.yml
This job is still timing out sometimes. There are some open bugs about slow Windows runners, maybe relevant:
https://github.com/actions/runner-images/issues/7320
=> ci: Increase Windows timeout to 10 minutes

uefi-macros/src/lib.rs, uefi-test-runner/src/proto/device_path.rs, uefi-test-runner/src/proto/network/pxe.rs, uefi-test-runner/src/runtime/vars.rs, uefi/src/data_types/mod.rs, uefi/src/data_types/owned_strs.rs, uefi/src/data_types/strs.rs, uefi/src/lib.rs, uefi/src/mem.rs, uefi/src/proto/console/gop.rs, uefi/src/proto/device_path/text.rs, uefi/src/proto/loaded_image.rs, uefi/src/proto/media/file/info.rs, uefi/src/proto/media/file/mod.rs, uefi/src/proto/network/pxe.rs, uefi/src/proto/rng.rs, xtask/src/device_path/node.rs
Most of the project uses the style of only merging imports from the same module. Normally this isn't handled by `cargo fmt`, so there are some inconsistencies. There's an unstable option [1] to rustfmt to make imports consistent, so as a one-time operation apply that to all source files:
```
cargo fmt --all -- --config imports_granularity=Module
```
[1]: https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#module
=> Format `use` consistently

uefi-test-runner/src/proto/network/pxe.rs
The Windows CI job sometimes times out in the pxe test; add a retry loop around the read operation to see if that helps.
https://github.com/rust-osdev/uefi-rs/issues/741
=> test-runner: Speculative fix for Windows CI timeout

uefi/src/result/status.rs
The bit about "we can't use a Rust enum" is true of all the places we use `newtype_enum!`, so no need to call out `Status` in particular.
=> uefi: Update Status documentation

CHANGELOG.md, Cargo.lock, uefi-test-runner/src/fs/mod.rs, uefi-test-runner/src/main.rs, uefi-test-runner/src/proto/media.rs, uefi/Cargo.toml, uefi/src/fs/dir_entry_iter.rs, uefi/src/fs/file_system.rs, uefi/src/fs/mod.rs, uefi/src/fs/normalized_path.rs, uefi/src/fs/path.rs, uefi/src/fs/uefi_types.rs, uefi/src/lib.rs, uefi/src/table/boot.rs
Hi! This originated in a personal learning project and I'd like to know what others think about it. Would be cool if we can bring this upstream. It's about creating a high level FS abstraction over the existing FS protocol. It aims to be as close to top-level functions provided by `std::fs` as possible.
Usually, UEFI-application hackers want to do something like this:
- read configuration file from /foo/bar/config
- write to /for/bar/log.txt
- read /foo/bar/kernel.elf
```rust
let mut fs = FileSystem::new(
"boot",
system_table.boot_services().get_image_file_system(handle).unwrap()
);
fs.write("foobar.bin", [1,2,3]).unwrap();
fs.read("bar").unwrap_err();
fs.copy("foobar.bin", "bar").unwrap();
fs.read("bar").unwrap();
fs.rename("bar", "barfoo").unwrap(); …
```
=> Introducing a high-level FS abstraction

xtask/src/cargo.rs
Build documentation with `--no-deps` as this makes the documentation of the actual crate much clearer.
This is also similar to what `docs.rs` shows on their website.
=> doc: build with --no-deps

.github/workflows/rust.yml
Shorter + more descriptive CI job names.
I think the current names are too long for this view:
=> ci: shorter job names

uefi/src/data_types/guid.rs, uefi/src/fs/dir_entry_iter.rs, uefi/src/fs/file_system.rs, uefi/src/fs/normalized_path.rs, uefi/src/fs/uefi_types.rs, uefi/src/mem.rs, uefi/src/proto/device_path/build.rs, uefi/src/proto/string/unicode_collation.rs
Consistent use of `crate::` over `uefi::` in the codebase of `./uefi/src`.
=> uefi: consistent use of crate:: over uefi::

uefi/src/fs/mod.rs
* Typo fix
* Dropped "This may change in the future but is currently sufficient", I think it's usually clearer to stick to how things currently are in the docs, we can update the doc in the future if we actually change the API.
* Moved some things out of separate headers, the rustdoc style for h1/h2/h3 is so similar it's hard to even see stuff is semantically nested anyway.
=> uefi: Minor cleanups in the fs module doc

CHANGELOG.md, uefi/src/data_types/chars.rs, uefi/src/data_types/owned_strs.rs, uefi/src/data_types/strs.rs
For #747 I'm about to add a `PathBuf` struct as wrapper around `CString16`, akin to the standard library. For this, a lot of convenience functions are missing on `CStr16` and `CString16`. This PR adds those.
=> cstr[ing]16: convenience functions

uefi-test-runner/src/proto/debug.rs, uefi/src/proto/debug/mod.rs
DebugPort might be useful for some uefi applications.
=> uefi: debug: add DebugPort protocol

CHANGELOG.md, uefi-macros/src/lib.rs
For example, instead of this:
`#[unsafe_protocol("12345678-1234-5678-1234-567812345678")]`
You can do this:
`#[unsafe_protocol(path::of::some::guid::constant)]`
This is helpful to avoid repeating the GUID if you happen to have it defined somewhere else already.
=> Allow passing a constant's path into unsafe_protocol

.github/workflows/book.yml
This job needs write access to the repo. Hopefully this change is sufficient; I don't know how to test other than merge and see what happens.
Fixes https://github.com/rust-osdev/uefi-rs/issues/762
=> ci: Fix book token permission

uefi/src/proto/network/pxe.rs, uefi/src/proto/network/snp.rs
=> uefi: Clean up some Status -> Result conversions

uefi/src/proto/console/gop.rs
To check which mode is currently active, have to compare the ModeInfo structs.
https://blog.fpmurphy.com/2015/05/check-available-text-and-graphics-modes-from-uefi-shell.html does the same.
=> gop: Derive PartialEq on ModeInfo

Cargo.lock, uefi-raw/Cargo.toml, uefi-raw/src/lib.rs, uefi-raw/src/protocol/mod.rs, uefi-raw/src/protocol/rng.rs, uefi/src/proto/rng.rs
A couple naming notes:
* For uefi-raw, I went with a more explicit `protocol` module name rather than `proto`.
* Similarly, instead of naming the protocol `Rng` I named it `RngProtocol`. Unlike in the uefi crate, it doesn't implement a `Protocol` trait, so I think it makes sense to give it a longer name clearly indicating what it is.
Should be no change to the public API of `uefi` from this, all internal changes.
=> Add RngProtocol to `uefi-raw` and use it from `uefi`

CHANGELOG.md, uefi-test-runner/src/runtime/vars.rs, uefi/src/table/runtime.rs
This alloc-only method is a more convenient form of `get_variable`.
Closes https://github.com/rust-osdev/uefi-rs/issues/776
=> uefi: Add get_variable_boxed

uefi/src/proto/rng.rs
It shouldn't really make a difference here, but `repr(transparent)` is semantically clearer.
=> uefi: Switch Rng repr from C to transparent

CHANGELOG.md, uefi/src/table/boot.rs, uefi/src/table/system.rs
=> uefi: Make MEMORY_DESCRIPTOR_VERSION an associated constant

CHANGELOG.md, uefi-macros/src/lib.rs, uefi/src/lib.rs
Allow to use `cstr8!()`, `cstr8!("")`, `cstr16!()`, and `cstr16!("")` to create empty strings. I need this for #771 .
=> macros: allow to create empty cstr8/16 slices

CHANGELOG.md, uefi-raw/src/lib.rs, uefi-raw/src/table/mod.rs, uefi-raw/src/table/revision.rs, uefi/src/table/mod.rs
One API change: the struct's one field is now public. This fits better with uefi-raw, and doesn't cause any problems for the re-export in uefi.
=> Add Revision to uefi-raw and use it from uefi

uefi-raw/src/table/boot.rs, uefi-raw/src/table/mod.rs, uefi/src/table/boot.rs
=> Add Tpl to uefi-raw and use it from uefi

uefi-raw/src/lib.rs, uefi/src/data_types/mod.rs
=> Add PhysicalAddress/VirtualAddress to uefi-raw and use them from uefi

uefi-raw/src/table/boot.rs, uefi/src/table/boot.rs
=> Move various memory types to uefi-raw and re-export in uefi

CHANGELOG.md, uefi/src/proto/device_path/build.rs
Previously there was an implicit assumption that the `Vec` was empty; clear it to ensure this.
=> uefi: Clear the Vec in DevicePathBuilder::with_vec

CHANGELOG.md, uefi-test-runner/src/proto/device_path.rs, uefi/src/proto/device_path/mod.rs, uefi/src/table/boot.rs
This protocol is the same as `DevicePath`, but only available on image handles.
=> Add LoadedImageDevicePath protocol

uefi-test-runner/src/fs/mod.rs, uefi/src/fs/file_system/error.rs, uefi/src/fs/file_system/fs.rs, uefi/src/fs/file_system/mod.rs, uefi/src/fs/mod.rs, uefi/src/fs/path/mod.rs, uefi/src/fs/path/path.rs, uefi/src/fs/path/pathbuf.rs, uefi/src/result/error.rs
In #472 I added an initial version of a file-system error type. I did not really like it. Therefore, this MR adds a new type which adds much more context to errors. I think, the new abstraction is helpful - yet kind of feature-creep 😁 
What do you think?
Changelog update is not needed I think, as none of the fs-related code is published yet.
=> fs: add new error type

CHANGELOG.md, Cargo.lock, uefi-raw/Cargo.toml, uefi-raw/src/table/boot.rs, uefi/Cargo.toml, uefi/src/proto/console/serial.rs, uefi/src/proto/device_path/device_path_gen.rs, uefi/src/proto/media/file/mod.rs, uefi/src/proto/media/partition.rs, uefi/src/proto/network/pxe.rs, uefi/src/proto/network/snp.rs, uefi/src/proto/pi/mp.rs, uefi/src/proto/tcg/mod.rs, uefi/src/proto/tcg/v1.rs, uefi/src/proto/tcg/v2.rs, uefi/src/table/boot.rs, uefi/src/table/cfg.rs, uefi/src/table/runtime.rs, xtask/src/device_path/spec.rs
This updates bitflags from version 1 to version 2.
TL;DR: Now every struct needs to manually implement copy, clone, partial ord, etc.
=> deps: bump bitflags from 1.0 to 2.1

CHANGELOG.md, uefi-test-runner/src/fs/mod.rs, uefi/src/fs/dir_entry_iter.rs, uefi/src/fs/file_system/error.rs, uefi/src/fs/file_system/fs.rs, uefi/src/fs/mod.rs, uefi/src/fs/path/mod.rs, uefi/src/proto/media/file/info.rs
With this PR, the fs module is feature-complete and ready to be shipped.
=> fs: implement remove_dir_all

Cargo.lock, uefi-raw/Cargo.toml
We don't actually need this dep anymore since the uguid dep is providing the guid macro.
=> uefi-raw: Drop dep on uefi-macros

uefi-test-runner/Cargo.toml, uefi-test-runner/src/proto/debug.rs, xtask/src/cargo.rs, xtask/src/main.rs
Recent versions of edk2 no longer expose some protocols, so disable them on aarch64.
=> Disable some tests on aarch64

CHANGELOG.md, uefi-test-runner/src/fs/mod.rs, uefi/src/fs/file_system/error.rs, uefi/src/fs/file_system/fs.rs
It's already in the `fs` module, so the `FileSystem` part is redundent. Also, `IO` -> `Io` to match `IoError`.
=> uefi: Rename FileSystemIOErrorContext to IoErrorContext

Cargo.lock, uefi/Cargo.toml, uefi/src/fs/file_system/error.rs, uefi/src/fs/path/validation.rs
Add some custom Display impls for the various error types to provide more sentence-oriented messages. Drop `derive_more` since it's no longer used.
=> uefi: Improve fs error Display impls, drop derive_more

uefi-raw/src/table/boot.rs, uefi/src/table/boot.rs
Also changed the underlying type to `u32`. It doesn't really matter in this case; from the FFI perspective they are the same here. But `u32` is more common, so use that.
=> Move InterfaceType to uefi-raw

uefi-raw/Cargo.toml, uefi/Cargo.toml
Any of the 2.0/2.1/2.2/2.3 releases should be fine.
=> Relax bitflags dep version to 2.0.0

xtask/src/qemu.rs
The test file that is actually read in the tests is the one created in disk.rs, so drop this vestigial file.
=> xtask: Drop an unused test file

xtask/src/qemu.rs
On aarch64 it sits for a while on the initial screen and shows a progress bar to give the user time to enter the boot menu. We don't want to do that in our tests, so set the timeout to zero.
Even though we're skipping the boot menu, we have to also enable it here, otherwise the timeout value is ignored and a hardcoded platform default of 3 seconds is used.
=> xtask: Improve QEMU boot time

CHANGELOG.md, uefi-raw/src/table/mod.rs, uefi-raw/src/table/runtime.rs, uefi-services/src/lib.rs, uefi-test-runner/src/main.rs, uefi/src/table/runtime.rs, uefi/src/table/system.rs
These are direct moves with no changes to the types except for `ResetType`. That type has been changed to a newtype enum since it is used as an output parameter in `QueryCapsuleCapabilities`.
=> Move some runtime services types to uefi-raw

uefi-raw/src/lib.rs, uefi-raw/src/time.rs, uefi/src/table/runtime.rs
A few differences in the raw version:
* Moved to a new `time` module instead of `table::runtime`, because the type gets used in other places such as file metadata.
* Derived `Debug` impl instead of custom.
* Added a test for the `Display` impl.
* All fields public.
=> Add Time to uefi-raw and use it from uefi

uefi-raw/src/lib.rs
These definitions are just type aliases, unlike the more restrictive newtypes in the `uefi` package. In particular, the `uefi` package does not allow `Char16` to be created for surrogate pair characters. This is more restrictive than what UEFI actually specifies though; it says that `Char16` is _usually_ UCS-2, but particular uses may allow other encodings. So for `uefi-raw`, just treat `Char16` as numbers that can hold any `u16` value.
=> uefi-raw: Add Char8/Char16

CHANGELOG.md, uefi/src/proto/console/pointer/mod.rs
Tuples are not FFI safe, so replace them with arrays.
Demonstration of FFI warnings: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=7c6a699b754782072e09c34debf621ff
=> uefi: Fix use of tuples in pointer structs

.github/workflows/rust.yml, Cargo.lock, xtask/Cargo.toml, xtask/src/check_raw.rs, xtask/src/main.rs, xtask/src/opt.rs
Running `cargo xtask check-raw` validates various properties of the code in the `uefi-raw` package. For example, it checks that no Rust enums are used, that structs have an appropriate repr for FFI, that raw pointers are used instead of references, and many other things.
This is run in CI as part of the lint job.
=> xtask: Add check-raw

.github/workflows/rust.yml, Cargo.lock, Cargo.toml, xtask/Cargo.toml, xtask/src/qemu.rs
The code for trying to find where the OS has installed OVMF files has been removed. You can still pass your own OVMF files in via command-line or env vars, but by default the code will download prebuilt OVMF files from https://github.com/rust-osdev/ovmf-prebuilt.
=> Download OVMF files rather than relying on distro package

uefi/src/proto/media/file/mod.rs
Otherwise there is no way to consume the size hint returned by FileInfo::new().
=> Export FileInfoCreationError

uefi-raw/src/table/boot.rs, uefi/src/table/boot.rs
=> Move EventType to uefi-raw

uefi/src/data_types/mod.rs
There is value in checking whether two handles describe the same thing.
As EFI handles are just c_void, it's safe to do.
=> uefi: Derive Eq for Handle

CHANGELOG.md, uefi/src/proto/media/file/dir.rs, uefi/src/proto/media/file/regular.rs
Some UEFI implementations have a bug where large reads will incorrectly return an error, so read in 1 MiB chunks to avoid that.
Fixes https://github.com/rust-osdev/uefi-rs/issues/825
=> uefi: Change file reading to read in 1 MiB chunks

CHANGELOG.md, Cargo.lock, book/src/tutorial/app.md, template/Cargo.toml, uefi-macros/Cargo.toml, uefi-raw/Cargo.toml, uefi-services/Cargo.toml, uefi/Cargo.toml
Closes https://github.com/rust-osdev/uefi-rs/issues/839
=> Release uefi-raw-0.2.0, uefi-0.22.0, and uefi-services-0.19.0

.github/workflows/rust.yml, uefi-test-runner/src/proto/media.rs, uefi/src/proto/media/file/info.rs, uefi/src/proto/network/pxe.rs, uefi/src/proto/rng.rs, uefi/src/result/mod.rs
* Windows CI: there are issues with the May 2023 releases of QEMU, pin to a known-working version.
I cherry-picked in two fixes from https://github.com/rust-osdev/uefi-rs/pull/843 as well.
=> Fix various CI failures

uefi-test-runner/src/boot/misc.rs, uefi-test-runner/src/boot/mod.rs, uefi-test-runner/src/main.rs, uefi/src/table/boot.rs
Interestingly, this crashes on aarch64 but works on x86_64. Likely,
the x86_64 calling convention used still passes the Guid struct by
pointer, while the aarch64 passes it by value (or in an unexpected
registers) causing a crash.
This also adds a test case to verify this works correctly now.
Fixes: #842
=> uefi: Fix wrong install_configuration_table() signature

CHANGELOG.md, Cargo.lock, book/src/tutorial/app.md, template/Cargo.toml, uefi-macros/Cargo.toml, uefi-services/Cargo.toml, uefi/Cargo.toml
Closes https://github.com/rust-osdev/uefi-rs/issues/845
=> Release uefi-0.23.0 and uefi-services-0.20.0

CHANGELOG.md, uefi/src/fs/file_system/error.rs, uefi/src/proto/device_path/mod.rs
To enable a faster merge, this is a split from #827. It adds more convenience for device paths.
=> device_path: add more convenience (part 2)

uefi-test-runner/src/bin/shell_launcher.rs, xtask/src/qemu.rs
Add a new `shell_launcher` app that gets booted first when launching QEMU. This
app launches the shell app (which is built alongside the OVMF files). The shell
app's command line is set so that it will launch the test-runner app. Doing it
this way allows us to avoid the shell app's built-in five second startup delay.
By launching the test-runner inside the shell, in future commits we'll be able
to test UEFI shell protocols.
=> Make UEFI shell protocols testable

uefi-raw/src/protocol/device_path.rs, uefi-raw/src/protocol/mod.rs, uefi/src/proto/device_path/mod.rs, xtask/src/check_raw.rs
=> Add DevicePathProtocol to uefi-raw

CHANGELOG.md, uefi-test-runner/src/bin/shell_launcher.rs, uefi-test-runner/src/boot/mod.rs, uefi/src/data_types/strs.rs, uefi/src/proto/loaded_image.rs, uefi/src/table/boot.rs
A colleague of mine (ping @scholzp) was about to use the `load_image` function of UEFI boot services to load an image into memory. While working on a minimal example, he encountered an unintuitive bug. As a consequence, I thought it's useful to have a valid integration test for that function which others can use as template.
~~The test currently fails. What's wrong there with the chosen approach, @nicholasbishop ? UEFI fails with `NOT_FOUND` when `load_image` is executed.~~
=> Integration test for boot service function load_image

Cargo.toml, uefi-macros/Cargo.toml, uefi-raw/Cargo.toml, uefi-services/Cargo.toml, uefi/Cargo.toml, xtask/Cargo.toml
Cargo 1.64 added the ability to inherit package metadata from the root `Cargo.toml` file. Use that to deduplicate a bunch of fields.
=> cargo: Use `[workspace.package]` to deduplicate metadata

uefi/src/table/boot.rs
While `MaybeUninit` is useful to avoid unnecessarily initializing large buffers, it's not needed for small values like single pointers and integers.
For `Event`, `Handle`, and `ProtocolSearchKey`, which internally contain a `NonNull` pointer, we can wrap them in an `Option` and still have the same layout as a raw pointer. The initial value can then be `None` rather than `MaybeUninit`.
This has the nice side effect of removing a little bit of `unsafe` code.
=> uefi: Remove some uses of MaybeUninit in BootServices

.github/workflows/developer_productivity.yml
This is a speculative fix, I think the CI works for the `pull_request` trigger but fails on the `push` trigger. Seems like maybe a checkout action will fix it.
=> ci: Fix developer_productivity push error

uefi-raw/src/lib.rs, uefi-raw/src/table/boot.rs
=> uefi-raw: Add BootServices table

CHANGELOG.md, uefi/src/data_types/mod.rs
Allow round-tripping from raw pointer to `Event` and `Handle` via `from_ptr` and `as_ptr` methods.
=> uefi: Add raw pointer Event/Handle methods

.github/dependabot.yml, .github/workflows/book.yml, .github/workflows/developer_productivity.yml, .github/workflows/qa.yml, .github/workflows/rust.yml, shell.nix, xtask/src/main.rs, xtask/src/opt.rs, xtask/src/util.rs
This adds support for rustfmt, nixpkgs-fmt and yamlfmt via a new `cargo xtask fmt [--check]` command.
This needs #828 to be merged first.
=> xtask: add "cargo xtask fmt" (and formatting for nix and yml files)

CHANGELOG.md, uefi-test-runner/src/boot/mod.rs, uefi/src/table/boot.rs
Modify `ScopedProtocol` to check if the interface pointer is null. If it is, then `Deref` and `DerefMut` will now panic. They are also now marked `#[track_caller]` so that the panic location points to the caller.
Also added `get` and `get_mut` methods to get potentially-null interface data without panicking.
---
This is a minimal fix for the issue described in https://github.com/rust-osdev/uefi-rs/pull/859. I'm not sure if it's the best long-term fix, but I'm wary of doing anything too invasive until we have better Miri coverage of protocols.
=> uefi: Improve support for null protocol interfaces

xtask/src/check_raw.rs
This fixes a case where `check-raw` can incorrectly report an error as being the first line of a file.
=> xtask: Improve an error location in check-raw

uefi-raw/src/capsule.rs, uefi-raw/src/protocol/device_path.rs, uefi-raw/src/table/boot.rs, uefi-raw/src/table/header.rs, uefi-raw/src/table/revision.rs, uefi-raw/src/table/runtime.rs
This adds all possible derives to the important structs. Compile time overhead is negligible, but I'd like to refrain from limiting higher-level APIs in the lowest possible API.
For example, users should be able to create a HashSet of MemoryAttribute.
=> uefi-raw: derive all the things

CHANGELOG.md, uefi-test-runner/src/proto/device_path.rs, uefi/src/proto/device_path/mod.rs, xtask/src/qemu.rs
This MR adds convenient methods to transform device paths easier to text. This should make it easier for devs to work with device paths (through convenient debug output).
**for the first helper method (`.to_node_string_pairs`)**
**for the second helper method (`.to_string`)**
=> device_path: add more convenience (part 1)

uefi/src/table/system.rs
`slice::from_raw_parts` requires a valid pointer even if the slice length is zero, so avoid calling it if the configuration table pointer is null.
=> uefi: Check for null pointer in config_table

uefi/src/proto/console/text/output.rs
=> uefi: Use uefi_raw's `SimpleTextOutputProtocol` in `Output`

uefi/src/proto/device_path/mod.rs, uefi/src/table/runtime.rs
=> uefi: Fix warnings when compiling without the alloc feature

uefi-raw/src/protocol/console.rs
=> uefi-raw: Add `SimplePointerProtocol`

uefi/src/table/system.rs
=> uefi: Use uefi_raw's SystemTable to implement SystemTable

CHANGELOG.md, uefi-test-runner/src/boot/mod.rs, uefi/src/table/boot.rs
This reverts a small change from: https://github.com/rust-osdev/uefi-rs/pull/472
If using the library without the `alloc` feature enabled, `FileSystem` isn't available, but you might still want access to the image's file system via the underlying protocol.
The high-level API is still easily accessible via `FileSystem::new`.
=> Return a SimpleFileSystem from BootServices::get_image_file_system

uefi-raw/src/enums.rs, uefi-raw/src/table/boot.rs
=> uefi-raw: Derive Ord, PartialOrd, and Hash for all newtype enums

CHANGELOG.md, uefi/src/proto/console/pointer/mod.rs
=> uefi: Use uefi_raw's SimplePointerProtocol to implement Pointer

CHANGELOG.md, uefi-test-runner/src/proto/mod.rs, uefi/src/proto/shim/mod.rs
`x86` is what will be set on the `i686-unknown-uefi` target, not `i386`.
See also https://doc.rust-lang.org/reference/conditional-compilation.html.
=> Fix target_arch name: i386 -> x86

CHANGELOG.md, uefi-test-runner/src/fs/mod.rs, uefi/src/fs/file_system/fs.rs
Returning a bool allows both "exists" and "does not exist" to be success cases, while properly propagating unexpected errors.
This makes it line up with the std `try_exists` method: https://doc.rust-lang.org/std/path/struct.Path.html#method.try_exists
Also simplified the implementation to just call `open`, no need to get metadata since `open` already returns an error if the file doesn't exist.
=> uefi: Change try_exists to return FileSystemResult<bool>

CHANGELOG.md, uefi-test-runner/src/fs/mod.rs, uefi-test-runner/src/proto/media.rs, uefi/src/fs/file_system/fs.rs, xtask/src/disk.rs
Fixes https://github.com/rust-osdev/uefi-rs/issues/824
=> Rework `FileSystem::copy` to operate on 1MiB chunks

.github/workflows/developer_productivity.yml, .github/workflows/qa.yml, .github/workflows/rust.yml
This is required for using [Github's merge queue](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#configuring-continuous-integration-ci-workflows-for-merge-queues). However, note that this change does not actually enable merge queues (that's done through the branch protection settings).
=> ci: Add merge_group trigger

CHANGELOG.md, uefi-test-runner/src/boot/memory.rs, uefi/src/table/boot.rs
There's no good reason to the UEFI version of these functions over core Rust functions like `core::ptr::copy` and `core::ptr::write_bytes`. The safety requirements of the `core` functions are also better documented.
=> Drop `memmove` and `set_mem` from boot services

uefi-raw/src/protocol/memory_protection.rs, uefi-raw/src/protocol/mod.rs, uefi/src/proto/security/memory_protection.rs
=> Add raw memory protection protocol and use in `uefi`

uefi-raw/src/protocol/driver.rs, uefi-raw/src/protocol/mod.rs, uefi/src/proto/driver/component_name.rs
=> Add component name protocol to uefi-raw and use from uefi

CHANGELOG.md, uefi/src/data_types/chars.rs, uefi/src/data_types/owned_strs.rs, uefi/src/data_types/strs.rs, uefi/src/proto/device_path/build.rs, uefi/src/proto/driver/component_name.rs, uefi/src/proto/media/file/info.rs, uefi/src/proto/network/pxe.rs, uefi/src/proto/string/unicode_collation.rs, uefi/src/table/runtime.rs
Implemented `core::error::Error` and `core::fmt::Display` for all error types. Addresses https://github.com/rust-osdev/uefi-rs/issues/594
I'm fairly new to Rust so there might be some coding conventions I'm not familiar with. I tried to match the style of existing `Display` implementations. Any and all feedback is appreciated.
=> Implement core::error::Error for all error types

CHANGELOG.md, uefi-test-runner/src/main.rs, uefi/src/table/system.rs
~~Remove the reference type in iterator which results in incorrect lifetime for return value of MemoryMap::entries()~~
Change prototype of exit_boot_services()
For #914
=> Memory map change

CHANGELOG.md, uefi-raw/src/protocol/mod.rs, uefi-raw/src/protocol/shell_params.rs, uefi-test-runner/examples/shell_params.rs, uefi-test-runner/src/bin/shell_launcher.rs, uefi-test-runner/src/proto/mod.rs, uefi-test-runner/src/proto/shell_params.rs, uefi/src/proto/mod.rs, uefi/src/proto/shell_params.rs
Useful to get the shell arguments for a commandline application.
Running example application on UEFI shell:
```
Shell> fs0:EFI\Boot\BootX64.efi
Args: ["FS0:\\EFI\Boot\BootX64.efi"]
Num args: 1
Shell> fs0:EFI\Boot\BootX64.efi foo bar
Args: ["FS0:\\EFI\Boot\BootX64.efi", "foo", "bar"]
Num args: 3
First real arg: 'foo'
Shell> 
```
=> Add ShellParams protocol

xtask/src/pipe.rs
`clippy::needless_return_with_question_mark` is incorrectly firing here in 1.73.
=> xtask: Temporarily disable a false-positive clippy lint

CHANGELOG.md, uefi-test-runner/src/proto/console/gop.rs, uefi/src/proto/console/gop.rs
This fixes the memory leak reported in #968. This comes with a breaking change.
=> uefi/gop: fix memory leak

CHANGELOG.md, uefi/src/table/boot.rs
In developing a bootloader for my microkernel, I have have found that being able to index the given `MemoryMap` would reduce some complexity.
=> Allow indexing of `MemoryMap`.

uefi-services/src/lib.rs
As mentioned in https://github.com/rust-osdev/uefi-rs/issues/917 If the app built with uefi-services exits before ExitBootServices, UEFI will call `UnloadImage` on it. Then the callback function is not in memory anymore and when ExitBootServices runs, invalid memory is accessed.
QEMU will crash like this when the Linux EFISTUB calls ExitBootServices:
```
!!!! X64 Exception Type - 06(#UD - Invalid Opcode)  CPU Apic ID - 00000000 !!!!
RIP  - 000000003E13F018, CS  - 0000000000000038, RFLAGS - 0000000000210246
RAX  - 0000000000000000, RCX - 000000003E191E98, RDX - 0000000000000000
RBX  - 0000000000000004, RSP - 000000003FF0FD08, RBP - 000000003FF28740
RSI  - 000000003E167518, RDI - 000000003FF6A5E0
R8   - 000000003FF27140, R9  - 000000003F4807A0, R10 - 0000000000000001
R11  - …
```
=> uefi-services: Return event in init

uefi/src/fs/uefi_types.rs
This alias is neither used internally nor publicly exposed.
=> Remove unused UefiRegularFileHandle type alias

CHANGELOG.md, uefi-services/src/lib.rs
The `SystemTable` type is already essentially a wrapper around a pointer, so there's no need to wrap this return value in another pointer via `NonNull`.
=> uefi-services: Remove NonNull wrapper from system_table

CHANGELOG.md, uefi-test-runner/src/boot/memory.rs, uefi/src/proto/console/gop.rs, uefi/src/proto/device_path/text.rs, uefi/src/table/boot.rs
These functions can easily be used to trigger UB from safe code by passing in an address to memory that is still in use. Fix by marking them `unsafe`.
=> Mark free_pages and free_pool as unsafe

uefi/src/table/boot.rs
This aligns with how the std uefi target works:
https://github.com/rust-lang/rust/blob/f654229c27267334023a22233795b88b75fc340e/library/std/src/os/uefi/env.rs#L9
And also avoids some unsafe; a static atomic be written without being `static mut`, and reads and writes are safe operations.
=> uefi: Change IMAGE_HANDLE to an atomic pointer

CHANGELOG.md, uefi-services/src/lib.rs, uefi/src/table/system.rs
This aligns with how the std uefi target works:
https://github.com/rust-lang/rust/blob/f654229c27267334023a22233795b88b75fc340e/library/std/src/os/uefi/env.rs#L8
And also avoids some unsafe; a static atomic be written without being `static mut`, and reads and writes are safe operations.
Also includes some related cleanups in uefi-services, and the addition of `SystemTable::as_ptr`.
=> uefi-services: Change SYSTEM_TABLE to an atomic pointer

CHANGELOG.md, uefi-services/src/lib.rs, uefi/src/logger.rs
Using a `Logger` no longer requires making it mutable, and it now provides a `const` `new` function. This allows creating a `static` `Logger`, rather than a `static mut` `Option<Logger>`, which allows for less `unsafe`.
Update the `LOGGER` in uefi-services accordingly.
=> Change Logger to use an atomic pointer internally

CHANGELOG.md, uefi-services/src/lib.rs, uefi/src/allocator.rs
This completes the transition away from any uses of `static mut`.
=> uefi: Use atomics instead of `static mut` in allocator

CHANGELOG.md, uefi-raw/src/table/boot.rs, uefi/src/table/boot.rs
A protocol's interface may mutate itself, but the void pointer passed to the `{install,reinstall,uninstall}_protocol_interface` functions is opaque to the firmware, so there's no need for it to be a mut pointer.
Note that from a Rust safety perspective there's no difference here -- mut and const pointers are interchangeable.
https://github.com/rust-osdev/uefi-rs/issues/970
=> Use const interface pointers in protocol management functions

CHANGELOG.md, uefi-raw/src/protocol/console.rs
=> uefi-raw: Add AbsolutePointerProtocol

CHANGELOG.md, uefi-raw/src/protocol/file_system.rs, uefi-raw/src/protocol/mod.rs, uefi/src/proto/media/file/info.rs, uefi/src/proto/media/file/mod.rs, uefi/src/proto/media/file/regular.rs, uefi/src/proto/media/fs.rs
=> Add SimpleFileSystemProtocol & file types to `uefi-raw`, use those types from `uefi`

uefi-raw/api_guidelines.md
Some initial guildelines for the uefi-raw crate. Probably missing some stuff but hopefully this is a good start.
=> uefi-raw: Add API guidelines

PUBLISHING.md, uefi-macros/Cargo.toml
Using a path avoids having to update the `uefi-macros` dep on `uefi` after releasing a new version of `uefi`, slightly simplifying our release process.
Prior to cargo 1.40 there was no choice but to have a version on dev-dependencies. That changed with
https://github.com/rust-lang/cargo/pull/7333, and now you can publish a crate with a path-only dev dependency.
=> uefi-macros: Change uefi dev-dependency from version to path

CHANGELOG.md, uefi-macros/CHANGELOG.md, uefi-raw/CHANGELOG.md, uefi-services/CHANGELOG.md, uefi/CHANGELOG.md
I've found that having a single changelog for four different packages can get a bit unwieldy. ("Do I have this entry under the right package? Is my `###` header at the right level? Did I resolve these merge conflicts correctly?") Split up the big changelog into one for each package, and change the top-level one to link to the others.
=> Add per-package changelogs

uefi-test-runner/src/boot/misc.rs
If a protocol is installed with a data pointer, you have to pass that same pointer in when uninstalling the interface. Update the test runner to demonstrate how to do this by opening the protocol and converting the ScopedProtocol to a raw pointer.
https://github.com/rust-osdev/uefi-rs/issues/921
=> test-runner: Improve uninstall_protocol_interface example

.github/workflows/release.yml, Cargo.lock, PUBLISHING.md, xtask/Cargo.toml, xtask/src/cargo.rs, xtask/src/main.rs, xtask/src/opt.rs, xtask/src/release.rs, xtask/src/util.rs
This new workflow will simplify our release process and make it more reviewable:
1. Create a branch that updates the versions of all packages you want to release. This PR should include all related changes such as updating the versions in dependent crates and updating the changelog.
2. Create a PR of that branch. The subject of the PR must start with `release:`, the rest of the message is arbitrary.
3. Once the PR is approved and merged, a Github Actions workflow will take care of creating git tags and publishing to crates.io.
Since all the changes are now part of one PR that is created before the release actually occurs, we can now review our release changes just like any other PR. And with the release happening in a github action, it avoids a lot of easy-to-make mistakes such as …
=> Release via Github Actions workflow

uefi-raw/CHANGELOG.md, uefi-raw/src/table/boot.rs, xtask/src/check_raw.rs
The existing comment there said the unstable `c-variadic` feature was required, but that was incorrect. While defining c-variadic functions is unstable in Rust, c-variadic function pointers are stable (calling c-variadics is also stable).
We still can't quite define these two function pointers correctly because they should be `extern "efiapi"`, which requires the unstable `extended_varargs_abi_support` feature. However, as long as your code is compiled for a UEFI target, `extern "C"` gives you the correct ABI. Since these function pointers are `unsafe` to call, we can expose them in the raw interface and leave it up to the caller to ensure they are used correctly.
=> uefi-raw: Fill in [un]install_multiple_protocol_interfaces pointers

PUBLISHING.md, book/src/tutorial/app.md
Rather than showing exact dependencies in `Cargo.toml`, use the `cargo add` command. That removes a small step of the release process.
=> book: Use `cargo add` command

PUBLISHING.md
**UPDATE** According to the latest discussions and developments, I'm updating the guide again.
[rendered](https://github.com/rust-osdev/uefi-rs/blob/9d2c6ba55ee5f5b3103880e3fba086ed2ffe9d69/PUBLISHING.md)
<details>
<summary>Old Version</summary>
After publishing `uefi-raw` and `uefi`, I noticed that the `PUBLISHING.md` was a bit cumbersome to follow. I simplified things in a way where I think it is more useful and consise for everybody. What do you think?
For example: 
I removed some (from my perspective) obvious paragraphs. For example if `uefi-raw` has a 
publicly exported breaking change (such as a new MSRV), then bumping it in `uefi` is of
course a breaking change too. I don't think I need to remind ourselves for such "obvious" stuff. Do you agree?
I'm open for your opinions! …
=> doc: update PUBLISHING.md

.github/workflows/developer_productivity.yml, nix/nixpkgs.nix, nix/rust-toolchain.nix, nix/sources.json, rust-toolchain.toml, shell.nix
This changes the rust-toolchain from `rustup` to `rust-bin.fromRustupToolchainFile` coming from https://github.com/oxalica/rust-overlay. This supersedes #994.
TL;DR: `nix-shell --pure --run "rustc --version"` is now `1.73`.
=> nix: update rust-toolchain in shell

uefi-test-runner/src/proto/device_path.rs, uefi/CHANGELOG.md, uefi/src/proto/device_path/mod.rs
Instead of returning `None` for out of memory, add a new variant to `DevicePathToTextError` and return that. That allows the return type to be a plain `Result` rather than `Result<Option>`, simplifying usage.
=> Simplify DevicePath to_string return type

xtask/src/check_raw.rs
The checks are mostly the same as for structs, so refactor a bit to share code between the checks.
=> xtask: Allow unions in uefi-raw

uefi-raw/CHANGELOG.md, uefi-raw/src/lib.rs
These are defined in "Common UEFI Data Types" part of the spec, so put them in the root of the crate.
=> uefi-raw: Add Ipv4Address, Ipv6Address, and MacAddress types

.github/renovate.json
Support for this strategy (with cargo) was added recently:
https://github.com/renovatebot/renovate/issues/22820. It seems that at the same time the behavior of the "replace" strategy changed, causing PRs to be opened with unnecessary changes to Cargo.toml.
=> renovate: Change stategy to update-lockfile

xtask/src/qemu.rs
Also add a QEMU arg that will allow older version of QEMU to boot with recent releases of edk2.
=> xtask: Upgrade OVMF prebuilt

uefi-test-runner/src/main.rs, uefi-test-runner/src/proto/console/serial.rs, uefi/CHANGELOG.md, uefi/src/proto/device_path/device_path_gen.rs, xtask/src/device_path/spec.rs, xtask/src/qemu.rs
My [recent PR](https://github.com/rust-osdev/uefi-rs/pull/1027) to upgrade the edk2 prebuilts had a bug I didn't notice: the logging output gets cut off after the serial protocol is opened in exclusive mode.
This was caused by https://github.com/tianocore/edk2/commit/cf6a0a52b07195ba278e48b89cfb7ddbad332ab1. Fix it by specifying the appropriate terminal type when calling `connect_controller`.
Since this bug has happened in various forms a couple times, also update the tests to catch it: check for a special log message right before exiting boot services, and fail the tests if that message is not received.
=> Fix logger connection after opening serial protocol

uefi-raw/CHANGELOG.md, uefi-raw/src/lib.rs
Also derive `Default` on the previously-added address types.
=> uefi-raw: Add `IpAddress` type

uefi-raw/README.md
Removed the stray period character at the end of the link which prevented it from working
=> Fix broken UEFI spec link in uefi-raw README.md

uefi-raw/CHANGELOG.md, uefi-raw/src/protocol/media.rs, uefi-raw/src/protocol/mod.rs
Extracting the uefi-raw part of https://github.com/rust-osdev/uefi-rs/pull/945, and adding `LoadFileProtocol` as well.
=> uefi-raw: Add LoadFileProtocol and LoadFile2Protocol

uefi-raw/CHANGELOG.md, uefi-raw/src/firmware_storage.rs, uefi-raw/src/lib.rs
This contains firmware storage types from the UEFI Platform Initialization Specification. The firmware volume format is used, for example, for `OVMF_VARS.fd`.
=> uefi_raw: Add firmware_storage module

uefi-services/CHANGELOG.md, uefi-services/Cargo.toml
Use `dep:` for the optional `qemu-exit` dependency. This avoids implicitly adding a useless `qemu-exit` feature to the crate.
Doc: https://doc.rust-lang.org/cargo/reference/features.html#optional-dependencies
=> uefi-services: Use "dep:" syntax

Cargo.lock, template/Cargo.toml, uefi-raw/CHANGELOG.md, uefi-raw/Cargo.toml, uefi-services/Cargo.toml, uefi/CHANGELOG.md, uefi/Cargo.toml
Been a little while since we last released, and we've accumulated a few additions and fixes. This also serves as a test that the recent [auto-release](https://github.com/rust-osdev/uefi-rs/pull/1068) changes didn't break anything.
=> release: uefi-raw-0.5.1, uefi-0.27.0, uefi-services-0.24.0

uefi-services/src/lib.rs, uefi-test-runner/examples/shell_params.rs, uefi-test-runner/examples/sierpinski.rs, uefi-test-runner/src/bin/shell_launcher.rs, uefi-test-runner/src/boot/memory.rs, uefi-test-runner/src/proto/console/gop.rs, uefi-test-runner/src/proto/device_path.rs, uefi-test-runner/src/proto/driver.rs, uefi-test-runner/src/proto/loaded_image.rs, uefi-test-runner/src/runtime/vars.rs, uefi/src/data_types/strs.rs, uefi/src/fs/file_system/fs.rs, uefi/src/proto/console/serial.rs, uefi/src/proto/pi/mp.rs, uefi/src/table/boot.rs
=> Fix some new lints/warnings

uefi-raw/CHANGELOG.md, uefi-raw/src/protocol/misc.rs, uefi-raw/src/protocol/mod.rs, uefi/CHANGELOG.md, uefi/src/proto/misc.rs, uefi/src/proto/mod.rs
Closes https://github.com/rust-osdev/uefi-rs/issues/1084
=> Add timestamp protocol

uefi/src/data_types/chars.rs, uefi/src/data_types/mod.rs, uefi/src/data_types/strs.rs
Over time the standard library has introduced more specific conversion methods which allow the more powerful `as` cast to be avoided.
=> Replace some `as` casts

uefi/CHANGELOG.md, uefi/src/data_types/mod.rs
=> uefi: Add more derives for Handle and Event

.editorconfig, .github/workflows/qa.yml, .typos.toml, nix/sources.json
- update niv/nix dependencies
- update typos + apply fixes
=> misc: nix/niv updates and typo updates

uefi/src/fs/file_system/fs.rs, uefi/src/fs/mod.rs
Improve documentation of `uefi::fs` module.
=> doc: update fs documentation

.github/workflows/rust.yml, uefi/src/helpers/mod.rs, uefi/src/table/boot.rs
Set `RUSTFLAGS="-D warnings"` for all jobs so that errors are treated as warnings for build/test.
=> Fix some warnings, and ensure CI catches them in the future

uefi/src/data_types/mod.rs, uefi/src/data_types/strs.rs, uefi/src/fs/dir_entry_iter.rs, uefi/src/fs/mod.rs, uefi/src/fs/path/mod.rs, uefi/src/fs/path/path.rs, uefi/src/fs/path/pathbuf.rs, uefi/src/fs/path/validation.rs, uefi/src/helpers/mod.rs, uefi/src/helpers/panic_handler.rs, uefi/src/lib.rs, uefi/src/prelude.rs, uefi/src/proto/console/text/mod.rs, uefi/src/proto/debug/mod.rs, uefi/src/proto/media/file/mod.rs, uefi/src/proto/network/snp.rs, uefi/src/result/mod.rs, uefi/src/table/boot.rs, uefi/src/table/mod.rs
* All of the macros from uefi_macros are imported into the uefi crate. Consistently use those imports everywhere, rather than reimporting from `uefi_macros`.
* Consistently import items in the `uefi` crate with `crate::` instead of `uefi::`.
* Clean up unnecessary uses of `self::`.
Should be no change to the public API from this.
=> Minor import/export cleanups

uefi-macros/CHANGELOG.md, uefi-macros/src/lib.rs, uefi/src/data_types/mod.rs, uefi/src/data_types/strs.rs, uefi/src/lib.rs, uefi/src/macros.rs
The implementation is similar to `cstr16`, except that since we don't have the equivalent of the `ucs2` crate for latin-1, the internals are implemented directly in this crate.
=> Replace `cstr8!` with a declarative macro

uefi/src/proto/debug/exception.rs
Nightly now checks if target_arch is correct, which revealed a spot where we used `riscv`, which isn't valid. Switched to test both riscv32 and riscv64.
=> Fix risc target_arch cfg

uefi-raw/CHANGELOG.md, uefi-raw/src/table/runtime.rs
Per section 8.5.3.4 of the latest UEFI spec [1], `QueryCapsuleCapabilities` uses a uint64 for MaximumCapsuleSize, not a usize.
[1]:https://uefi.org/sites/default/files/resources/UEFI_Spec_2_10_Aug29.pdf
=> Match MaximumCapsuleSize to UEFI spec

uefi/CHANGELOG.md, uefi/src/table/runtime.rs
This allows passing capsules [1] to firmware.
Firmware updates cannot be explicitly tested as it is not supported by OVMF.
[1]:https://uefi.org/specs/UEFI/2.9_A/08_Services_Runtime_Services.html#update-capsule
=> Add RuntimeServices::update_capsule

uefi-raw/CHANGELOG.md, uefi-raw/src/table/runtime.rs, uefi/CHANGELOG.md, uefi/src/table/runtime.rs
This adds the ability to query whether an update capsule is supported by update_capsule or not.
=> Add RuntimeServices::query_capsule_capabilities

book/src/tutorial/app.md
It took me most of an evening to figure this out, so I thought I'd share it!
=> Note about feature flags for uefi book

uefi-raw/src/table/boot.rs, uefi/src/table/boot.rs
Clarify the confusion I already described in [our zulip](https://rust-osdev.zulipchat.com/#narrow/stream/426438-uefi-rs/topic/general/near/440124507)
=> mem: clarify confusion around MemoryDescriptor

uefi-macros/CHANGELOG.md, uefi-macros/src/lib.rs, uefi-test-runner/src/main.rs, uefi/CHANGELOG.md, uefi/src/table/mod.rs, uefi/src/table/system.rs
This is a much simpler version than https://github.com/rust-osdev/uefi-rs/pull/905. Just the bare minimum: add functions to set and get the global system table, set the global system table in the `entry` macro, and also make `exit_boot_services` unsafe.
(I would still like to go in the direction of https://github.com/rust-osdev/uefi-rs/pull/905, but I think we should move a little incrementally so that we have a better chance of catching mistakes along the way.)
https://github.com/rust-osdev/uefi-rs/issues/893
=> Add basic API for a global system table

uefi-test-runner/src/boot/misc.rs, uefi/CHANGELOG.md, uefi/src/allocator.rs, uefi/src/table/boot.rs, uefi/src/table/system.rs
This is safe as each null pointer (=failed allocation) is already returned as non-successful status code by UEFI.
=> uefi: BootServices::allocate_pool now returns NonZero<u8> instead of *mut u8

uefi-macros/tests/ui/fail/entry_bad_return_type.stderr, xtask/src/cargo.rs
A difference in behavior between CI and local testing was observed for the entry_bad_return_type test. This is due to the way trybuild sets the `--verbose` flag, which is overwritten if RUSTFLAGS is set (as it always is for our CI jobs). Add code in xtask to ensure that `--verbose` still gets set correctly.
Also update entry_bad_return_type.stderr to match the expected current output.
=> Fix uefi-macros trybuild test

uefi/src/lib.rs
This should fix the CI errors.
This feature has been stabilized in latest nightly, so no need to enable it. All the uses of it (`impl core::error::Error for for ...`) are still gated by the `unstable` feature, so there's no change for users on the stable channel.
=> uefi: Stop enabling `error_in_core` feature

uefi/CHANGELOG.md, uefi/src/proto/device_path/mod.rs
Allows for making a `DevicePathHeader` from a byte splice, used primarily to verify whether the byte splice can also contain `DevicePathHeader.length` bytes.
=> uefi: Add TryFrom u8 slice to DevicePathHeader 

uefi-test-runner/src/main.rs, uefi-test-runner/src/proto/console/gop.rs, uefi-test-runner/src/proto/console/mod.rs, uefi-test-runner/src/proto/device_path.rs, uefi-test-runner/src/proto/loaded_image.rs, uefi-test-runner/src/proto/mod.rs
Rather than passing the image handle around in function args, just use the global image handle.
=> test-runner: Consistently use global image handle

uefi/CHANGELOG.md, uefi/src/proto/device_path/mod.rs
Adds the capability to convert a byte slice to a DevicePathNode. This will be used to convert a byte slice to a DevicePath in a followup PR, which allows easier interaction with the data returned from UEFI variable services.
=> uefi: Add TryFrom u8 slice to DevicePathNode

uefi/CHANGELOG.md, uefi/src/helpers/mod.rs, uefi/src/helpers/panic_handler.rs, uefi/src/helpers/println.rs, uefi/src/table/mod.rs
Now that `uefi::table` has a pointer to the system table, drop the pointer from `uefi::helpers` and deprecate `helpers::system_table`.
Note this also includes the change from https://github.com/rust-osdev/uefi-rs/pull/1175/ to make `system_table_boot`/`system_table_runtime` return `Option` instead of panicking.
=> Clean up duplicate global system table pointer in `uefi::helpers`

uefi/CHANGELOG.md, uefi/src/proto/device_path/mod.rs
Adds the capability to convert a byte slice to a DevicePath. This allows for users to easily get a DevicePath from the data returned by UEFI variables, etc.
=> uefi: Add TryFrom u8 slice to DevicePath

uefi/CHANGELOG.md, uefi/src/table/runtime.rs
Users of the UpdateCapsule runtime service need to create a `CapsuleFlags` to create a `CapsuleHeader`.
=> uefi: re-export CapsuleFlags

.github/workflows/rust.yml
The dead_code lint on nightly is currently incorrectly flagging a lot of structs as unused.
https://github.com/rust-osdev/uefi-rs/issues/1205
=> ci: Temporarily turn off warnings-as-errors for nightly CI jobs

uefi/src/table/runtime.rs
=> uefi: use UNSPECIFIED_TIMEZONE instead of magic number

uefi/CHANGELOG.md, uefi/src/table/runtime.rs
When returning a TimeError, it'd be helpful to specify to the user which field is invalid so that it can be handled accordingly, or at least communicated. This change does this by reimplementing TimeError as an enum instead of a struct, allowing for specification and more verbose error display.
=> uefi: Make TimeError more descriptive

uefi-raw/CHANGELOG.md, uefi/CHANGELOG.md
Depends on https://github.com/rust-osdev/uefi-rs/pull/1186
`uefi` 0.28 was released from commit https://github.com/rust-osdev/uefi-rs/commit/255359abeabaf26ab0c8dac2f889fa65bc38fc8e. The tree for that commit
doesn't contain `ResetNotificationProtocol`, even though the changelog
says it does. `ResetNotificationProtocol` was added in commit https://github.com/rust-osdev/uefi-rs/commit/04be50fe34f6f919aa647573d43c112363337091,
which was merged in commit `0c533bd` - both occurring after 0.28 was
released.
This commit fixes those issues, and bumps the unreleased crate versions
so that I can depend on them before this commit is released.
=> Fix versions

uefi-test-runner/examples/sierpinski.rs
When only one pixel needs to be updated, there is no need to transfer the entire buffer. After drawing the background in advance, you only need to update each pixel that requires it.
=> uefi-test-runner: speed up ploting of sierpinski triangle by updating changed pixel only

nix/sources.json
Update nixpkgs from branch nixos-23.11 to nixos-24.05.
=> nix/niv: update nixpkgs to nixos-24.05

uefi-services/README.md, uefi-test-runner/src/boot/memory.rs, uefi/CHANGELOG.md, uefi/src/lib.rs, uefi/src/mem.rs, uefi/src/table/boot.rs, uefi/src/table/system.rs
Follow-up of #1174 that improves the MemoryMap abstraction.
- rename `entry_size` -> `desc_size`
- better documentation
- unify usage of common constructor with sane assertions
- **removed lifetime/reference, type now owns the memory (which makes much more sense IMHO)**
This is an attempt to simplify the overall complex handling of obtaining the UEFI memory
map. We have the following pre-requisites and use-cases all to keep in mind when
designing the functions and associated helper types:
- the memory map itself needs memory; typically on the UEFI heap
- acquiring that memory and storing the memory map inside it are two distinct steps
- the memory map is not just a slice of [MemoryDescriptor] (desc_size is bigger than
size_of)
- the required map size can be obtained by a call to a boot …
=> memory map: improvements to fight pitfalls (MemoryMap now owns the memory)

uefi/CHANGELOG.md, uefi/src/proto/console/gop.rs
=> uefi: simplify usage of Mode

template/Cargo.toml
The template failed to build when built with cmds below:
```bash
cd template
cargo build --target x86_64-unknown-uefi
```
We'll get error:
```bash
error: no global memory allocator found but one is required; link to std or add `#[global_allocator]` to a static item that implements the GlobalAlloc trait
error: `#[panic_handler]` function required, but not found
error: could not compile `uefi_app` (bin "uefi_app") due to 2 previous errors
```
As the Rust UEFI Book shown, the template succeeds to build with uefi-rs feature `panic_handler` enabled.
=> template: fix build failure

uefi/CHANGELOG.md, uefi/src/table/runtime.rs
I am implementing a UEFI application which needs to convert part of a byte splice (returned by the variable runtime service) into a `Time`. I wanted to see if it was worth upstreaming, in case others might also need of it.
=> uefi: Add TryFrom<&[u8]> for Time

Cargo.lock, book/src/tutorial/app.md, template/Cargo.toml, uefi-macros/CHANGELOG.md, uefi-macros/Cargo.toml, uefi-raw/CHANGELOG.md, uefi-raw/Cargo.toml, uefi/CHANGELOG.md, uefi/Cargo.toml
Last release was in April, we've accumulated a good number of changes since then.
=> release: uefi-macros-0.14.0, uefi-raw-0.6.0, uefi-0.29.0

.github/workflows/book.yml, book/head_redirect.html
For https://github.com/rust-osdev/uefi-rs/issues/1222
* The book job now triggers on tag pushes in addition to pushes to `main`
* The job builds the book from the highest release tag instead of `main`
* The book output is added to the root of the `gh-pages` branch rather than a subdirectory
* Removed the now-unused redirect-to-HEAD html file
Did some testing in a fork to make sure the changes work as expected.
Note that the old `HEAD` folder will still be present on the `gh-pages` branch after running this, so it won't immediately break any links.
=> book: Publish the latest release instead of main

template/src/main.rs, uefi-test-runner/examples/hello_world.rs, uefi-test-runner/examples/loaded_image.rs, uefi-test-runner/examples/shell_params.rs, uefi-test-runner/examples/sierpinski.rs, uefi-test-runner/examples/timestamp.rs, uefi-test-runner/src/bin/shell_launcher.rs, uefi-test-runner/src/main.rs, uefi/CHANGELOG.md, uefi/src/helpers/mod.rs
Use the global system table pointer instead.
Cleanup for https://github.com/rust-osdev/uefi-rs/issues/893
=> Drop SystemTable arg from uefi::helpers::init

uefi-macros/CHANGELOG.md, uefi-macros/src/lib.rs, uefi-macros/tests/ui/pass/entry_no_args.rs
For https://github.com/rust-osdev/uefi-rs/issues/893
=> uefi-macros: Allow zero-param function in the entry macro

uefi/CHANGELOG.md, uefi/src/table/boot.rs
Due to the rules of lifetime elision
(https://doc.rust-lang.org/reference/lifetime-elision.html), the lifetime of the `SearchType` returned from `register_protocol_notify` was infered to be the lifetime of `Self`. The correct lifetime is the `protocol` reference.
In practice this isn't likely to matter much to users, but I noticed it due to a compilation error when working on https://github.com/rust-osdev/uefi-rs/issues/893
=> uefi: Fix return value lifetime for register_protocol_notify

uefi/src/helpers/println.rs
When one accidentally call println! after exit_boot_services, one now at least gets some more debugging info why the machine suddenly reboots.
Specifically, this prints now info to `integration-test-debugcon.log` in such a case.
=> uefi: _print more failsafe

uefi-test-runner/src/boot/memory.rs, uefi-test-runner/src/main.rs, uefi/CHANGELOG.md, uefi/src/table/boot.rs, uefi/src/table/system.rs
In #1175 we lost the flexibility to use the memory map on any buffer. However, if you write a kernel and get the raw memory map from your bootloader, one has to parse the memory map from this raw memory. To solve this (leveraging the `uefi` crate), I introduced: 
- the traits `MemoryMap` and `MemoryMapMut`, where `MemoryMapMut` extends `MemoryMap`
- the types `MemoryMapRef`, `MemoryMapRefMut`, and `MemoryMapOwned`, where the latter two implement `MemoryMapMut` 
This helps to have a common API for all these use-cases. However, there are the
following open questions:
- There is still code repetition. Especially for the implementations of `Index` and `IndexMut` which I have to provide 3 times. Any idea for improvement? Just use a macro?
- I didn't manage to make the traits directly dependent …
=> mem: introduce traits MemoryMap and MemoryMapMut

uefi-test-runner/src/main.rs, uefi/CHANGELOG.md, uefi/src/lib.rs, uefi/src/system.rs, uefi/src/table/cfg.rs, uefi/src/table/mod.rs
This is similar to existing methods of `SystemTable`, but as freestanding functions that use the global system table pointer.
Splitting this out from https://github.com/rust-osdev/uefi-rs/pull/905, the `system` module provides a good starting point to get a sense of what `uefi::{system,boot,runtime}` will look like.
https://github.com/rust-osdev/uefi-rs/issues/893
=> Add uefi::system module

uefi-test-runner/src/proto/tcg.rs, uefi/CHANGELOG.md, uefi/src/proto/tcg/v1.rs, uefi/src/proto/tcg/v2.rs
Fixes https://github.com/rust-osdev/uefi-rs/issues/780
The initial commits are modifying the structs so that the `make_boxed` utility can be used.
=> Add PcrEvent::new_in_box/PcrEventInputs::new_in_box

uefi-test-runner/src/runtime/mod.rs, uefi/CHANGELOG.md, uefi/src/lib.rs, uefi/src/runtime.rs
The initial version here just provides functions for getting and setting the system time. Later PRs will add functions to get/set variables, handle update capsules, etc.
Also added some tests for the new code in the test runner (note that there were no existing tests for the time-related functions of `RuntimeServices`).
=> Add uefi::runtime module

uefi-test-runner/src/runtime/vars.rs, uefi/src/data_types/mod.rs, uefi/src/runtime.rs
The new version of `get_variable` returns the required size in the error data if the input buffer is too small. This allows `get_variable_boxed` to use `make_boxed`, and also makes `get_variable_size` unnecessary.
Also:
* Added more info about errors to the docstrings.
* impl `Align` for `[u8]` to allow `make_boxed` to work here.
(Note: `variable_keys` function to come in a later PR.)
=> runtime: Add freestanding functions to get/set/delete UEFI variables

uefi/src/table/boot.rs
Gating this on `cfg(not(test))` isn't necessary; during unit tests `system_table_boot()` will return `None` and so the drop won't do anything anyway.
Also fix a typo, excited -> exited.
=> boot: Always impl Drop for MemoryMapBackingMemory

uefi-test-runner/src/boot/memory.rs
The loop makes the test runner noticably slower to run. That doesn't matter so much for CI, but is a little inconvenient for local testing.
The drop impl for `MemoryMapBackingMemory` is no longer conditional, so it's not particularly different from the many other types that internally allocate.
=> test-runner: Drop the memory map OOM loop

uefi-raw/CHANGELOG.md, uefi-raw/src/table/boot.rs
Unaccepted memory was added in UEFI 2.9. Also add the max constant and two range constants, and tweaked a few docs.
=> uefi-raw: Add more MemoryType constants

uefi-test-runner/src/runtime/vars.rs, uefi/CHANGELOG.md, uefi/src/runtime.rs, uefi/src/table/runtime.rs
The interface is slightly different than in `uefi/src/table/runtime.rs`, where we just have a function to get all keys at once in a `Vec<VariableKey>`.
For the new implementation, two interfaces are provided:
`get_next_variable_key` is a low-level interface that does not require the `alloc` feature; it's a simple wrapper around `GetNextVariableName`.
`variable_keys` is a high-level interface that returns an iterator. (Following the conventions of Rust's std lib, the iterator type is named `VariableKeys`.) This requires `alloc`.
Also:
* Add standard derives for `VariableKey` (needed eq for the tests)
=> Add variable key functions to `uefi::runtime`

uefi/src/runtime.rs
No tests for these since QEMU+OVMF doesn't support firmware update testing currently.
=> Add capsule update functions to `uefi::runtime`

uefi-test-runner/src/boot/memory.rs, uefi/CHANGELOG.md, uefi/src/boot.rs, uefi/src/lib.rs
The initial version contains `allocate_pages/allocate_pool` and the corresponding `free` functions.
=> Add uefi::boot module

uefi/src/runtime.rs
No test added for this since our test runner isn't really set up for testing multiple resets.
=> runtime: Add uefi::runtime::reset

uefi/src/boot.rs, uefi/src/table/boot.rs
The BootServices methods just pass through to the uefi::boot version now.
=> Move the global image handle to uefi::boot

uefi-test-runner/src/boot/mod.rs, uefi/src/boot.rs, uefi/src/table/boot.rs
=> Add `boot::locate_handle_buffer`

uefi-test-runner/src/boot/misc.rs, uefi/src/boot.rs, uefi/src/table/boot.rs
This comes with its own version of the `ScopedProtocol` struct. This one has no `BootServices` reference and no lifetime param.
For test coverage, updated `test_uninstall_protocol_interface` to use `boot::open_protocol` instead of the `BootServices` method. The `BootServices` method still has plenty of coverage in the test runner since `BootServices::open_protocol_exclusive` calls `BootServices::open_protocol`, and the former is called in lots of places.
=> boot: Add freestanding version of open_protocol

uefi-test-runner/src/bin/shell_launcher.rs, uefi/src/boot.rs
For testing, modify `shell_launcher.rs` to use the new function.
=> boot: Add freestanding version of open_protocol_exclusive

uefi-test-runner/src/bin/shell_launcher.rs, uefi/src/boot.rs
Also update shell_launcher to use the new freestanding functions.
=> Add `boot::{load_image, unload_image, start_image}`

uefi/src/lib.rs, uefi/src/proto/mod.rs, uefi/src/proto/tcg/v1.rs, uefi/src/proto/tcg/v2.rs
Follow-up for #1271 and #1206.
=> clippy: streamline lints

.github/workflows/rust.yml
"Build (nightly + unstable feature)" was misleading, as it also ran unit tests, doc tests, builds everything, and runs miri. I decoupled plus renamed things for a better separation of concerns.
=> ci: reorganize nightly CI jobs

uefi-test-runner/src/boot/misc.rs, uefi/src/boot.rs
This comes with its own version of the `TplGuard` struct. This one has no `BootServices` reference and no lifetime param.
Also add a test. The test can't actually verify the results since there's no way to query the TPL, but it at least calls `raise_tpl`.
=> boot: Add freestanding version of raise_tpl

uefi-test-runner/src/main.rs, uefi-test-runner/src/proto/console/serial.rs, uefi/src/boot.rs
Also update test-runner to use the new connect_controller (there are currently no uses of disconnect_controller in test-runner).
=> boot: Add freestanding connect_controller and disconnect_controller

uefi/src/boot.rs
=> boot: Add freestanding exit function

uefi/CHANGELOG.md, uefi/src/proto/device_path/mod.rs
The missing lifetime means that the &[u8] buffer could be freed while the &DevicePath still exists, which is UB.
Bug: https://github.com/rust-osdev/uefi-rs/issues/1281
=> uefi: Fix lifetimes in device_path TryFrom<&[u8]> impls

Cargo.lock, book/src/tutorial/app.md, template/Cargo.toml, uefi-raw/src/capsule.rs, uefi/CHANGELOG.md, uefi/Cargo.toml
This release contains a cherry-pick of https://github.com/rust-osdev/uefi-rs/pull/1282.
(The change in uefi-raw/src/capsule.rs was needed to fix a clippy lint.)
=> release: uefi-0.30.0

uefi/CHANGELOG.md
The 0.30 release is being made from the `version-0.30` branch, so we need to update the release data on the `main` branch as well.
=> uefi: Add release data to 0.30.0 release

README.md, uefi/Cargo.toml, uefi/README.md, uefi/src/lib.rs
_This is split-out 1/N from #1264 to improve reviewability._
This adds a new unified catchy Crate introduction.
=> doc: unified catchy new Crate introduction [doc: 1/n]

uefi-test-runner/src/proto/media.rs, uefi/src/boot.rs, uefi/src/table/boot.rs
Also made `EventNotifyFn` public, that was an existing oversight.
=> boot: Add freestanding version of `create_event`

Cargo.lock, book/src/tutorial/app.md, template/Cargo.toml, uefi/CHANGELOG.md, uefi/Cargo.toml
It is weird that we have a release v0.30 branch and a released version, but `uefi` is still
at `0.29` on the main branch. This merges the branch from #1285 into main with some necessary adaptions.
=> Merge release-v0.30 branch into main

uefi/src/boot.rs
One minor implementation change from the BootServices version: the Status value is ignored rather than asserting it is `SUCCESS`. There shouldn't be any practical difference, as stalling should always succeed. In the unlikely event that some implementation returns an error, a panic is unlikely to be desirable to the caller.
=> boot: Add freestanding stall

uefi-test-runner/src/boot/misc.rs, uefi/src/boot.rs
Also add corresponding test to uefi-test-runner.
=> boot: Add freestanding check_event

README.md, uefi/src/lib.rs
_This is split-out 2/N from #1264 to improve reviewability._
This moves misc stuff from README to lib.rs
=> doc: move misc stuff from README to lib.rs [doc: 2/N] 

uefi/src/table/boot.rs
The next release already has a fair number of breaking changes going into it, so restore a few public exports to uefi::table::boot to reduce the number of changes users have to make on upgrade. Specifically, `MemoryAttribute`, `MemoryDescriptor`, and `MemoryType`.
This module will be deprecated eventually (replaced by `uefi::boot`), so these re-exports will eventually go away in some future release.
=> Restore some memory exports to uefi::table::boot

.github/workflows/rust.yml, uefi/src/proto/mod.rs
The changes to dead_code analysis that lead to unwanted warnings have been reverted for now in rustc.
=> Remove dead_code workarounds

uefi/src/runtime.rs, uefi/src/table/mod.rs
=> runtime: Add freestanding set_virtual_address_map

uefi-test-runner/src/boot/misc.rs, uefi/src/boot.rs
=> Add freestanding set_timer and wait_for_event

uefi-test-runner/src/boot/misc.rs, uefi/src/boot.rs
=> boot: Add freestanding close_event

uefi-test-runner/src/boot/misc.rs, uefi/src/boot.rs
=> boot: Add freestanding install_configuration_table

uefi-test-runner/src/proto/mod.rs, uefi/src/boot.rs
This comes with its own version of the `ProtocolsPerHandle` struct. This one has no `BootServices` reference and no lifetime param. The GUID references in the slice are assumed to have a static lifetime, see safety comment for details.
=> boot: Add freestanding version of protocols_per_handle

uefi-test-runner/src/proto/mod.rs, uefi/src/boot.rs
Tweaked the interface slightly from the method; it now returns `Result<bool>` instead of `Result<()>`.
=> boot: Add freestanding test_protocol

uefi-test-runner/src/boot/misc.rs, uefi/src/boot.rs
=> boot: Add freestanding set_watchdog_timer

uefi-test-runner/src/boot/memory.rs, uefi/src/boot.rs
This follows the same structure as the BootServices version, so get_memory_map can be reused for exiting boot services.
=> boot: Add freestanding memory_map

uefi-test-runner/src/boot/misc.rs, uefi/src/boot.rs
=> boot: Add freestanding create_event_ex

uefi-test-runner/src/main.rs, uefi-test-runner/src/proto/console/gop.rs, uefi/src/boot.rs
=> boot: Add freestanding get_handle_for_protocol

docs/funcs_migration.md, uefi/CHANGELOG.md
This is in its own file so that we can conveniently link to it in [deprecation diagnostics](https://doc.rust-lang.org/reference/attributes/diagnostics.html#the-deprecated-attribute).
=> Add doc on freestanding function migration

uefi-test-runner/src/boot/mod.rs, uefi/src/boot.rs
These are relatively old parts of the API. The BootServices::locate_handle method in particular doesn't quite match our current conventions. For the freestanding version, changed the input buffer to not be an `Option`, and changed the buffer-too-small case to be an error rather than returning `Ok(usize)`.
=> boot: Add freestanding locate_handle and find_handles

uefi/src/boot.rs
=> boot: Add freestanding exit_boot_services

uefi/CHANGELOG.md, uefi/src/table/mod.rs
This provides an alternative to `SystemTable::as_ptr`.
=> uefi: Add table::system_table_raw

uefi-test-runner/src/boot/misc.rs, uefi/src/boot.rs
=> boot: Add freestanding register_protocol_notify

uefi/README.md, uefi/src/lib.rs
_This is split-out 3/N from #1264 to improve reviewability._
This adds an About section that discusses the value-add and possible use-cases.
- merge #1290 and rebase onto
=> doc: add comprehensive About section to lib.rs [doc: 3/N]

uefi-test-runner/examples/loaded_image.rs, uefi-test-runner/src/proto/device_path.rs, uefi/CHANGELOG.md, uefi/src/proto/device_path/mod.rs, uefi/src/proto/device_path/text.rs
Since BootServices will be deprecated, we don't want the public API to require using it.
=> uefi: Drop BootServices arg from device path <-> text conversions

uefi-test-runner/examples/loaded_image.rs, uefi-test-runner/src/proto/device_path.rs, uefi/CHANGELOG.md, uefi/src/proto/device_path/mod.rs, uefi/src/proto/device_path/text.rs
Reverts rust-osdev/uefi-rs#1327 (per https://github.com/rust-osdev/uefi-rs/issues/893#issuecomment-2286637186)
=> Revert "uefi: Drop BootServices arg from device path <-> text conversions"

docs/funcs_migration.md, uefi/CHANGELOG.md
Change the text to indicate that we don't plan to deprecate until a later release, but the new APIs are available for use.
=> Update funcs_migration doc

uefi-test-runner/src/bin/shell_launcher.rs, uefi-test-runner/src/boot/mod.rs, uefi/CHANGELOG.md, uefi/src/boot.rs, uefi/src/proto/boot_policy.rs, uefi/src/proto/mod.rs, uefi/src/table/boot.rs
This was decoupled from #1297 for better review-ability.
=> uefi: add BootPolicy type

.github/workflows/rust.yml
- cancel obsolete runs automatically
- streamline CI file
=> ci: cancel obsolete runs automatically + streamline

Cargo.lock, uefi-test-runner/Cargo.toml, uefi-test-runner/src/proto/load.rs, uefi-test-runner/src/proto/mod.rs, uefi/CHANGELOG.md, uefi/src/proto/media/load_file.rs, uefi/src/proto/media/mod.rs, uefi/src/table/boot.rs
Supersedes #945. Implements `LoadFile` and `LoadFile2`, including an integration test. The way we are implementing the LoadFile(2) protocol is roughly what certain Linux loaders do so that Linux can find its initrd. See code for references.
=> LoadFileProtocol and LoadFile2Protocol

uefi/src/lib.rs
_This is split-out 4/N from #1264 to improve reviewability._
This:
- adds a minimal example in `lib.rs` so that readers know what to expect from the crate
- compares `uefi` to other impls in the ecosystem, especially to the `std` impl for Rust
- adds a minimal example for a Rust app built with `std` and `uefi`
=> doc: Comparison to Ecosystem (including Rust std impl) [doc: 4/N]

uefi/src/lib.rs
This include is blocking the release job:
https://github.com/rust-osdev/uefi-rs/pull/1330#issuecomment-2299476889
For now, just inline the example so that we can release. Filed https://github.com/rust-osdev/uefi-rs/issues/1337 to track a better fix.
=> uefi: Inline the template example into lib.rs doc

uefi/README.md, uefi/src/lib.rs
_This is split-out 5/N from #1264 to improve reviewability._
This adds a section that  talks about our Documentation Organization/Overview
- merge #1292 and rebase onto
=> doc: Talk about Documentation Organization/Overview [doc: 5/N]

.github/workflows/rust.yml, Cargo.lock, Cargo.toml, README.md, book/src/SUMMARY.md, book/src/how_to/rust-std.md, shell.nix, uefi-std-example/Cargo.toml, uefi-std-example/README.md, uefi-std-example/src/main.rs, uefi/CHANGELOG.md, uefi/src/data_types/mod.rs
Split-out of #1292. This adds an example for a Rust **standard** binary for UEFI that utilizes `uefi` on top of that. It also adds a chapter to the book.
=> uefi std: add example and add book chapter

uefi/CHANGELOG.md, uefi/src/allocator.rs, uefi/src/boot.rs, uefi/src/helpers/mod.rs
Explicitly initializing and shutting down the allocator is no longer needed, since all the internal operations use the global system table now. Mark `allocator::init` and `allocator::exit_boot_services` as deprecated, and update `uefi::helper` to stop calling those functions as well.
=> Update the uefi::allocator module to use the global system table

README.md, uefi/README.md, uefi/src/lib.rs
_This is split-out 6/6 from #1264 to improve reviewability._
This adds to uefi/README how our documentation is organized.
- merge #1293 and rebase onto
=> doc: final README streamlining [doc: 6/6]

uefi-test-runner/src/proto/driver.rs, uefi-test-runner/src/proto/mod.rs, uefi/CHANGELOG.md, uefi/src/proto/driver/component_name.rs
=> uefi: Drop BootServices arg from ComponentName::open

.github/workflows/rust.yml
This is an attempt to prevent situations as documented in #1338
=> ci: release package check

uefi/src/boot.rs, uefi/src/table/boot.rs
The types are publicly re-exported from `uefi::table::boot`, so there should be no breaking change to the public API.
=> uefi: Move various types to the `uefi::boot` module

.github/workflows/rust.yml
Fixes https://github.com/rust-osdev/uefi-rs/issues/1198
=> ci: Use `cargo xtask fmt --check`

uefi/src/helpers/panic_handler.rs
=> uefi: Update panic handler to use the global system table

uefi-test-runner/src/main.rs, uefi/src/prelude.rs, uefi/src/table/runtime.rs, uefi/src/table/system.rs
=> uefi: Deprecate RuntimeServices

uefi/src/boot.rs, uefi/src/mem/memory_map/impl_.rs, uefi/src/table/boot.rs
=> uefi: Use global system table in MemoryMapBackingMemory

uefi/src/boot.rs, uefi/src/lib.rs, uefi/src/proto/console/text/output.rs, uefi/src/proto/media/fs.rs, uefi/src/proto/mod.rs
The new section is copied from the BootServices docstring. Also update various places that link to that doc.
=> uefi: Copy 'Accessing Protocols' docs to uefi::boot

uefi-macros/tests/ui/fail/entry_bad_abi.rs, uefi-macros/tests/ui/fail/entry_bad_abi.stderr, uefi-macros/tests/ui/fail/entry_bad_arg.rs, uefi-macros/tests/ui/fail/entry_bad_arg.stderr, uefi-macros/tests/ui/fail/entry_bad_return_type.rs, uefi-macros/tests/ui/fail/entry_bad_return_type.stderr, uefi-macros/tests/ui/pass/entry.rs, uefi-macros/tests/ui/pass/entry_docstring.rs, uefi-macros/tests/ui/pass/entry_unsafe.rs, uefi/CHANGELOG.md, uefi/src/allocator.rs, uefi/src/helpers/mod.rs, uefi/src/prelude.rs, uefi/src/table/mod.rs, uefi/src/table/system.rs
=> uefi: Deprecate SystemTable

.github/workflows/rust.yml
This reverts commit fc5c0a98c7f19acb9ccada14cd6a63d4c85e9b62.
When `cargo package` builds `uefi`, it does so with dependencies from crates.io. That causes a problem if `uefi` depends on some not-yet-released API changes in `uefi-raw` or `uefi-macros`. For example, see: https://github.com/rust-osdev/uefi-rs/pull/1383#issuecomment-2315661178
I couldn't find a way to force it to use local deps, so revert the job for now.
=> Revert "ci: check if crate can be packaged"

uefi/CHANGELOG.md, uefi/src/table/system.rs
=> uefi: Deprecate SystemTableView, Boot, and Runtime

uefi-raw/CHANGELOG.md, uefi-raw/src/table/boot.rs, uefi/src/boot.rs, uefi/src/table/boot.rs
=> Move PAGE_SIZE to uefi-raw and reexport from uefi boot modules

uefi/src/boot.rs, uefi/src/proto/media/file/info.rs, uefi/src/proto/media/file/mod.rs
=> uefi: Clean up imports of uefi::table::runtime

uefi/src/helpers/logger.rs, xtask/src/cargo.rs
Also update xtask so that the `--feature-permutations` test catches this.
=> Fix unused warnings if log-debugcon is not enabled

uefi/CHANGELOG.md, uefi/src/prelude.rs
=> Add uefi::{boot,runtime,system} modules to the prelude

uefi/src/helpers/mod.rs
This function may panic if called more than once, because `log::set_logger` panics if called more than once. Document this panic.
=> uefi: Add panic doc to uefi::helpers::init

uefi-test-runner/src/runtime/vars.rs, uefi/CHANGELOG.md, uefi/src/runtime.rs
This is a slightly more convenient alternative to `get_variable` when you only want to know if a variable exists. Useful if you want to set a variable only if it is not already set.
=> uefi: Add uefi::runtime::variable_exists

book/src/tutorial/app.md, uefi-test-runner/examples/hello_world.rs
This page was a little out of date; it still referred to `main` taking multiple arguments, and to the `uefi_services` crate.
=> Update the hello-world tutorial

uefi/CHANGELOG.md, uefi/src/helpers/mod.rs
=> uefi: Delete the deprecated helpers::system_table function

uefi-test-runner/src/boot/mod.rs, uefi-test-runner/src/fs/mod.rs, uefi-test-runner/src/proto/media.rs, uefi/CHANGELOG.md, uefi/src/fs/file_system/fs.rs
=> Drop FileSystem conversion from table::boot::ScopedProtocol

uefi-test-runner/src/main.rs, uefi-test-runner/src/proto/misc.rs, uefi-test-runner/src/proto/mod.rs, uefi-test-runner/src/proto/network/mod.rs, uefi-test-runner/src/proto/network/pxe.rs, uefi-test-runner/src/proto/network/snp.rs, uefi-test-runner/src/proto/pi/mod.rs, uefi-test-runner/src/proto/pi/mp.rs, uefi-test-runner/src/proto/shell_params.rs
=> test-runner: Remove BootServices from remaining proto tests

uefi-test-runner/src/boot/mod.rs, uefi/CHANGELOG.md, uefi/src/boot.rs
Also update `test_load_image` to use the freestanding functions, so that this case is tested (`LoadedImageDevicePath` is loaded with a null interface pointer).
=> Fix handling of a null interface pointer in `boot::open_protocol`

uefi-test-runner/src/boot/memory.rs, uefi-test-runner/src/boot/misc.rs, uefi-test-runner/src/boot/mod.rs, uefi-test-runner/src/main.rs
=> test-runner: Remove remaining tests for deprecated table types

uefi/CHANGELOG.md, uefi/src/proto/media/partition.rs
=> uefi: Derive Eq/PartialEq for GptPartitionEntry

uefi/CHANGELOG.md, uefi/src/data_types/strs.rs
This is modeled after `CStr::from_bytes_until_nul`, which was added in Rust 1.69. It's often the case that you have a slice of data containing a string, but the buffer size is larger than the string; these new methods make that case easy to handle.
[1]: https://doc.rust-lang.org/std/ffi/struct.CStr.html#method.from_bytes_until_nul
=> uefi: Add CStr16 conversions from slices with interior nuls

.github/codecov.yml, .github/workflows/rust.yml
Set the codecov token secret (added `CODECOV_TOKEN` to the github repo settings, value pulled from https://app.codecov.io/gh/rust-osdev/uefi-rs/config/general).
Also disabled codecov PR comments; I found don't find them very helpful, and they trigger an unnecessary notification email.
=> Codecov configuration updates

.github/workflows/msrv_toolchain.toml, Cargo.toml, uefi/CHANGELOG.md, uefi/src/data_types/unaligned_slice.rs, uefi/src/lib.rs, uefi/src/mem/memory_map/impl_.rs, uefi/src/proto/driver/component_name.rs
Mark a few new functions `const` to satisfy clippy lints. Also drop the "Keep in Sync with README!" comment for the MSRV doc; it's not in the readme anymore.
This upgrade will allow using various `core` improvements that have been stabilized since 1.70, including a number of `ptr` conveniences like `byte_add`, `is_aligned`, and `from_ref`/`from_mut` that make unsafe code easier to write.
=> Increase MSRV to 1.79

uefi/src/boot.rs, uefi/src/data_types/owned_strs.rs, uefi/src/data_types/strs.rs, uefi/src/fs/path/path.rs, uefi/src/lib.rs, uefi/src/polyfill.rs, uefi/src/proto/console/gop.rs, uefi/src/proto/media/file/mod.rs, uefi/src/proto/network/pxe.rs
This detects casts from a reference to a pointer that can be expressed more safely, e.g. with `ptr::as_ref` or `[slice].as_ptr`.
=> uefi: Deny clippy::ref_as_ptr

Cargo.lock, xtask/Cargo.toml, xtask/src/main.rs, xtask/src/qemu.rs
This simplifies xtask/qemu.rs a bit.
Also install a simple logger in `main`, so that download messages from ovmf-prebuilt get printed.
For now I've kept the same edk2 tag, because the latest version is crashing QEMU in our CI. I'll follow up on that later to figure out why.
=> Use ovmf-prebuilt

xtask/src/qemu.rs
edk2-stable202402 is the latest release that passes CI. Starting in edk2-stable202405, the aarch64 job fails early in boot with a "Synchronous Exception" error.
This seems likely to be an issue with the version of QEMU installed on the Github runner, as newer versions of OVMF work fine in my local testing.
=> xtask: Update OVMF prebuilts

Cargo.lock, uefi-raw/Cargo.toml
We don't use DST types in uefi-raw; this dependency was never actually used.
=> uefi-raw: Drop unused dependency on ptr_meta

uefi-test-runner/src/proto/console/serial.rs, xtask/src/main.rs, xtask/src/qemu.rs
Format checking was printing errors but not exiting non-zero, so the CI didn't actually catch formatting errors since da55df613496b68899996d44e2dc2fb0ffb45bf9.
Fix that, and fix up a few format errors that snuck in.
=> Fix `cargo xtask fmt --check`

uefi/src/mem/memory_map/impl_.rs
The qsort, partition, and swap methods do not need to be `unsafe`; they do some unsafe operations internally, but have safe interfaces.
Add some asserts to ensure that arguments passed to swap and get_element_phys_addr are valid, and also add some safety comments.
=> Clean up some use of unsafe in MemoryMapRefMut

uefi/src/boot.rs, uefi/src/data_types/owned_strs.rs, uefi/src/data_types/strs.rs, uefi/src/data_types/unaligned_slice.rs, uefi/src/fs/path/path.rs, uefi/src/helpers/logger.rs, uefi/src/mem/memory_map/impl_.rs, uefi/src/proto/console/gop.rs, uefi/src/proto/console/text/output.rs, uefi/src/proto/device_path/device_path_gen.rs, uefi/src/proto/driver/component_name.rs, uefi/src/proto/shim/mod.rs, uefi/src/proto/tcg/v1.rs, uefi/src/proto/tcg/v2.rs, xtask/src/device_path/group.rs, xtask/src/device_path/node.rs, xtask/src/device_path/spec.rs
=> Fix clippy::needless_lifetimes in Rust 1.83 and ShimLock ABI on ia32

uefi-raw/CHANGELOG.md, uefi-raw/src/protocol/driver.rs
Add the interface for `EFI_DRIVER_BINDING_PROTOCOL`.
Ref: [UEFI 2.10: 11.1 EFI Driver Binding Protocol](https://uefi.org/specs/UEFI/2.10/11_Protocols_UEFI_Driver_Model.html)
<details>
<summary>Example usage</summary>
```rust
#![no_main]
#![no_std]
use uefi::prelude::*;
use uefi_raw::protocol::device_path::DevicePathProtocol;
use uefi_raw::protocol::driver::DriverBindingProtocol;
// EFI_DRIVER_BINDING_SUPPORTED
unsafe extern "efiapi" fn supported(
_this: *const DriverBindingProtocol,
_controller: uefi_raw::Handle,
_remaining: *const DevicePathProtocol,
) -> Status {
log::info!("DriverBindingSupported called");
Status::SUCCESS
}
// EFI_DRIVER_BINDING_START
unsafe extern "efiapi" fn start(
_this: *const DriverBindingProtocol,
_controller: uefi_raw::Handle,
_remaining: *const …
```
=> uefi-raw: Add DriverBindingProtocol

.github/workflows/msrv_toolchain.toml, Cargo.toml, uefi/CHANGELOG.md, uefi/src/lib.rs
1.83 has been released, so we can bump MSRV to 1.81. This will unblock https://github.com/rust-osdev/uefi-rs/issues/1200 and also allow updating the `ptr_meta` dep.
=> Increase MSRV to 1.81

Cargo.lock, Cargo.toml, uefi/src/proto/device_path/device_path_gen.rs, uefi/src/proto/tcg/v1.rs, uefi/src/proto/tcg/v2.rs, xtask/src/device_path/field.rs, xtask/src/device_path/mod.rs, xtask/src/device_path/node.rs
The PtrExt trait was removed in this release; free functions are used instead.
=> Update ptr_meta to 0.3.0

uefi/CHANGELOG.md, uefi/src/data_types/chars.rs, uefi/src/data_types/owned_strs.rs, uefi/src/data_types/strs.rs, uefi/src/fs/file_system/error.rs, uefi/src/fs/path/validation.rs, uefi/src/mem/memory_map/impl_.rs, uefi/src/proto/boot_policy.rs, uefi/src/proto/device_path/build.rs, uefi/src/proto/device_path/mod.rs, uefi/src/proto/driver/component_name.rs, uefi/src/proto/media/file/info.rs, uefi/src/proto/network/pxe.rs, uefi/src/proto/string/unicode_collation.rs, uefi/src/result/error.rs, uefi/src/runtime.rs
Fixes https://github.com/rust-osdev/uefi-rs/issues/1200
=> Remove unstable gate for `core::error::Error` impls

uefi-raw/src/status.rs, uefi-raw/src/table/system.rs, uefi-test-runner/examples/sierpinski.rs, uefi-test-runner/src/boot/misc.rs, uefi/src/boot.rs, uefi/src/data_types/mod.rs, uefi/src/mem/memory_map/impl_.rs, uefi/src/mem/memory_map/mod.rs, uefi/src/proto/console/gop.rs, uefi/src/proto/device_path/build.rs, uefi/src/proto/device_path/mod.rs, uefi/src/proto/loaded_image.rs, uefi/src/proto/media/file/info.rs, uefi/src/proto/media/file/mod.rs, uefi/src/proto/network/pxe.rs, uefi/src/proto/network/snp.rs, uefi/src/proto/rng.rs, uefi/src/proto/tcg/v1.rs, uefi/src/proto/tcg/v2.rs, uefi/src/runtime.rs, uefi/src/util.rs
As of Rust 1.80, these functions are in the prelude so we don't need to import `mem` or fully specify the path.
Also replace one use of `size_of` with `usize::BITS` as suggested by clippy.
=> Use size_of/size_of_val/align_of/align_of_val from the prelude

book/src/how_to/building_drivers.md
`config.toml` is a project-level configuration. Cargo will only read the configuration from the current directory and up, and not in:
- package directories in a workspace
- package directories when `--manifest-path` is used
Use `build.rs` instead, which will be executed before the package is built and only apply the flags for the specific package. This allows mixing drivers and applications in a workspace while still invoking Cargo from the workspace root.
Ref: https://doc.rust-lang.org/cargo/reference/config.html#hierarchical-structure
Ref: https://doc.rust-lang.org/cargo/reference/build-scripts.html
=> book: Set driver link-arg in `build.rs`

uefi-raw/CHANGELOG.md, uefi-raw/src/protocol/firmware_volume.rs, uefi-raw/src/protocol/mod.rs
Add bindings for `EFI_FIRMWARE_VOLUME2_PROTOCOL`, `EFI_FIRMWARE_VOLUME_BLOCK2_PROTOCOL`, and related data types.
Reason: I need to read a raw section of a file (`FV->ReadSection`) added in edk2 for Platform GOP Policy driver implementation.
Ref: UEFI-PI 1.9: III-3.4.1 Firmware Volume2 Protocol
Ref: UEFI-PI 1.9: III-3.4.2 Firmware Volume Block2 Protocol
=> uefi-raw: Add FirmwareVolume{,Block}2Protocol

uefi-raw/CHANGELOG.md, uefi-raw/src/protocol/mod.rs, uefi-raw/src/protocol/scsi.rs
This is a subset of https://github.com/rust-osdev/uefi-rs/pull/1155 with just the uefi-raw changes.
=> uefi-raw: Add ScsiIoProtocol

uefi/CHANGELOG.md, uefi/src/proto/device_path/device_path_gen.rs, uefi/src/proto/device_path/mod.rs, xtask/src/device_path/node.rs
This fixes a bug where `&DevicePathNode` could be converted to any specific node type as long as the node length matches. The node type and subtype needs to be checked first.
Also added a test for this.
Fixes https://github.com/rust-osdev/uefi-rs/issues/1489
=> Add missing type/subtype checks to `TryFrom<&DevicePathNode>`

uefi-raw/CHANGELOG.md, uefi-raw/src/protocol/network/http.rs
Of note, all types now implement `Default`, with all fields set to zero/null. This can be useful when constructing the types, even if the default is not itself particularly semantically meaningful.
=> uefi-raw: Add common impls for http types

uefi-test-runner/src/boot/misc.rs, uefi-test-runner/src/proto/media.rs, uefi/src/allocator.rs, uefi/src/proto/loaded_image.rs
See https://github.com/rust-osdev/uefi-rs/issues/1470?issue=rust-osdev%7Cuefi-rs%7C1521. This rewrites code from medhefgo that we do not have relicensing approval for.
=> relicensing: Rewrite allocator, configuration table, and image unload PRs

uefi-raw/CHANGELOG.md, uefi-raw/src/table/boot.rs, uefi/src/boot.rs
See https://github.com/rust-osdev/uefi-rs/issues/1521. This rewrites code from pavlus that we do not have relicensing approval for.
=> relicensing: Rewrite set_timer PR

uefi-raw/src/table/boot.rs
When using custom memory types in an uefi application there is a bug that causes the system to freeze on some machines. I had the same issue and struggled for quite sometime. #1375
Thus, I think it would be helpful to add a warning to the documentation regarding this issue:
>For the memory management functions in EFI, an OS is meant to be able to use "memory type" values above 0x80000000 >for its own purposes. In the OVMF EFI firmware release "r11337" (for Qemu, etc) there is a bug where the firmware >assumes the memory type is within the range of values defined for EFI's own use, and uses the memory type as an array >index. The end result is an "array index out of bounds" bug; where the higher memory type values (e.g. perfectly legal >values above 0x80000000) cause the 64-bit version of …
=> Add warning to custom memory types

uefi-test-runner/src/proto/device_path.rs
Split the conversion tests out into separate functions. This is a bit more verbose, but makes it clearer exactly what is being tested.
The conversion tests now use a hardcoded test `DevicePath`, so we no longer need to `cfg` the tests for different arches based on what devices QEMU creates. This also makes it clearer what effects `DisplayOnly` and `AllowShortcuts` can have on the text conversion.
=> test-runner: Clean up device path tests

uefi/src/proto/device_path/text.rs
See https://github.com/rust-osdev/uefi-rs/issues/1521. This rewrites code from supdrewin that we do not have relicensing approval for.
=> relicensing: Rewrite PR "DevicePathToText and DevicePathFromText Protocol"

uefi/src/lib.rs
Missed this one in the previous cleanup.
=> uefi: Update license info in docstring

uefi-raw/CHANGELOG.md, uefi-raw/src/lib.rs
This PR pulls in just the definition of the `Boolean` type from https://github.com/rust-osdev/uefi-rs/pull/1307.
=> uefi-raw: add Boolean type

uefi-raw/CHANGELOG.md, uefi-raw/src/lib.rs, uefi-raw/src/protocol/block.rs, uefi-raw/src/protocol/console.rs, uefi-raw/src/protocol/device_path.rs, uefi-raw/src/protocol/file_system.rs, uefi-raw/src/protocol/media.rs, uefi-raw/src/protocol/network/dhcp4.rs, uefi-raw/src/protocol/network/http.rs, uefi-raw/src/table/boot.rs, uefi-raw/src/table/runtime.rs, uefi-test-runner/src/proto/load.rs, uefi/CHANGELOG.md, uefi/src/boot.rs, uefi/src/proto/boot_policy.rs, uefi/src/proto/console/pointer/mod.rs, uefi/src/proto/console/text/input.rs, uefi/src/proto/console/text/output.rs, uefi/src/proto/device_path/text.rs, uefi/src/proto/media/block.rs, uefi/src/proto/media/load_file.rs, uefi/src/proto/mod.rs
Use the new type introduced in ec6e0e6b (#1536). This adds the changes originally proposed in #1307.
=> uefi-raw: use new Boolean type 

xtask/src/check_raw.rs
This helps to better identify why the check-raw step fails.
=> xtask/uefi-raw: improve check-raw error messages

uefi/src/data_types/strs.rs, uefi/src/proto/network/pxe.rs
=> Fix upcoming lints in clippy 1.85

uefi/CHANGELOG.md, uefi/src/boot.rs
Solves the confusion brought up in #1539
=> uefi: clarify situation with `boot::memory_map()` and `Status::BUFFER_TOO_SMALL`

.github/workflows/msrv_toolchain.toml, .github/workflows/rust.yml, uefi-raw/src/table/system.rs
`uefi-raw` has a lower MSRV than the `uefi` package, currently 1.70. Fix a minor error that prevented it from building at that MSRV, and add a job to check that package's MSRV build going forward.
Also improve the existing MSRV job so that it uses cargo to get the correct MSRV value, rather than having a separate MSRV toolchain file that has to be updated manually.
=> Fix uefi-raw MSRV build, and improve CI for MSRV

uefi-raw/CHANGELOG.md, uefi-raw/src/protocol/network/mod.rs, uefi-raw/src/protocol/network/pxe.rs
This PR just adds the raw types, I'll follow up with additional PR(s) to use them in `uefi::proto::network::pxe`.
=> Add PXE types to uefi-raw

uefi/src/proto/network/mod.rs
=> uefi: Replace definition of MacAddress with a re-export from uefi-raw

uefi-raw/src/protocol/network/pxe.rs, uefi/src/proto/network/pxe.rs
Move the docstrings to uefi-raw, then re-export the types in uefi.
=> Use bitflags definitions from uefi-raw in uefi's pxe module

uefi/CHANGELOG.md, uefi/src/proto/network/snp.rs
The buffer is supposed to contain both the header and data, so adding `buffer.len() + header_size` tells the firmware the wrong size of the packet.
Fixes https://github.com/rust-osdev/uefi-rs/issues/1549
=> uefi: Fix the BufferSize argument in SimpleNetwork::transmit

uefi/src/proto/network/pxe.rs
=> Use newtype enum definitions from uefi-raw in uefi's pxe module

uefi-test-runner/src/boot/misc.rs, uefi/CHANGELOG.md, uefi/src/boot.rs
Missing from the boot services is the SignalEvent() function, which is used to place signals into a signaled state. Implement this to allow applications to signal e.g. event groups.
Also implement a test case, checking that the event callback is signaled when the newly introduced function is invoked.
=> uefi: Implement SignalEvent() boot services function

uefi/CHANGELOG.md, uefi/src/boot.rs
The firmware is allowed to return an allocation at address zero. This is not compatible with Rust, since it's UB to write through a null pointer. If a null address is returned, retry the allocation. If that second allocation still fails, return an error rather than panicking.
Fixes https://github.com/rust-osdev/uefi-rs/issues/1557
=> uefi: Improve handling of null-address allocations in allocate_pages

uefi/CHANGELOG.md, uefi/src/data_types/strs.rs
This makes it match the CStr16 Display impl. Added tests for both.
=> uefi: Exclude null byte from CStr8 Display impl

uefi-raw/CHANGELOG.md, uefi-raw/src/lib.rs, uefi/CHANGELOG.md, uefi/src/proto/network/mod.rs
- I've added conversions for IpAddress so that it can be converted to `core::net::*` types.
- I also added a conversion for MacAddress to `[u8; 6]` because most other utilities that consume MAC addresses want that type.
=> Implement conversions for IpAddress and MacAddress

uefi/src/proto/network/pxe.rs
In the rest of the crate we generally don't have blank lines between sections of `use`, so remove that in the pxe module.
=> uefi: Reformat `use` items in pxe module

uefi/CHANGELOG.md, uefi/src/proto/network/pxe.rs
Although these methods are just reading data, they are almost certainly modifying internal state in the UEFI protocol and so should be `&mut`.
=> uefi: Consistently use `&mut self` for pxe::BaseCode methods

.github/workflows/qa.yml, .typos.toml
=> ci: fix typos

uefi-macros/src/lib.rs, uefi/src/proto/mod.rs
Some minor cleanups of the docs, and specifically note that implementing `Protocol` allows a protocol to be opened with uefi-rs, but installing a protocol is separate.
https://github.com/rust-osdev/uefi-rs/issues/1573
=> Update Protocol/unsafe_protocol docs

uefi-raw/CHANGELOG.md, uefi-raw/src/protocol/disk.rs
Added a (only raw for now) binding to the UEFI DiskInfo protocol [`d432a67f-14dc-484b-b3bb-3f0291849327`].
=> uefi-raw: Add DiskInfo protocol binding

uefi-raw/CHANGELOG.md, uefi-raw/src/protocol/scsi.rs
Added a (only raw for now) binding to the EFI_EXT_SCSI_PASS_THRU_PROTOCOL [`143b7632-b81b-4cb7-abd3-b625a5b9bffe`].
=> uefi-raw: Add EXT_SCSI_PASS_THRU protocol binding

uefi/CHANGELOG.md, uefi/src/runtime.rs
Some firmware fails to update the "VariableNameSize" parameter passed into GetNextVariableName(). To work around this we will use a large default buffer size.
=> uefi runtime: Increase default size of name buffer

uefi-raw/CHANGELOG.md, uefi-raw/Cargo.toml, uefi-raw/src/lib.rs
This will help with the implementation of https://github.com/rust-osdev/uefi-rs/issues/1575.
Note that this bumps the MSRV of uefi-raw to 1.77 so that `core::net` is available.
=> uefi-raw: Add conversions to/from core::net IP address types

uefi/src/allocator.rs, uefi/src/boot.rs, uefi/src/data_types/strs.rs, uefi/src/helpers/logger.rs, uefi/src/lib.rs, uefi/src/proto/console/gop.rs, uefi/src/proto/debug/mod.rs, uefi/src/proto/device_path/mod.rs, uefi/src/proto/loaded_image.rs, uefi/src/proto/media/disk.rs, uefi/src/proto/media/file/dir.rs, uefi/src/proto/media/file/info.rs, uefi/src/proto/media/file/mod.rs, uefi/src/proto/tcg/v1.rs, uefi/src/proto/tcg/v2.rs, uefi/src/runtime.rs, uefi/src/util.rs
These are all very mechanical changes, just adding `unsafe { ... }` blocks where needed.
https://github.com/rust-osdev/uefi-rs/issues/1584
=> uefi: Enable unsafe_op_in_unsafe_fn lint

uefi-test-runner/src/proto/network/pxe.rs, uefi/CHANGELOG.md, uefi/src/proto/network/mod.rs, uefi/src/proto/network/pxe.rs
Methods are now provided to access mode data instead of direct field access.
This will help with the `IpAddr` conversion. https://github.com/rust-osdev/uefi-rs/issues/1575
=> uefi: Make pxe::Mode an opaque struct

uefi-raw/src/protocol/disk.rs, uefi-test-runner/src/proto/media.rs, uefi/CHANGELOG.md, uefi/src/proto/media/disk_info.rs, uefi/src/proto/media/mod.rs, xtask/src/qemu.rs
Implement safe protocol wrapper for `EFI_DISK_INFO_PROTOCOL`.
I also added an integration-test that's based on the same disk configuration I did for https://github.com/rust-osdev/uefi-rs/pull/1589.
=> uefi: Implement safe wrapper for EFI_DISK_INFO_PROTOCOL

uefi-raw/CHANGELOG.md, uefi-raw/src/protocol/mod.rs, uefi-raw/src/protocol/nvme.rs
Added a (only raw for now) binding to EFI_NVM_EXPRESS_PASS_THRU_PROTOCOL [`52c78312-8edc-4233-98f2-1a1aa5e388a5`].
=> uefi-raw: Add EFI_NVM_EXPRESS_PASS_THRU_PROTOCOL bindings

uefi-raw/src/protocol/scsi.rs
Add documentation to ScsiIoScsiRequestPacket
=> uefi-raw: Add documentation to ScsiIoScsiRequestPacket

uefi-raw/CHANGELOG.md, uefi-raw/src/protocol/ata.rs, uefi-raw/src/protocol/mod.rs, uefi/src/proto/media/disk_info.rs
Added a (only raw for now) binding to EFI_ATA_PASS_THRU_PROTOCOL [`1d3de7f0-0807-424f-aa69-11a54e19a46f`].
Also fixed a small spelling mistake in `disk_info` that's related to this.
There is a bug in the UEFI spec v2.11 for method: `EFI_ATA_PASS_THRU_PROTOCOL.ResetPort()`. Parameter `port` is falsely portrayed as pointer. I sent in an errata.
Should I make the `Reset`-method's take a `*mut Self` instead of `*const Self` again?
=> uefi-raw: Add EFI_ATA_PASS_THRU_PROTOCOL bindings

uefi-raw/CHANGELOG.md, uefi-raw/src/protocol/device_path.rs
Added a (raw only for now) binding for `EFI_DEVICE_PATH_UTILITIES_PROTOCOL` [`0379be4e-d706-437d-b037-edb82fb772a4`].
Having safe bindings for this would be very helpful for `pass-thru`, where constructing and appending `DevicePath`'s is necessary. But I don't know how to model a safe APi here, since this API allocates and requires the caller to free the allocated stuff.
=> uefi-raw: Add binding for EFI_DEVICE_PATH_UTILITIES_PROTOCOL

uefi/src/proto/console/pointer/mod.rs, uefi/src/proto/driver/component_name.rs, uefi/src/proto/media/block.rs, uefi/src/proto/media/disk.rs, uefi/src/runtime.rs
This unblocks #1600.
Instead of applying the fixes, it is better to ignore the lints. In once case, we have false positives. In the other case, we actually like the old style. For instance:
We prefer
```
/// # Parameters
/// * `some_param` This parameter has a
///    very long description
```
over
```
/// # Parameters
/// * `some_param` This parameter has a
/// very long description
```
=> clippy: fix

uefi/CHANGELOG.md, uefi/src/mem/aligned_buffer.rs, uefi/src/mem/mod.rs
AlignedBuffer is a helper class that manages the livetime of a memory region, allocated using a certain alignment. Like Box, it handles deallocation when the object isn't used anymore.
=> helpers: Add AlignedBuffer

.github/FUNDING.yml, .github/workflows/developer_productivity.yml, .github/workflows/qa.yml, .github/workflows/rust.yml, flake.lock, flake.nix, xtask/src/main.rs
=> xtask: fix nixfmt + update Nix flake + fix CI

uefi-test-runner/src/proto/device_path.rs, uefi/CHANGELOG.md, uefi/src/proto/device_path/mod.rs, uefi/src/proto/device_path/text.rs, uefi/src/proto/device_path/util.rs
Add nice helper methods on `DevicePath` to construct a new path by appending two paths.
- I need this for the `pass-thru` stuff
- I had to move the `PoolDevicePath*` stuff around a bit. But they IMHO make more sense where they are now anyway, since those are generally useful.
=> uefi: Some convenient DevicePathUtilities helper methods

uefi-raw/src/protocol/scsi.rs, uefi-test-runner/src/proto/mod.rs, uefi-test-runner/src/proto/scsi/mod.rs, uefi-test-runner/src/proto/scsi/pass_thru.rs, uefi/CHANGELOG.md, uefi/src/proto/mod.rs, uefi/src/proto/scsi/mod.rs, uefi/src/proto/scsi/pass_thru.rs
**Update** [Latest API discussions](https://github.com/rust-osdev/uefi-rs/pull/1589#issuecomment-2791197828)
---
Added a safe wrapper for the extended SCSI Pass Thru protocol.
I did my best to design the API in a way that avoids accidentally using it incorrectly, yet allowing it to operate efficiently.
The `ScsiRequestBuilder` API is designed in a way that should easily make it possible to use it for both `EFI_EXT_SCSI_PASS_THRU_PROTOCOL` and a possible future safe protocol wrapper of `EFI_SCSI_IO_PROTOCOL`.
```rust
// query handles with support for the protocol (one handle per SCSI controller)
let scsi_ctrl_handles = uefi::boot::find_handles::<ExtScsiPassThru>().unwrap();
// Iterate over scsi controllers with passthru support:
for handle in scsi_ctrl_handles {
// open protocol for …
```
=> uefi: Add safe protocol wrapper for EFI_EXT_SCSI_PASS_THRU_PROTOCOL

uefi-raw/src/protocol/ata.rs
This is an important fix for the raw bindings of `ATA_PASS_THRU_PROTOCOL`
- The `AtaPassThruCommandPacket` was broken (missing fields).
- The `AtaPassThruProtocol::pass_thru()` function signature had a redundant `*mut` on the `event` parameter
- The field-name was horrible :D
This was previously part of https://github.com/rust-osdev/uefi-rs/pull/1595
Blocks: https://github.com/rust-osdev/uefi-rs/pull/1595
=> uefi-raw: Fix ATA_PASS_THRU_PROTOCOL bindings

uefi-test-runner/src/proto/network/snp.rs, xtask/src/main.rs, xtask/src/qemu.rs
- **test/snp: NOT_STARTED error is not a test failure**
- **test/snp: UNSUPPORTED for statistics is not a test failure**
- **test/snp: drop multicast from packet filter.**
- **xtask/qemu: switch to virtio-net nic.**
=> snp network test fixes

uefi-raw/CHANGELOG.md, uefi-raw/src/protocol/mod.rs, uefi-raw/src/protocol/usb/io.rs, uefi-raw/src/protocol/usb/mod.rs
Added a raw binding for `EFI_USB_IO_PROTOCOL`.
=> uefi-raw: Add EFI_USB_IO_PROTOCOL bindings

uefi-raw/src/protocol/nvme.rs, uefi-test-runner/src/proto/mod.rs, uefi-test-runner/src/proto/nvme/mod.rs, uefi-test-runner/src/proto/nvme/pass_thru.rs, uefi/CHANGELOG.md, uefi/src/proto/mod.rs, uefi/src/proto/nvme/mod.rs, uefi/src/proto/nvme/pass_thru.rs, xtask/src/qemu.rs
**Update** [Latest API discussions](https://github.com/rust-osdev/uefi-rs/pull/1589#issuecomment-2791197828)
---
Implemented a safe API wrapper for `EFI_NVM_EXPRESS_PASS_THRU_PROTOCOL` [`52c78312-8edc-4233-98f2-1a1aa5e388a5`].
Added an integration-test for it.
~~+This contains a copy of the `AlignedBuffer` commit from https://github.com/rust-osdev/uefi-rs/pull/1589.+~~
This uses the iterator/mutable design I suggested here: https://github.com/rust-osdev/uefi-rs/pull/1589#issuecomment-2755354089 where the iter method only captures the protocol (`NvmePassThru`) immutably, but requires you to use the produced element (`NvmeNamespace`) in a mutable way for meaningful methods like `execute_command`.
=> uefi: Add safe protocol wrapper for EFI_NVM_EXPRESS_PASS_THRU_PROTOCOL

uefi/src/boot.rs, uefi/src/data_types/mod.rs, uefi/src/data_types/strs.rs, uefi/src/proto/device_path/text.rs
Move `PoolString` to enable other protocol implementations to utilize its functionality.
In particular, this PR will enable a safe wrapper around `UsbIoProtocol`'s `get_string_descriptor()`.
=> uefi: Move PoolString to enable additional use

uefi-raw/src/protocol/usb/io.rs
Correct definitions of the EFI_USB_IO_PROTOCOL and associated structures to align with the UEFI specification.
Also add additional traits to associated structs for ease of use.
=> uefi-raw: Fix EFI_USB_IO_PROTOCOL implementation

uefi-raw/CHANGELOG.md, uefi-raw/src/protocol/usb/host_controller.rs, uefi-raw/src/protocol/usb/io.rs, uefi-raw/src/protocol/usb/mod.rs
Added a raw binding for `EFI_USB2_HC_PROTOCOL`.
Also moves the common USB structures into `usb` module to share between USB protocol interfaces.
=> uefi-raw: Add EFI_USB2_HC_PROTOCOL bindings

uefi-test-runner/src/proto/ata/mod.rs, uefi-test-runner/src/proto/ata/pass_thru.rs, uefi-test-runner/src/proto/media.rs, uefi-test-runner/src/proto/mod.rs, uefi/CHANGELOG.md, uefi/src/proto/ata/mod.rs, uefi/src/proto/ata/pass_thru.rs, uefi/src/proto/mod.rs, xtask/src/qemu.rs
**Update** [Latest API discussions](https://github.com/rust-osdev/uefi-rs/pull/1589#issuecomment-2791197828)
---
Implemented a safe API wrapper for `EFI_ATA_PASS_THRU_PROTOCOL` [`1d3de7f0-0807-424f-aa69-11a54e19a46f`].
Added an integration-test for it.
This contains a copy of the AlignedBuffer commit from https://github.com/rust-osdev/uefi-rs/pull/1589.
This uses the iterator/mutable design I suggested here: https://github.com/rust-osdev/uefi-rs/pull/1589#issuecomment-2755354089 where the iter method only captures the protocol (`AtaPassThru`) immutably, but requires you to use the produced element (`AtaDevice`) in a mutable way for meaningful methods like execute_command.
This closes #244
=> uefi: Add safe protocol wrapper for EFI_ATA_PASS_THRU_PROTOCOL

uefi-raw/src/protocol/network/mod.rs, uefi-raw/src/protocol/network/snp.rs, uefi-test-runner/src/proto/network/snp.rs, uefi/src/proto/network/snp.rs
Move the raw definition of EFI_SIMPLE_NETWORK_PROTOCOL to the `uefi-raw` crate.
=> uefi-raw: Move EFI_SIMPLE_NETWORK_PROTOCOL

uefi/CHANGELOG.md, uefi/src/boot.rs
Enables access to hidden (but not sensitive) components of RAII guards.
Exposing the old `Tpl` value inside `TplGuard` allows for retrieving the current `Tpl` safely as shown below.
```rust
// SAFETY:
//
// Tpl::HIGH_LEVEL is the highest possible `Tpl` level according to the UEFI
// specification and so will be greater than or equal to all valid `Tpl` values.
// Furthermore, we are only in `Tpl::HIGH_LEVEL` for the smallest possible amount of time.
unsafe { raise_tpl(Tpl::HIGH_LEVEL).old_tpl() }
``` 
Exposing the `OpenProtocolParams` inside `ScopedProtocol` allows UEFI drivers to use `uefi` and not have to store duplicate handles in their private data structures, since they can access the one inside of the `ScopedProtocol`.
=> Enable access to hidden RAII guard components

uefi-test-runner/src/boot/memory.rs, uefi/CHANGELOG.md, uefi/src/allocator.rs
Please review this commit-by-commit.
=> UEFI Allocator: add PAGE_SIZE shortcut 

uefi-raw/src/protocol/usb/host_controller.rs, uefi-raw/src/protocol/usb/mod.rs
Change the definitions of `UsbPortStatus` and `UsbTransferStatus` to better align with the UEFI specification, primarily by adding the defined flags.
=> uefi-raw: Redefine UsbPortStatus and UsbTransferStatus

uefi-raw/CHANGELOG.md, uefi-raw/src/protocol/device_path.rs, uefi/CHANGELOG.md, uefi/src/proto/device_path/build.rs, uefi/src/proto/device_path/device_path_gen.rs, uefi/src/proto/device_path/mod.rs, xtask/src/device_path/node.rs
uefi: remove duplication in DevicePathHeader; use uefi-raw
=> uefi: remove duplication in DevicePathHeader; use uefi-raw

Cargo.lock, Cargo.toml
Fix the CI that is broken since https://github.com/rust-osdev/uefi-rs/pull/1648#issuecomment-2841154287.
The MSRV was bumped upstream as part of a minor fix update: https://github.com/google/gpt-disk-rs/commit/02d38c2da469aa01519f094d2fd23dffde451761#r156105778
=> ci: fix failing MSRV uefi-raw job

uefi-test-runner/src/boot/misc.rs, uefi/CHANGELOG.md, uefi/src/boot.rs
UEFI Boot services includes a helper function (CalculateCrc32) for calculating a 32-bit CRC over a buffer. This is useful in Rust applications as well, so expose it in the boot services API.
=> uefi: Implement CalculateCrc32() boot services function

Cargo.lock, book/src/tutorial/app.md, template/Cargo.toml, uefi-macros/CHANGELOG.md, uefi-macros/Cargo.toml, uefi-raw/CHANGELOG.md, uefi-raw/Cargo.toml, uefi/CHANGELOG.md, uefi/Cargo.toml
Closes https://github.com/rust-osdev/uefi-rs/issues/1608
=> release: uefi-raw-0.11.0, uefi-macros-0.18.1, uefi-0.35.0

xtask/src/opt.rs, xtask/src/qemu.rs
This makes the shell more consistent with ovmf-code/ovmf-vars.
Closes https://github.com/rust-osdev/uefi-rs/issues/1616
=> xtask: Add --ovmf-shell arg

xtask/Cargo.toml, xtask/src/opt.rs, xtask/src/qemu.rs
=> xtask: simplify env variables

uefi-test-runner/examples/hello_world.rs, uefi-test-runner/examples/loaded_image.rs, uefi-test-runner/examples/timestamp.rs, uefi-test-runner/src/proto/network/snp.rs, uefi-test-runner/src/proto/pi/mp.rs, uefi/CHANGELOG.md, uefi/src/boot.rs, uefi/src/helpers/panic_handler.rs, uefi/src/proto/network/ip4config2.rs
Before:
```rust
pub fn stall(microseconds: usize) {
```
After:
```rust
pub fn stall(duration: Duration) {
```
=> uefi: use Duration for boot::stall

xtask/src/check_raw.rs
Instead of a generic "forbidden type of item" error, recommend using the `newtype_enum!` macro.
Motivated by https://github.com/rust-osdev/uefi-rs/pull/1658#issuecomment-2862196591
=> xtask: Improve error message for enums in uefi-raw

uefi/CHANGELOG.md, uefi/src/system.rs, uefi/src/table/cfg.rs
=> ConfigTableEntry move constants and add example

Cargo.toml
Fixes https://github.com/rust-osdev/uefi-rs/issues/1651
=> Unpin uguid

uefi/src/boot.rs
=> doc: improved documentation for boot allocation functions

uefi-raw/CHANGELOG.md, uefi-raw/src/protocol/mod.rs, uefi-raw/src/protocol/pci/mod.rs, uefi-raw/src/protocol/pci/root_bridge.rs, uefi-raw/src/table/boot.rs, uefi/src/boot.rs
=> uefi-raw: Add binding for EFI_PCI_ROOT_BRIDGE_IO_PROTOCOL

uefi-raw/CHANGELOG.md, uefi-raw/src/protocol/device_path.rs, uefi/CHANGELOG.md, uefi/src/proto/device_path/mod.rs
Closes #1639. I personally prefer to move all generic low-level UEFI documentation to `uefi-raw` and refer to it from `uefi`.
Together with #1612, I think this is a major step forward in our documentation, when it comes to Protocols and Device Paths.
=> doc: streamline device path documentation between uefi-raw and uefi

uefi/src/data_types/strs.rs, uefi/src/proto/driver/component_name.rs, uefi/src/proto/media/file/info.rs
=> clippy: fix upcoming nightly lints

.gitignore, xtask/src/qemu.rs
Follow-up of #1614 by @kraxel.
- missing file in `.gitignore`
=> cleanup IPConfig2/Http Protocol

uefi-test-runner/Cargo.toml, uefi/CHANGELOG.md, uefi/Cargo.toml, uefi/src/lib.rs
This closes #1170. IMHO, the set of default features depends on the use-case: Are you creating an UEFI image or another type of application. The new doc should help users.
=> doc: help with feature selection

uefi-test-runner/src/proto/mod.rs, uefi-test-runner/src/proto/pci/mod.rs, uefi-test-runner/src/proto/pci/root_bridge.rs, uefi/CHANGELOG.md, uefi/src/proto/mod.rs, uefi/src/proto/pci/mod.rs, uefi/src/proto/pci/root_bridge.rs
This is only a very simple and incomplete version of the API.
Only API for now is direct PCI I/O.
The PCI API is rather ... complicated. Firstly, because of just how versatile the read/write I/O Access methods are. And secondly, because the whole topic is complicated.
Instead of packing all the variants into read() and write(), I instead unpacked each variant as their own prefixed method.
`write()`, `fill_write()`, `fifo_write()`, etc.
=> uefi: Add (partial) safe protocol implementation for PCI_ROOT_BRIDGE_IO_PROTOCOL

Cargo.lock, uefi-test-runner/Cargo.toml, uefi-test-runner/src/proto/network/mod.rs, uefi-test-runner/src/proto/network/pxe.rs, uefi-test-runner/src/proto/network/snp.rs, xtask/src/qemu.rs
**TL;DR**: This adds more clarity to facilitate future debugging and improvements for #1617.
Wow, working on #1617 was an unexpected major time sink. The problem is that if `snp::test` runs before `pxe::test`, `snp.receive()` receives an Ethernet ARP package rather than a Ethernet IPv4 packet.
I tried two solutions:
- perform DHCP in SNP via PXEBaseCode protocol
- Send a raw ethernet frame
I've got none of the approaches to work, unfortunately. So instead, this adds more clarity to ease future debugging and improvements. Relates to #1617 opened by @kraxel.
=> SNP Integration Test: Improve Clarity

.github/workflows/nightly_toolchain.toml, .github/workflows/rust.yml
There are a bunch of new lint errors that need to be addressed before we can successfully build with latest nightly.
(Note that the `+nightly` is dropped here from the `build_standard_uefi_binary` job, because it overrides the toolchain specified in `rust-toolchain.toml`.)
https://github.com/rust-osdev/uefi-rs/issues/1687
=> ci: Temporarily pin to older nightly

uefi/src/lib.rs
just fix the typo of `ctr16!` to `cstr16!`
=> fix typo `ctr16!` to `cstr16!`

uefi-test-runner/src/proto/driver.rs, uefi/src/data_types/strs.rs, uefi/src/fs/path/path.rs, uefi/src/proto/console/gop.rs, uefi/src/proto/device_path/device_path_gen.rs, uefi/src/proto/device_path/mod.rs, uefi/src/proto/driver/component_name.rs, uefi/src/proto/tcg/v1.rs, uefi/src/proto/tcg/v2.rs, xtask/src/device_path/field.rs
Partial fix for https://github.com/rust-osdev/uefi-rs/issues/1687
=> Fix mismatched_lifetime_syntaxes lint

uefi/src/proto/pci/mod.rs
Very useful for pci bus scan/iteration
=> uefi: Make PciIoAddress orderable and hashable

uefi-raw/CHANGELOG.md, uefi-raw/src/protocol/hii/config.rs, uefi-raw/src/protocol/hii/mod.rs
=> uefi-raw: Add HII_CONFIG_ACCESS and CONFIG_KEYWORD_HANDLER protocol bindings

uefi-raw/src/protocol/tcg/v2.rs, uefi/src/lib.rs, uefi/src/proto/scsi/pass_thru.rs, uefi/src/proto/string/unicode_collation.rs
Some of those were found using:
cargo deadlinks --check-intra-doc-links -- --features alloc
=> doc: fix broken links

uefi/CHANGELOG.md, uefi/src/proto/hii/config.rs, uefi/src/proto/hii/config_str.rs, uefi/src/proto/hii/mod.rs, uefi/src/proto/mod.rs
Added stubs for `EFI_HII_CONFIG_ACCESS_PROTOCOL` and `EFI_CONFIG_KEYWORD_HANDLER_PROTOCOL`.
Added initial parser for the `ConfigurationString` according to UEFI Specification 35.2.1.
Unfortunately, the protocols turned out to not be what I was searching for.
I will try to drive this MR to completion as long as it does not become too much work, but I will probably not be adding much more in this direction.
Blocked by (& contains): https://github.com/rust-osdev/uefi-rs/pull/1683
=> uefi: Add HiiKeywordHandler and HiiConfigAccess protocol

uefi-raw/src/protocol/acpi.rs, uefi-raw/src/protocol/mod.rs, uefi/CHANGELOG.md, uefi/src/proto/acpi.rs, uefi/src/proto/mod.rs
Adding the [EFI_ACPI_TABLE_PROTOCOL](https://uefi.org/specs/UEFI/2.10/20_Protocols_ACPI_Protocols.html). I need this for a project I'm working on, for the install API here I've setup something similar to the `boot::install_configuration_table` but set on it's own protocol.
=> protocols: Add ACPI Table protocol

uefi-raw/src/protocol/iommu.rs, uefi-raw/src/protocol/mod.rs
Spiting out IoMmu implementation for `uefi-raw`.
ref: #1728
=> feat: `uefi-raw` IoMmu Protocol Impl

uefi-raw/src/protocol/device_path.rs, uefi-raw/src/table/system.rs, uefi-test-runner/src/proto/pci/root_bridge.rs, uefi-test-runner/src/proto/usb/io.rs, uefi/src/mem/memory_map/impl_.rs, uefi/src/mem/memory_map/mod.rs, uefi/src/mem/util.rs, uefi/src/proto/device_path/device_path_gen.rs, uefi/src/proto/device_path/mod.rs, uefi/src/proto/pci/mod.rs, xtask/src/device_path/mod.rs
As of the 2024 edition, size_of/size_of_val/align_of/align_of_val are in the prelude, so no need to import or use a fully qualified path.
=> Use size_of/align_of from prelude

uefi/CHANGELOG.md, uefi/src/proto/hii/database.rs, uefi/src/proto/hii/mod.rs
This only grants access to the HII-database's raw buffer for now.
=> Add (partial) safe protocol implementation for EFI_HII_DATABASE_PROTOCOL

xtask/src/check_raw.rs
Uncontroversial part from #1741
=> xtask: improved error output for "wrong" repr

uefi-raw/CHANGELOG.md, uefi-raw/src/net.rs
Split-out from #1699 for better reviewability.
=> uefi-raw: various small net improvements

uefi-test-runner/examples/input.rs
https://github.com/rust-osdev/uefi-rs/issues/1754
=> test-runner: Add example of using the Input protocol

uefi-raw/src/protocol/console.rs, uefi/CHANGELOG.md, uefi/src/proto/console/gop.rs, uefi/src/proto/network/snp.rs
Fix some memory safety issues.
=> uefi: memory safety fixes (UB!)

uefi-raw/src/lib.rs, uefi-raw/src/protocol/ata.rs, uefi-raw/src/protocol/console.rs, uefi-raw/src/protocol/console/serial.rs, uefi-raw/src/protocol/device_path.rs, uefi-raw/src/protocol/device_path/device_path_gen.rs, uefi-raw/src/protocol/file_system.rs, uefi-raw/src/protocol/firmware_volume.rs, uefi-raw/src/protocol/hii/config.rs, uefi-raw/src/protocol/hii/database.rs, uefi-raw/src/protocol/hii/mod.rs, uefi-raw/src/protocol/network/dhcp4.rs, uefi-raw/src/protocol/network/http.rs, uefi-raw/src/protocol/network/ip4_config2.rs, uefi-raw/src/protocol/network/pxe.rs, uefi-raw/src/protocol/network/snp.rs, uefi-raw/src/protocol/network/tls.rs, uefi-raw/src/protocol/nvme.rs, uefi-raw/src/protocol/pci/root_bridge.rs, uefi-raw/src/protocol/rng.rs, uefi-raw/src/protocol/scsi.rs, uefi-raw/src/protocol/tcg/enums.rs, uefi-raw/src/protocol/usb/host_controller.rs, uefi-raw/src/protocol/usb/mod.rs, uefi-raw/src/status.rs, uefi-raw/src/table/boot.rs, uefi-raw/src/table/runtime.rs, uefi/src/data_types/mod.rs, xtask/src/device_path/mod.rs
We were inconsistent with the use of the newtype_enum! macro.
Sometimes we imported it directly, sometimes we used it from
the global scope (#[macro_use]). We now prefer an explicit 
dependency for every usage.
=> ci: fix latest nightly issues

uefi/src/boot.rs, uefi/src/data_types/strs.rs, uefi/src/fs/file_system/fs.rs, uefi/src/proto/ata/pass_thru.rs, uefi/src/proto/device_path/text.rs, uefi/src/proto/device_path/util.rs, uefi/src/proto/hii/config_str.rs, uefi/src/proto/nvme/pass_thru.rs, uefi/src/proto/scsi/pass_thru.rs, uefi/src/runtime.rs
Using `clippy::nursery`, I was able to perform the following improvements:
- this PR
- #1758
- #1759
- #1760
=> style: apply/fix more clippy lints (from cargo::nursery)
