- src/table/boot.rs
- tests/src/proto.rs
Added support handle_protocol, and added some code to the protocol test so it actually fills the result buffer properly
> Added support for handle_protocol and updated protocol test

- src/lib.rs
- src/ucs2/mod.rs
- tests/src/main.rs
- tests/src/ucs2.rs
- uefi-logger/src/writer.rs
Added proper UTF-8 to UCS-2 encoding
> UTF-8 to UCS-2 encoding

- src/proto/mod.rs
- src/proto/sfs/mod.rs
Support for Simple File System Protocol
> Filesystem protocol

- src/table/boot.rs
- uefi-test-runner/src/boot.rs
This pull request replaces the current implementation of `get_memory_map` with a better one.
It allows the user to determine how big the buffer should be beforehand, and then provides an iterator for the memory descriptors.
> Improve `get_memory_map` implementation

- src/table/boot.rs
- uefi-test-runner/src/boot/misc.rs
Let's go a bit more into the details of what the watchdog does!
> Improve documentation of the watchdog timer

- .travis.yml
- src/lib.rs
- uefi-alloc/src/lib.rs
- uefi-logger/src/lib.rs
- uefi-test-runner/README.md
- uefi-test-runner/build.py
- uefi-test-runner/src/boot/memory.rs
- uefi-test-runner/src/boot/mod.rs
- uefi-test-runner/src/main.rs
- uefi-test-runner/src/proto/console/gop.rs
- uefi-test-runner/src/proto/console/mod.rs
- uefi-test-runner/src/proto/console/pointer.rs
- uefi-test-runner/src/proto/console/serial.rs
- uefi-test-runner/src/proto/console/stdout.rs
- uefi-test-runner/src/proto/debug.rs
- uefi-test-runner/src/proto/mod.rs
This PR fixes a lot of issues with the build script.
- fixed issues with `argparse` not working
- added option for building in release mode
- documented the new command line arguments.
- Clippy support has been added back, and it's now run in CI.
> Improve Python helper script

- .travis.yml
> Run `rustfmt` in CI

- src/table/boot.rs
- src/table/system.rs
- uefi-logger/src/lib.rs
- uefi-test-runner/src/boot/memory.rs
- uefi-test-runner/src/main.rs
- uefi-test-runner/src/proto/console/gop.rs
This concludes the API tour that I started with #69 , thankfully with much less scope creep :wink:
> End of this pass of uefi-rs review

- uefi-test-runner/README.md
Hi, I ran into a slightly confusing issue when trying this project. Being new to rust, I didn't have cargo-xbuild installed previously. I'm not sure how to best make this suggestion, hopefully this PR is a good place to discuss this idea further.
Thanks!
> Add note about requiring cargo-xbuild to run the tests to README.md

- src/proto/media/file/dir.rs
- src/proto/media/file/info.rs
- src/proto/media/file/mod.rs
- src/table/boot.rs
- src/table/system.rs
> Require correct alignment, but do not enforce it

- src/proto/media/file/dir.rs
- src/proto/media/file/info.rs
- src/proto/media/file/mod.rs
- src/table/boot.rs
This fixes Travis CI presubmits
> Run rustfmt on all files

- src/proto/media/file/mod.rs
To make sure code compiles on latest nightly.
> Remove unwrap after pad_to_align

- src/alloc.rs
- uefi-test-runner/src/boot/memory.rs
Support >8 Bytes alignment by allocating more space and storing the real pointer.
> Implement alignment for allocator

- src/table/system.rs
> Clarify SystemTable docs

- src/exts.rs
Fixes build on latest nightlies.
> Update to new `alloc` API

- Cargo.toml
- uefi-macros/Cargo.toml
- uefi-services/Cargo.toml
- uefi-test-runner/Cargo.toml
Update dependencies and publish new versions of the crates.
> Publish new versions of the crates

- src/proto/console/gop.rs
- src/table/system.rs
- uefi-test-runner/src/boot/memory.rs
Refactors some code to make Clippy happy.
> Fix Clippy lints

- Cargo.toml
- uefi-services/Cargo.toml
Publish new versions due to breaking changes.
> Bump the minor versions of the crates

- src/proto/media/block.rs
- src/proto/media/mod.rs
Adds support to the Block I/O protocol, which allows getting the Block Media to list all devices.
> Add support for the Block I/O protocol

- .github/workflows/rust.yml
- uefi-services/Cargo.toml
- uefi-services/src/lib.rs
- uefi-test-runner/Cargo.toml
- uefi-test-runner/build.py
- uefi-test-runner/src/main.rs
- uefi-test-runner/src/proto/console/serial.rs
- uefi-test-runner/src/proto/pi/mp.rs
Seems the `qemu` package installs something else on the new Ubuntu 20.04 runners.
> Fix running tests in CI

- src/proto/console/gop.rs
Valid mode numbers are 0..max_mode.
> fix(GraphicsOutput::modes): iterate over 0..max_mode

- Cargo.toml
- uefi-macros/Cargo.toml
- uefi-services/Cargo.toml
https://github.com/rust-osdev/uefi-rs/issues/340
> (cargo-release) version 0.14.0

- CHANGELOG.md
Also fixed a typo: "anded" -> "and".
> Update changelog for file info changes

- CHANGELOG.md
- PUBLISHING.md
This PR updates the changelog to reflect the fact that the unpublished changes were included in the latest new versions, and also adds a new section to the `PUBLISHING.md` document with instructions on how to update the changelog's contents.
> Update the changelog

- src/proto/loaded_image.rs
This change add support for getting the file path of the loaded image.
> Add support to get the file path of loaded image

- CHANGELOG.md
- Cargo.toml
- template/Cargo.toml
- uefi-macros/Cargo.toml
- uefi-services/Cargo.toml
Prepares the release of new versions for `uefi-macros` and `uefi`.
> Release new versions of the crates

- CHANGELOG.md
- uefi-services/Cargo.toml
- uefi-services/src/lib.rs
This commit is a breaking change and corresponds to ticket #455
> cargo: additive panic-handler feature

- xtask/Cargo.toml
- xtask/src/disk.rs
- xtask/src/main.rs
- xtask/src/net.rs
- xtask/src/pipe.rs
- xtask/src/platform.rs
- xtask/src/qemu.rs
Fixes https://github.com/rust-osdev/uefi-rs/issues/461
> Allow qemu test to work under Windows without WSL

- .github/workflows/rust.yml
https://github.com/rust-osdev/uefi-rs/issues/488
> Enable CI for version-* branches

- src/data_types/chars.rs
> Fix clippy lint by removing unnecessary cast

- xtask/src/opt.rs
Oops, there's been incorrect copy-pasted text here since a6bdfe54adfd47f3b1b46cfbe3a1c10e3e3a85e8 :sweat_smile:
> Fix `cargo xtask test` help text

- CHANGELOG.md
- Cargo.toml
- book/src/tutorial/app.md
- template/Cargo.toml
- uefi-macros/Cargo.toml
- uefi-services/Cargo.toml
> Publish new releases

- uefi/LICENSE
> Copy LICENSE to the new uefi directory

- uefi-test-runner/src/proto/console/gop.rs
- xtask/src/qemu.rs
> Make GOP test work on aarch64

- book/src/concepts/device_paths.md
> book: Fix link to handles page

- CHANGELOG.md
> changelog: Move some macro-related changes to correct section

- CHANGELOG.md
- book/src/tutorial/app.md
- template/Cargo.toml
- uefi-macros/Cargo.toml
- uefi-services/Cargo.toml
- uefi/Cargo.toml
> Release uefi-macros-0.10.0, uefi-0.19.0, and uefi-services-0.16.0

- CHANGELOG.md
> changelog: Fix a typo

- uefi/src/table/boot.rs
> Fix typo in wait_for_event docstring

- uefi/src/global_allocator.rs
Add more comments and rename some variables. It took me a while of staring at the code to convince myself it was safe, hopefully these comments help the next person who looks at it :)
> uefi: Improve clarity of global_allocator

- CHANGELOG.md
- book/src/tutorial/app.md
- template/Cargo.toml
- uefi-macros/Cargo.toml
- uefi-services/Cargo.toml
- uefi/Cargo.toml
> Merge changes from the 0.20 release

- .github/workflows/rust.yml
- xtask/src/main.rs
A few things I've found in the CI.
> ci: MSRV fixes

- uefi/src/table/runtime.rs
Fill in several padding fields with the correct name and type. This is an internal-only change since these functions aren't yet publically wrapped, so no changelog update needed.
> uefi: Fill in some more RuntimeServices fn pointers

- .github/dependabot.yml
Hopefully got it right this time.
> dependabot: Fix config syntax

- CHANGELOG.md
- uefi/src/result/error.rs
> uefi: Panic if an error is created from Status::SUCCESS

- Cargo.lock
- Cargo.toml
- README.md
- uefi-raw/Cargo.toml
- uefi-raw/LICENSE
- uefi-raw/README.md
- uefi-raw/src/lib.rs
- xtask/src/cargo.rs
This just adds the package and wires it into xtask. Nothing depends on it yet.
> uefi-raw: Add mostly-empty package

- uefi-macros/tests/ui/entry_bad_return_type.stderr
> uefi-macros: Fix compiler test for Rust 1.69

- Cargo.lock
- uefi-macros/Cargo.toml
- uefi-macros/tests/compilation.rs
- uefi-macros/tests/ui/entry_bad_abi.rs
- uefi-macros/tests/ui/entry_bad_abi.stderr
- uefi-macros/tests/ui/entry_bad_arg.rs
- uefi-macros/tests/ui/entry_bad_arg.stderr
- uefi-macros/tests/ui/entry_bad_async.rs
- uefi-macros/tests/ui/entry_bad_async.stderr
- uefi-macros/tests/ui/entry_bad_attr_arg.rs
- uefi-macros/tests/ui/entry_bad_attr_arg.stderr
- uefi-macros/tests/ui/entry_bad_const.rs
- uefi-macros/tests/ui/entry_bad_const.stderr
- uefi-macros/tests/ui/entry_bad_generic.rs
- uefi-macros/tests/ui/entry_bad_generic.stderr
- uefi-macros/tests/ui/entry_bad_return_type.rs
- uefi-macros/tests/ui/entry_bad_return_type.stderr
- uefi-macros/tests/ui/entry_unnamed_image_arg.rs
- uefi-macros/tests/ui/entry_unnamed_image_arg.stderr
- uefi-macros/tests/ui/entry_unnamed_table_arg.rs
- uefi-macros/tests/ui/entry_unnamed_table_arg.stderr
This is a partial revert of 5894e5167bdf3ad0be985b159d8ff17fd8b94a35, where I accidentally deleted too many tests.
> uefi-macros: Restore entry macro tests

- CHANGELOG.md
- Cargo.lock
- book/src/tutorial/app.md
- template/Cargo.toml
- uefi-macros/Cargo.toml
- uefi-services/Cargo.toml
- uefi/Cargo.toml
> Release branch

- CHANGELOG.md
- uefi/src/table/boot.rs
See https://uefi.org/specs/UEFI/2.9_A/07_Services_Boot_Services.html#efi-boot-services-installconfigurationtable
Closes #782
I'm not sure what is needed to do more for that contribution, let me know :).
> uefi(boot_services): add `install_configuration_table`

- uefi-raw/src/capsule.rs
- uefi-raw/src/lib.rs
Note that these are types that were not already in `uefi`, and are not yet exposed there.
> uefi-raw: Add Update Capsule types

- uefi-raw/src/table/runtime.rs
- uefi/src/table/runtime.rs
- uefi/src/table/system.rs
- xtask/src/check_raw.rs
> Add `RuntimeServices` definition to `uefi-raw` and use it from `uefi`

- uefi/README.md
Since there are now more releases since 1.68, drop the "in the future" bit.
> uefi: Update MSRV policy language

- uefi/src/table/boot.rs
As a precursor to using the `uefi_raw` definition of `BootServices` in `uefi`, mark all the function pointers as unsafe and add the necessary `unsafe` blocks to the call sites. This serves to reduce the diff of future PRs.
> uefi: Make BootServices fn ptrs unsafe

- uefi-raw/src/table/boot.rs
Accidentally left a TODO here, replace with `c_void` with `DevicePathProtocol`.
> uefi-raw: Fix arg type in connect_controller

- uefi-raw/src/table/boot.rs
> uefi-raw: Add common derives to `EventType`

- uefi-raw/src/table/configuration.rs
- uefi-raw/src/table/mod.rs
> uefi-raw: Add ConfigurationTable

- uefi-raw/src/protocol/console.rs
- uefi-raw/src/protocol/mod.rs
> uefi-raw: Add SimpleTextInputProtocol and SimpleTextOutputProtocol

- uefi-raw/src/table/header.rs
- uefi-raw/src/table/mod.rs
- uefi-raw/src/table/revision.rs
- uefi-raw/src/table/system.rs
Also added some more derives to `Revision` and `Header`.
> uefi-raw: Add SystemTable

- CHANGELOG.md
- Cargo.lock
- book/src/tutorial/app.md
- template/Cargo.toml
- uefi-macros/Cargo.toml
- uefi-raw/Cargo.toml
- uefi-services/Cargo.toml
- uefi/Cargo.toml
Closes https://github.com/rust-osdev/uefi-rs/issues/872
> Release uefi-raw-0.3.0, uefi-0.24.0, uefi-services-0.21.0

- uefi-raw/src/protocol/loaded_image.rs
- uefi-raw/src/protocol/mod.rs
> uefi-raw: Add LoadedImageProtocol

- uefi-test-runner/src/proto/device_path.rs
> test-runner: Simplify an iterator chain

- CHANGELOG.md
- uefi/src/proto/console/text/input.rs
> uefi: Use uefi_raw's `SimpleTextInputProtocol` in `Input`

- CHANGELOG.md
- uefi-test-runner/src/proto/device_path.rs
- uefi/src/proto/loaded_image.rs
- uefi/src/table/boot.rs
> uefi: Use uefi_raw's `LoadedImageProtocol` to implement `LoadedImage`

- Cargo.lock
> Cargo.lock: Update proc-macro2 to fix nightly CI

- uefi-raw/src/protocol/console.rs
- uefi/src/proto/console/gop.rs
> Add `GraphicsOutputProtocol` to `uefi_raw` and use it from `uefi`

- README.md
- book/src/reference.md
- uefi-raw/README.md
> Add some uefi-raw links/badges

- uefi/src/data_types/unaligned_slice.rs
> Fix a new lint in 1.71

- CHANGELOG.md
- uefi-raw/src/protocol/console.rs
- uefi-raw/src/protocol/console/serial.rs
- uefi/src/proto/console/serial.rs
> Add raw serial protocol and use it in `uefi`

- uefi-raw/src/protocol/disk.rs
- uefi-raw/src/protocol/mod.rs
- uefi/src/proto/media/disk.rs
- uefi/src/table/boot.rs
- uefi/src/util.rs
> Add raw disk protocols and use them in `uefi`

- .github/dependabot.yml
> dependabot: Enable updates for Github Actions

- CHANGELOG.md
- uefi-test-runner/src/proto/pi/mp.rs
- uefi/src/proto/pi/mp.rs
Enables non-blocking ap wakeup.
> add event to smp

- uefi-raw/src/protocol/block.rs
- uefi-raw/src/protocol/mod.rs
- uefi/src/proto/media/block.rs
> Add block I/O protocol to `uefi-raw` and use it in `uefi`

- uefi-raw/src/protocol/block.rs
- uefi/src/proto/media/block.rs
Forgot to add the suffix when implementing this protocol.
> uefi-raw: Rename BlockIo to BlockIoProtocol

- Cargo.toml
- uefi-raw/Cargo.toml
- uefi-services/Cargo.toml
- uefi-test-runner/Cargo.toml
- uefi/Cargo.toml
> Use workspace.dependencies to declare shared dependencies

- uefi-test-runner/src/boot/memory.rs
> Fix 1.72 lints

- .github/dependabot.yml
> github: Change dependabot interval to weekly

- CHANGELOG.md
- Cargo.lock
- book/src/tutorial/app.md
- template/Cargo.toml
- uefi-services/Cargo.toml
Closes https://github.com/rust-osdev/uefi-rs/issues/955
> Release uefi-services-0.22.0

- uefi-raw/Cargo.toml
> uefi-raw: Use workspace dependency for uguid

- Cargo.lock
- book/src/tutorial/app.md
- template/Cargo.toml
- uefi-macros/CHANGELOG.md
- uefi-macros/Cargo.toml
- uefi-raw/CHANGELOG.md
- uefi-raw/Cargo.toml
- uefi-services/CHANGELOG.md
- uefi-services/Cargo.toml
- uefi/CHANGELOG.md
- uefi/Cargo.toml
Once this is merged we see what breaks :)
> release: uefi-raw-0.5.0, uefi-macros-0.13.0, uefi-0.26.0, uefi-services-0.23.0

- book/src/reference.md
> book: Add a link to rust's UEFI target docs

- uefi/CHANGELOG.md
- uefi/src/table/boot.rs
> Add a method to create a MemoryMap from a raw buffer

- uefi/CHANGELOG.md
- uefi/src/data_types/chars.rs
- uefi/src/data_types/owned_strs.rs
- uefi/src/data_types/strs.rs
> uefi: Derive Hash for all char and string types

- uefi/CHANGELOG.md
- uefi/src/data_types/unaligned_slice.rs
> uefi: Add UnalignedSlice::as_ptr

- uefi-raw/CHANGELOG.md
- uefi-raw/src/protocol/device_path.rs
- uefi/src/proto/device_path/text.rs
> Add device path text protocols to uefi-raw and re-use in uefi

- uefi-services/src/lib.rs
> uefi-services: Fix warning with `--no-default-features`

- uefi-raw/Cargo.toml
> uefi-raw: misc

- uefi-test-runner/src/main.rs
- uefi/src/helpers/mod.rs
cargo fmt added these, missed from some other pr
> reorganize deps

- uefi/src/proto/device_path/mod.rs
> uefi: make DevicePathHeader::try_from idiomatic

- uefi/src/helpers/logger.rs
This whole module is already gated by `cfg(feature = "logger")`, so no need to do that inside the module.
> logger: Remove some unnecessary cfgs

- uefi-test-runner/src/runtime/vars.rs
- uefi/src/runtime.rs
> runtime: Add query_variable_info

- uefi-raw/src/capsule.rs
- uefi/src/table/boot.rs
> Fix CI for Rust 1.80

- nix/sources.json
This updates the toolchain coming from Nix. There is no urgent need to do so.
It is just a regular update to ensure that the toolchain for Nix(OS) users work
with the freshest upstream packages.
> nix/niv: update dependencies

- uefi/src/mem/util.rs
- uefi/src/table/boot.rs
> misc small improvements

- Cargo.lock
- book/src/tutorial/app.md
- template/Cargo.toml
- uefi-macros/CHANGELOG.md
- uefi-macros/Cargo.toml
- uefi-raw/CHANGELOG.md
- uefi-raw/Cargo.toml
- uefi/CHANGELOG.md
- uefi/Cargo.toml
> release: uefi-macros-0.15.0, uefi-raw-0.7.0, uefi-0.31.0

- uefi/CHANGELOG.md
> release: uefi-0.31.0

- uefi-test-runner/examples/hello_world.rs
- uefi-test-runner/examples/loaded_image.rs
- uefi-test-runner/examples/shell_params.rs
- uefi-test-runner/examples/sierpinski.rs
- uefi-test-runner/examples/timestamp.rs
Drop all uses of SystemTable, BootServices, and RuntimeServices.
> test-runner: Convert all examples to new style

- uefi-test-runner/src/proto/console/gop.rs
- uefi/CHANGELOG.md
- uefi/src/proto/console/gop.rs
> uefi: Drop BootServices arg from GraphicsOutput::modes

- book/src/how_to/protocols.md
> book: Update protocols how-to to use the `boot` module

- uefi/src/lib.rs
> uefi: Drop args from main in the example

- uefi-macros/src/lib.rs
> uefi-macros: Use uefi::boot::set_image_handle

- template/src/main.rs
> template: Drop args to main

- uefi-macros/src/lib.rs
When applying `entry` to a no-arg main, generate the system table pointer as `*const c_void` rather than `SystemTable<Boot>`. This will avoid unwanted deprecation warnings after `SystemTable` is deprecated.
> uefi-macros: Use raw pointer for system table when generating args

- uefi/src/helpers/logger.rs
- uefi/src/helpers/mod.rs
> uefi: Update logger to use the global system table

- uefi/src/helpers/println.rs
> uefi: Update println to use the global system table

- uefi/src/fs/mod.rs
> uefi: Update FS docstring example code

- uefi/CHANGELOG.md
- uefi/src/prelude.rs
- uefi/src/table/boot.rs
> uefi: Deprecate BootServices

- uefi/src/mem/memory_map/impl_.rs
- uefi/src/mem/memory_map/mod.rs
> uefi/mem: Update docs referring to BootServices

- uefi/src/proto/console/text/input.rs
> uefi: Update input protocol docs

- uefi/src/proto/misc.rs
> uefi: Update ResetNotification protocol docs

- uefi/src/proto/loaded_image.rs
> uefi: Update LoadedImage protocol docs

- uefi/CHANGELOG.md
- uefi/src/fs/file_system/fs.rs
- uefi/src/table/boot.rs
> uefi: Deprecate ancillary types in uefi::table::boot

- uefi/src/proto/console/pointer/mod.rs
> uefi: Update pointer protocol docs

- uefi/CHANGELOG.md
- uefi/src/helpers/mod.rs
- uefi/src/table/mod.rs
> uefi: Deprecate table::{system_table_boot,system_table_runtime}

- uefi/src/boot.rs
- uefi/src/data_types/mod.rs
- uefi/src/lib.rs
- uefi/src/proto/device_path/mod.rs
> uefi: Remove BootServices from more docstrings

- uefi/src/lib.rs
- uefi/src/mem/memory_map/mod.rs
- uefi/src/proto/console/text/output.rs
> uefi: Drop references to SystemTable from docstrings

- docs/funcs_migration.md
> docs: Update timeline for the API migration

- .github/workflows/developer_productivity.yml
- nix/nixpkgs.nix
- nix/rust-toolchain.nix
- nix/sources.json
- nix/sources.nix
- shell.nix
- xtask/src/main.rs
> nix/niv: update formatter (nixpkgs-fmt is deprecated)

- Cargo.lock
- book/src/tutorial/app.md
- template/Cargo.toml
- uefi-macros/CHANGELOG.md
- uefi-macros/Cargo.toml
- uefi-raw/CHANGELOG.md
- uefi-raw/Cargo.toml
- uefi/CHANGELOG.md
- uefi/Cargo.toml
> release: uefi-raw-0.8.0, uefi-macros-0.16.0, uefi-0.32.0

- uefi-test-runner/src/boot/mod.rs
> test-runner: Remove accidental debug log

- uefi/CHANGELOG.md
- uefi/src/allocator.rs
> uefi: Delete deprecated allocator functions

- docs/funcs_migration.md
> Update timeline section of funcs_migration.md

- nix/sources.json
- shell.nix
Follow-up of #1423. Tested on my machine
> nix: add cargo-llvm-cov to nix shell + niv update

- Cargo.lock
- book/src/tutorial/app.md
- template/Cargo.toml
- uefi-macros/CHANGELOG.md
- uefi-macros/Cargo.toml
- uefi-raw/CHANGELOG.md
- uefi-raw/Cargo.toml
- uefi/CHANGELOG.md
- uefi/Cargo.toml
Closes https://github.com/rust-osdev/uefi-rs/issues/893
> release: uefi-raw-0.9.0, uefi-macros-0.17.0, uefi-0.33.0

- uefi-raw/CHANGELOG.md
- uefi-raw/src/protocol/mod.rs
- uefi-raw/src/protocol/string.rs
- uefi/src/proto/string/unicode_collation.rs
> Move the UnicodeCollation protocol definition to `uefi-raw` and use it from `uefi`

- Cargo.lock
- book/src/tutorial/app.md
- template/Cargo.toml
- uefi-macros/CHANGELOG.md
- uefi-macros/Cargo.toml
- uefi-raw/CHANGELOG.md
- uefi-raw/Cargo.toml
- uefi/CHANGELOG.md
- uefi/Cargo.toml
> release: uefi-raw-0.10.0, uefi-macros-0.18.0, uefi-0.34.0

- Cargo.lock
- template/Cargo.toml
- uefi/CHANGELOG.md
- uefi/Cargo.toml
Trivial release so that the correct license info is shown in the crate documentation on docs.rs.
> release: uefi-0.34.1

- uefi/src/proto/network/pxe.rs
This is an intermediate step towards using the uefi-raw definition of the protocol.
> uefi: Mark all function pointers in pxe::BaseCode unsafe

- uefi-test-runner/src/boot/memory.rs
> uefi-test-runner: streamline memory related tests
